#!/usr/bin/env python3
"""Tests for `scripts/sync_sermon_library.py`.

Run:
    python3 -m unittest discover -s test -p 'test_*.py' -v
    python3 test/test_sermon_library.py            # same thing

stdlib `unittest` on purpose: this repo has no pytest and no Python test
infrastructure, and an importer's tests should not be the thing that
adds a dependency to CI.

Two kinds of test live here.

1. GUARD TESTS. Every guard gets a test that feeds it deliberately
   broken input and asserts it fires, plus a test that feeds it good
   input and asserts it stays quiet. These are the tests that were
   mutation-checked: each guard was broken in turn and the mapped test
   was confirmed to fail. A guard no test can make fail is decorative.

2. SNAPSHOT TESTS. Assertions about the committed
   `assets/sermon_library/index.json`, so a bad regeneration is caught
   even if the guards were bypassed. These skip (not fail) when the
   snapshot is absent, so a fresh clone that has not run the sync yet
   still gets a green guard suite.
"""

import importlib.util
import json
import os
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(REPO, 'scripts', 'sync_sermon_library.py')
INDEX = os.path.join(REPO, 'assets', 'sermon_library', 'index.json')

_spec = importlib.util.spec_from_file_location('sync_sermon_library', SCRIPT)
sl = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sl)


# ── Fixtures ──────────────────────────────────────────────────────

def make_message(mid, body='正文' * 200, author_terms=(1,),
                 author_simple='', audio=(10,), book=(100,)):
    """One API-shaped `message` record."""
    return {
        'id': mid,
        'slug': f'slug-{mid}',
        'link': f'https://fuyindiantai.org/message/slug-{mid}/',
        'title': {'rendered': f'讲道 {mid}'},
        'date': '2020-01-01T00:00:00',
        'modified': '2020-01-02T00:00:00',
        'content': {'rendered': ''},
        'content_author': list(author_terms),
        'zhuantixilie': [],
        'shujuanchakao': list(book),
        'shengjingyishenlun': [],
        'qimiaoendian': [],
        'shengmingzaisi': [],
        'jiangdaoxinxi': [],
        'acf': {
            'refcode': f'RC{mid}',
            'author_simple': author_simple,
            'transcription_displayed': f'<p>{body}</p>' if body else '',
            'audio_recording_mp3': [{'mp3_recording': a} for a in audio],
            'transcription_doc_pdf': None,
            'mobile_version_transcript': None,
            'video': None,
        },
    }


TERMS = {
    'content_author': {1: {'name': '张成牧师', 'slug': 'zc', 'count': 1},
                       2: {'name': '奇妙恩典', 'slug': 'qmed', 'count': 1}},
    'zhuantixilie': {},
    'shujuanchakao': {100: {'name': '马太福音', 'slug': 'mt', 'count': 1}},
    'shengjingyishenlun': {},
    'qimiaoendian': {},
    'shengmingzaisi': {},
    'jiangdaoxinxi': {},
}

MEDIA = {10: {'url': 'https://fuyindiantai.org/wp-content/uploads/a.mp3',
              'mime': 'audio/mpeg'},
         11: {'url': 'https://fuyindiantai.org/wp-content/uploads/b.mp3',
              'mime': 'audio/mpeg'}}


def rows_from(messages, terms=None, media=None):
    rows, _ = sl.build_records(messages, terms or TERMS, media or MEDIA)
    return rows


def good_corpus(n=None):
    """A corpus that clears every floor."""
    n = n or sl.MIN_RECORDS
    return [make_message(1000 + i) for i in range(n)]


# ── Transform ─────────────────────────────────────────────────────

class TestBodyText(unittest.TestCase):

    def test_one_line_per_source_paragraph(self):
        html = '<p>第一段</p>\r\n<p>第二段</p>'
        self.assertEqual(sl.body_text(html), '第一段\n第二段')

    def test_does_not_invent_paragraph_breaks(self):
        """A single long paragraph must come out as ONE line.

        The app's rule for the other sermon corpus is that nothing
        re-paragraphs another man's sermon; this pins it here.
        """
        html = '<p>' + ('句子。' * 300) + '</p>'
        self.assertEqual(len(sl.body_text(html).split('\n')), 1)

    def test_strips_tags_and_decodes_entities(self):
        html = '<p><span style="x"><strong>a</strong>&amp;b</span></p>'
        self.assertEqual(sl.body_text(html), 'a&b')

    def test_empty_inputs(self):
        for v in ('', None, '   ', False, 0, []):
            self.assertEqual(sl.body_text(v), '')


class TestCleanTitle(unittest.TestCase):
    """Direct tests for `clean_title`.

    These exist because of a mutation result: breaking the entity
    decoding was originally SURVIVED by the whole suite. The only test
    that looked like it covered this asserted over the COMMITTED
    snapshot, which was generated by correct code and therefore stays
    green no matter what the code later does. A snapshot assertion
    cannot catch a code regression — it needs a unit test underneath it.
    """

    def test_decodes_html_entities(self):
        """7 of the 940 upstream titles carry entities."""
        self.assertEqual(sl.clean_title('&#8220;a&#8221;'), '\u201ca\u201d')
        self.assertEqual(sl.clean_title('a &amp; b'), 'a & b')

    def test_strips_tags(self):
        self.assertEqual(sl.clean_title('<em>论舌头</em>'), '论舌头')

    def test_collapses_whitespace(self):
        self.assertEqual(sl.clean_title('  a \n\t b  '), 'a b')

    def test_blank_becomes_none(self):
        for v in ('', '   ', None, '<em></em>'):
            self.assertIsNone(sl.clean_title(v))


class TestAuthorAttribution(unittest.TestCase):

    def test_taxonomy_wins(self):
        m = make_message(1, author_terms=(1,), author_simple='其他人')
        self.assertEqual(sl.resolve_author(m, TERMS),
                         ('张成牧师', 'taxonomy', 'person'))

    def test_legacy_fallback_when_no_term(self):
        m = make_message(1, author_terms=(), author_simple='凉水')
        self.assertEqual(sl.resolve_author(m, TERMS),
                         ('凉水', 'legacy_field', 'person'))

    def test_numeric_legacy_value_is_refused(self):
        """"9" / "3" / "10" are stale term ids, not names."""
        m = make_message(1, author_terms=(), author_simple='9')
        self.assertEqual(sl.resolve_author(m, TERMS), (None, 'none', None))

    def test_unattributed_is_none_not_placeholder(self):
        m = make_message(1, author_terms=(), author_simple='')
        name, source, kind = sl.resolve_author(m, TERMS)
        self.assertIsNone(name)
        self.assertEqual(source, 'none')
        self.assertNotIn(name, ('', '未知', '福音电台'))

    def test_programme_author_flagged_not_person(self):
        m = make_message(1, author_terms=(2,))
        self.assertEqual(sl.resolve_author(m, TERMS),
                         ('奇妙恩典', 'taxonomy', 'programme'))


class TestBuildRecords(unittest.TestCase):

    def test_shape_and_fields(self):
        rows = rows_from([make_message(1)])
        self.assertEqual(tuple(rows[0].keys()), sl.FIELD_ORDER)

    def test_multi_part_audio_is_a_list(self):
        """44 real records carry more than one mp3."""
        rows = rows_from([make_message(1, audio=(10, 11))])
        self.assertEqual(len(rows[0]['audioUrls']), 2)

    def test_bodyless_record_is_kept_not_dropped(self):
        """Ruling: a body-less record is emitted, not skipped."""
        rows = rows_from([make_message(1, body='')])
        self.assertEqual(len(rows), 1)
        self.assertFalse(rows[0]['hasBody'])
        self.assertIsNone(rows[0]['bodyFile'])
        self.assertEqual(rows[0]['title'], '讲道 1')

    def test_book_reference_resolved(self):
        self.assertEqual(rows_from([make_message(1)])[0]['book'], '马太福音')


# ── Guards ────────────────────────────────────────────────────────

class TestGuardStructural(unittest.TestCase):
    """The guard that separates 'no transcript' from 'field renamed'."""

    def test_quiet_on_good_input(self):
        self.assertEqual(sl.guard_structural(good_corpus(3)), [])

    def test_quiet_when_body_merely_empty(self):
        """97 real records are legitimately body-less. Not a failure."""
        msgs = [make_message(1, body=''), make_message(2, body='')]
        self.assertEqual(sl.guard_structural(msgs), [])

    def test_fires_when_acf_object_missing(self):
        msgs = good_corpus(3)
        msgs[0]['acf'] = None
        self.assertTrue(sl.guard_structural(msgs))

    def test_fires_when_body_key_renamed(self):
        msgs = good_corpus(3)
        del msgs[1]['acf']['transcription_displayed']
        fails = sl.guard_structural(msgs)
        self.assertTrue(fails)
        self.assertIn('transcription_displayed', fails[0])


class TestGuardFloors(unittest.TestCase):

    def test_quiet_on_good_input(self):
        self.assertEqual(sl.guard_floors(rows_from(good_corpus())), [])

    def test_fires_on_short_crawl(self):
        rows = rows_from(good_corpus(sl.MIN_RECORDS - 1))
        self.assertTrue(any('records' in f for f in sl.guard_floors(rows)))

    def test_fires_when_bodies_stop_rendering(self):
        msgs = good_corpus()
        for m in msgs[:sl.MIN_RECORDS - sl.MIN_BODIED + 1]:
            m['acf']['transcription_displayed'] = ''
        self.assertTrue(any('body' in f for f in
                            sl.guard_floors(rows_from(msgs))))

    def test_fires_when_audio_resolution_fails(self):
        """Attachment lookup returning nothing must not write silently."""
        rows, _ = sl.build_records(good_corpus(), TERMS, {})
        self.assertTrue(any('audio' in f for f in sl.guard_floors(rows)))


class TestGuardHosts(unittest.TestCase):

    def test_quiet_on_both_real_hosts(self):
        rows = rows_from(good_corpus(2))
        rows[0]['url'] = 'https://fydt.org/message/x/'
        self.assertEqual(sl.guard_hosts(rows), [])

    def test_fires_on_foreign_host(self):
        rows = rows_from(good_corpus(2))
        rows[0]['url'] = 'https://evil.example.com/message/x/'
        self.assertTrue(sl.guard_hosts(rows))

    def test_fires_on_foreign_media_host(self):
        rows = rows_from(good_corpus(2))
        rows[0]['audioUrls'] = ['https://cdn.example.net/a.mp3']
        self.assertTrue(sl.guard_hosts(rows))


class TestGuardIdentity(unittest.TestCase):

    def test_quiet_on_good_input(self):
        self.assertEqual(sl.guard_identity(rows_from(good_corpus(5))), [])

    def test_fires_on_duplicate_ids(self):
        rows = rows_from([make_message(1), make_message(1)])
        self.assertTrue(any('duplicate' in f
                            for f in sl.guard_identity(rows)))

    def test_fires_on_missing_title(self):
        rows = rows_from(good_corpus(3))
        rows[0]['title'] = None
        self.assertTrue(any('title' in f for f in sl.guard_identity(rows)))


class TestGuardUnresolvedTerms(unittest.TestCase):

    def test_quiet_on_good_input(self):
        self.assertEqual(sl.guard_unresolved_terms(good_corpus(3), TERMS), [])

    def test_fires_when_term_fetch_truncated(self):
        """A short taxonomy fetch would otherwise blank authors silently."""
        terms = {k: dict(v) for k, v in TERMS.items()}
        terms['content_author'] = {}
        fails = sl.guard_unresolved_terms(good_corpus(3), terms)
        self.assertTrue(any('content_author' in f for f in fails))


class TestGuardAuthorCollapse(unittest.TestCase):

    def test_quiet_without_previous_snapshot(self):
        self.assertEqual(
            sl.guard_author_collapse(rows_from(good_corpus(3)), []), [])

    def test_quiet_when_stable(self):
        rows = rows_from(good_corpus(20))
        self.assertEqual(sl.guard_author_collapse(rows, rows), [])

    def test_fires_when_author_halves(self):
        before = rows_from(good_corpus(20))
        after = rows_from(good_corpus(9))
        self.assertTrue(sl.guard_author_collapse(after, before))

    def test_fires_when_author_disappears_at_any_size(self):
        before = rows_from([make_message(1, author_terms=(2,))])
        after = rows_from([make_message(1, author_terms=(1,))])
        fails = sl.guard_author_collapse(after, before)
        self.assertTrue(any('奇妙恩典' in f for f in fails))


class TestRunGuards(unittest.TestCase):

    def test_clean_corpus_passes_every_guard(self):
        msgs = good_corpus()
        self.assertEqual(sl.run_guards(msgs, rows_from(msgs), TERMS, []), [])

    def test_run_guards_aggregates(self):
        msgs = good_corpus(3)
        msgs[0]['acf'] = None
        self.assertTrue(sl.run_guards(msgs, rows_from(msgs), TERMS, []))


# ── Committed snapshot ────────────────────────────────────────────

def load_snapshot():
    if not os.path.exists(INDEX):
        return None
    with open(INDEX, encoding='utf-8') as f:
        return json.load(f)


@unittest.skipIf(load_snapshot() is None, 'snapshot not generated yet')
class TestSnapshot(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.doc = load_snapshot()
        cls.rows = cls.doc['sermons']
        cls.meta = cls.doc['_meta']

    def test_record_count_matches_upstream_total(self):
        """940 is upstream's own x-wp-total, measured 2026-09-05."""
        self.assertEqual(len(self.rows), 940)
        self.assertEqual(self.meta['count'], 940)

    def test_ids_unique(self):
        ids = [r['id'] for r in self.rows]
        self.assertEqual(len(set(ids)), len(ids))

    def test_every_record_has_a_title(self):
        self.assertEqual([r['id'] for r in self.rows if not r['title']], [])

    def test_no_html_entities_left_in_titles(self):
        """7 upstream titles carry entities; they must not reach the UI."""
        bad = [r['id'] for r in self.rows
               if r['title'] and ('&#' in r['title'] or '&amp;' in r['title'])]
        self.assertEqual(bad, [])

    def test_body_and_audio_coverage_holds(self):
        self.assertGreaterEqual(self.meta['withBody'], sl.MIN_BODIED)
        self.assertGreaterEqual(self.meta['withAudio'], sl.MIN_WITH_AUDIO)

    def test_attribution_accounts_for_every_record(self):
        by = self.meta['byAuthorSource']
        self.assertEqual(by['taxonomy'] + by['legacy_field'] + by['none'],
                         len(self.rows))

    def test_no_placeholder_author(self):
        for r in self.rows:
            self.assertNotIn(r['author'], ('', '未知', 'unknown'))

    def test_author_source_none_implies_no_author(self):
        for r in self.rows:
            if r['authorSource'] == 'none':
                self.assertIsNone(r['author'])
            else:
                self.assertIsNotNone(r['author'])

    def test_programme_authors_are_live_taxonomy_terms(self):
        """The hardcoded set must not rot: every name in it has to still
        appear as an author upstream, or the flag is silently dead."""
        seen = {r['author'] for r in self.rows}
        for name in sl.PROGRAMME_AUTHORS:
            self.assertIn(name, seen,
                          f'{name} is in PROGRAMME_AUTHORS but no longer '
                          f'appears upstream — re-check the taxonomy')

    def test_programme_authors_flagged(self):
        for r in self.rows:
            if r['author'] in sl.PROGRAMME_AUTHORS:
                self.assertEqual(r['authorKind'], 'programme')
            elif r['author']:
                self.assertEqual(r['authorKind'], 'person')

    def test_every_url_on_an_allowed_host(self):
        self.assertEqual(sl.guard_hosts(self.rows), [])

    def test_canonical_host_is_the_cms_siteurl(self):
        self.assertEqual(self.meta['canonicalHost'], 'fuyindiantai.org')

    def test_rights_recorded_without_inventing_a_licence(self):
        self.assertTrue(self.meta['rights'])
        self.assertTrue(self.meta['rightsNote'])
        for forbidden in ('CC BY', 'Creative Commons', 'public domain',
                          'MIT', 'GPL'):
            self.assertNotIn(forbidden, self.meta['rightsNote'])
            self.assertNotIn(forbidden, self.meta['rightsEn'])

    def test_body_files_match_the_index(self):
        base = os.path.dirname(INDEX)
        claimed = {r['bodyFile'] for r in self.rows if r['bodyFile']}
        for rel in claimed:
            self.assertTrue(os.path.exists(os.path.join(base, rel)), rel)
        on_disk = {f'bodies/{n}' for n in
                   os.listdir(os.path.join(base, 'bodies'))
                   if n.endswith('.txt')}
        self.assertEqual(on_disk - claimed, set(),
                         'orphan body files not referenced by the index')

    def test_bodyless_records_still_carry_metadata(self):
        """The 97 body-less records are kept, per the skip ruling."""
        bodyless = [r for r in self.rows if not r['hasBody']]
        self.assertTrue(bodyless)
        for r in bodyless:
            self.assertTrue(r['title'])
            self.assertTrue(r['url'])


if __name__ == '__main__':
    unittest.main(verbosity=2)
