import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';
import 'package:yswords/constants/bible_versions.dart';
import 'package:yswords/constants/book_names.dart';

/// The four texts imported from the 雅伟的话 export on 2026-09-08 —
/// BSB, BSB (Yahweh), ASV (Yahweh) and the Westcott-Hort Greek NT.
///
/// `tools/import_ydh_texts.py` already refuses to write a file whose
/// counts are wrong, so the obvious objection to this file is that it
/// re-checks work the importer will not let you get wrong. It does not:
/// the importer guards the moment of writing, and nothing guards the
/// asset afterwards. An asset can be regenerated by a modified script,
/// truncated by a bad merge, or — the case this repo has actually lived
/// through — edited by hand. These read the files that ship.
///
/// The expectations are parsed out of the importer's own `TEXTS` table
/// rather than typed here, so there is exactly one place where "the BSB
/// has 31,086 verses" is written down. `offline_pack_counts_test.dart`
/// reads `bible_versions.dart` as source text the same way and for the
/// same reason.
void main() {
  final importer =
      File('tools/import_ydh_texts.py').readAsStringSync();

  /// `Text('bsb', 'bsbs', 31102, 66, 16, …)` → the numbers.
  ({int verses, int books, int empty}) declared(String code) {
    final m = RegExp("Text\\('$code', '[a-z]+', (\\d+), (\\d+), (\\d+),")
        .firstMatch(importer);
    expect(m, isNotNull,
        reason: 'tools/import_ydh_texts.py no longer declares $code');
    return (
      verses: int.parse(m!.group(1)!),
      books: int.parse(m.group(2)!),
      empty: int.parse(m.group(3)!),
    );
  }

  List<Map<String, dynamic>> load(String code) =>
      (json.decode(File('assets/$code.json').readAsStringSync()) as List)
          .cast<Map<String, dynamic>>();

  /// Every English book name, in canonical order, taken from the KJV —
  /// the one bundled asset that is 66 books in canonical order and
  /// nothing else. Deriving the order beats typing 66 names, which is
  /// 66 chances to file Philemon's text under Philippians;
  /// `tools/import_csb.py::book_map` makes the same argument.
  final canon = <String>{
    for (final v in load('kjv')) v['book'] as String
  }.toList();

  // Plain BSB was imported here on 2026-09-08 and removed the same
  // day on the owner's instruction 「bsbs 不用，就 bsb yahweh 版本导入」.
  // It stays buildable (`tools/import_ydh_texts.py bsb`), so the
  // source mapping below still names it; only the shipped list drops it.
  const shipped = ['bsb-yhwh', 'asv-yhwh', 'wh'];

  group('the four texts are the shape their importer promises', () {
    for (final code in shipped) {
      test('$code holds every verse the source has and no blank ones', () {
        final d = declared(code);
        final verses = load(code);
        // The file omits the verses the source carries as empty rows —
        // the critical text's Acts 8:37 and friends — because every
        // other bundled asset in this repo omits a verse it does not
        // have rather than shipping a blank one, and
        // `bible_version_integrity_test.dart` fails on an empty string.
        expect(verses, hasLength(d.verses - d.empty),
            reason: '$code should hold ${d.verses} source verses less '
                'the ${d.empty} the source leaves empty');
        expect(verses.where((v) => (v['text'] as String).trim().isEmpty),
            isEmpty);
      });

      test('$code covers exactly the books its testament contains', () {
        final d = declared(code);
        final books = load(code).map((v) => v['book'] as String).toSet();
        expect(books, hasLength(d.books));
        // Not just "the right number" — the right ones, in canonical
        // order and contiguous. A file holding 27 books of which one is
        // Malachi would pass a count.
        final positions = books.map(canon.indexOf).toList()..sort();
        expect(positions.first, code == 'wh' ? 39 : 0,
            reason: '$code should start at '
                '${code == 'wh' ? 'Matthew' : 'Genesis'}');
        expect(positions.last, canon.length - 1);
        expect(positions,
            List.generate(d.books, (i) => positions.first + i),
            reason: '$code skips a book in the middle of its canon');
      });

      test('$code keys books the way the rest of the app does', () {
        // A book name that falls through `bookNameToEnglish` keeps its
        // own spelling in `Verse.id`, which silently detaches every
        // highlight and note on that book from the same verse in every
        // other translation. It is why the Greek text uses English book
        // names: a Greek book-name column exists nowhere in this app.
        final unmapped = <String>{
          for (final v in load(code))
            if (!bookNameToEnglish.containsKey(v['book']))
              v['book'] as String
        };
        expect(unmapped, isEmpty);
      });

      test('$code carries no leftover markup from the source module', () {
        // The source is theWord markup — `<WH3068>`, `<WTN-GSM>`,
        // `<CL>`, `<redletter>`. `import_ydh_texts.py` maps all of it
        // and refuses to write a file with a tag left in; this is the
        // same claim made about the file that shipped.
        final tag = RegExp(r'<[^>]{1,20}>');
        final offenders = <String>[];
        for (final v in load(code)) {
          final hit = tag.firstMatch(v['text'] as String);
          if (hit != null) {
            offenders.add('${v['book']} ${v['chapter']}:${v['verse']} — '
                '${hit.group(0)}');
          }
        }
        expect(offenders, isEmpty);
      });

      test('$code numbers every verse uniquely and consistently', () {
        final verses = load(code);
        final ids = verses.map((v) => v['id'] as String).toSet();
        expect(ids, hasLength(verses.length));
        for (final v in verses) {
          final id = v['id'] as String;
          expect(id, hasLength(9));
          expect(int.parse(id.substring(0, 3)),
              canon.indexOf(v['book'] as String) + 1,
              reason: 'the id of ${v['book']} ${v['chapter']}:'
                  '${v['verse']} does not agree with its own book');
          expect(int.parse(id.substring(3, 6)),
              int.parse(v['chapter'] as String));
          expect(int.parse(id.substring(6)),
              int.parse(v['verse'] as String));
        }
      });
    }

    test('the Westcott-Hort is the New Testament and only that', () {
      final books = load('wh').map((v) => v['book'] as String).toSet();
      expect(books, contains('Matthew'));
      expect(books, contains('Revelation'));
      expect(books, isNot(contains('Genesis')));
      expect(books, isNot(contains('Malachi')));
      // NT-only editions need a full-canon partner or the daily-verse
      // card comes up empty on an Old Testament reference. The WH is
      // the first one whose own language family has none to offer.
      // Repointed to bsb-yhwh on 2026-09-08 when plain BSB was removed
      // on the owner's instruction. Same translation; the Yahweh
      // edition only restores the divine name, so the reasoning in
      // bible_versions.dart transfers intact.
      expect(bibleVersionFullCanonFallback('wh'), 'bsb-yhwh');
      expect(bibleVersionFullCanonFallback('bsb-yhwh'), isNull);
    });

    test('the three whole-Bible texts cover both testaments', () {
      for (final code in ['bsb-yhwh', 'asv-yhwh']) {
        final books = load(code).map((v) => v['book'] as String).toSet();
        expect(books, contains('Genesis'), reason: code);
        expect(books, contains('Malachi'), reason: code);
        expect(books, contains('Matthew'), reason: code);
        expect(books, contains('Revelation'), reason: code);
        expect(bibleVersionFullCanonFallback(code), isNull, reason: code);
      }
    });
  });

  group('which of them read the divine name, and where', () {
    String verse(List<Map<String, dynamic>> v, String book, int c, int n) =>
        v.firstWhere((r) =>
            r['book'] == book &&
            r['chapter'] == '$c' &&
            r['verse'] == '$n')['text'] as String;

    // The 'plain BSB is the control' test lived here until 2026-09-08,
    // when plain BSB stopped shipping. It read the LORD in the Shema
    // and the Shepherd psalm and held no Yahweh at all, which is what
    // made it the control; the next test still pins the restored
    // reading directly against the source database, so nothing that
    // test proved is now unproven.

    test('BSB (Yahweh) reads the name in the Shema and the Shepherd '
        'psalm, where the plain BSB reads the LORD', () {
      final v = load('bsb-yhwh');
      expect(verse(v, 'Deuteronomy', 6, 4),
          'Hear, O Israel: Yahweh our God, Yahweh is One.');
      expect(verse(v, 'Psalms', 23, 1),
          'A Psalm of David. Yahweh is my shepherd; I shall not want.');
      expect(verse(v, 'Exodus', 3, 15), contains('Yahweh'));
      // The census, not just three verses: a restoration that reached
      // the famous passages and missed the other five thousand would
      // pass the three assertions above.
      expect(v.where((r) => (r['text'] as String).contains('Yahweh')),
          hasLength(5942));
    });

    test('ASV (Yahweh) reads Yahweh where the 1901 ASV printed Jehovah',
        () {
      final v = load('asv-yhwh');
      expect(verse(v, 'Deuteronomy', 6, 4),
          'Hear, O Israel: Yahweh our God is one Yahweh:');
      expect(verse(v, 'Psalms', 23, 1),
          'A Psalm of David. Yahweh is my shepherd; I shall not want.');
      expect(verse(v, 'Exodus', 6, 3), contains('Yahweh'));
      expect(v.where((r) => (r['text'] as String).contains('Yahweh')),
          hasLength(5787));

      // The restoration is CASE-SENSITIVE, and the four verses it
      // leaves behind are the evidence. Mixed-case Jehovah is gone
      // everywhere — the altar names included, Genesis 22:14 reads
      // Yahweh-jireh — but four verses print the name in CAPITALS
      // because they are quoting an inscription, and all four still say
      // JEHOVAH:
      //
      //   Exod 28:36 / 39:30  "HOLY TO JEHOVAH", engraved on the plate
      //   Deut 28:58          "this glorious and fearful name,
      //                        JEHOVAH THY GOD"
      //   Zech 14:20          "HOLY UNTO JEHOVAH; and the pots in
      //                        Yahweh's house"
      //
      // Zechariah 14:20 is the one that settles what this is: both
      // spellings, one verse, the capitals inside the quoted inscription
      // and the restored name in the narration around it. So the four
      // are a boundary the restoration drew, not four it missed — and
      // this repo does not re-translate anybody's text to tidy up a
      // boundary its publisher drew.
      //
      // (Written after guessing wrong: the first version of this test
      // said these were place names like Jehovah-jireh, on the strength
      // of a `LIKE` query that is case-insensitive in SQLite and so
      // could not see the thing that actually distinguishes them.)
      // Case-INSENSITIVE to find them and case-SENSITIVE to judge them.
      // `contains('Jehovah')` finds none of the four, because all four
      // are shouting; a search that cannot see them would have reported
      // a clean sweep and been believed.
      final anyCase = RegExp(r'\bjehovah\b', caseSensitive: false);
      final shouting = RegExp(r'\bJEHOVAH\b');
      final left =
          v.where((r) => anyCase.hasMatch(r['text'] as String)).toList();
      expect(left, hasLength(4));
      for (final r in left) {
        expect(shouting.hasMatch(r['text'] as String), isTrue,
            reason: '${r['book']} ${r['chapter']}:${r['verse']} reads '
                'Jehovah in ordinary case — that is one the restoration '
                'missed, not one it deliberately left');
      }
      expect(verse(v, 'Genesis', 22, 14), contains('Yahweh-jireh'));
      expect(verse(v, 'Zechariah', 14, 20),
          allOf(contains('HOLY UNTO JEHOVAH'), contains("Yahweh's house")));
    });

    test('the Greek New Testament has no divine name to restore, and '
        'none has been put there', () {
      final v = load('wh');
      expect(v.where((r) => (r['text'] as String).contains('Yahweh')),
          isEmpty);
      // John 1:1, in the Greek this module actually holds — unaccented,
      // which is the module's own orthography and not a stripping this
      // repo did.
      expect(
          v.firstWhere((r) =>
              r['book'] == 'John' &&
              r['chapter'] == '1' &&
              r['verse'] == '1')['text'],
          'εν αρχη ην ο λογος και ο λογος ην προς τον θεον και θεος ην ο '
          'λογος');
    });
  });

  group('the CSB is offered once, not twice', () {
    // The export carries a text called "CSB (Yahweh)" (`hcsbs`) and it
    // is the module `assets/csb.json` was already built from. Shipping
    // it beside `csb` would put 6 MB of a licensed text in the bundle
    // twice — and label the copy with FEWER occurrences of the divine
    // name "(Yahweh)", next to the row that has more. The reasoning is
    // on the catalogue entry in `bible_versions.dart`; these are the
    // assertions that keep it from being undone by accident.
    test('the catalogue holds one CSB, and a reader can reach it', () {
      final csbs = bibleVersions
          .where((v) => v.value.startsWith('csb'))
          .map((v) => v.value)
          .toList();
      expect(csbs, ['csb']);
      expect(availableVersions.map((v) => v.value), contains('csb'));
      expect(resolvableVersion('csb'), 'csb');
    });

    test('no second CSB asset is declared or bundled', () {
      expect(File('assets/csb-yhwh.json').existsSync(), isFalse);
      final pubspec = File('pubspec.yaml').readAsStringSync();
      expect(pubspec, contains('assets/csb.json'));
      expect(pubspec, isNot(contains('assets/csb-yhwh.json')));
    });

    test('the importer can still build it, and says it is not shipped',
        () {
      // Not shipped is a decision, not a gap. The script keeps the
      // recipe so that answering the question is an asset and a
      // catalogue entry rather than a fresh investigation — and the
      // same is true of the Septuagint beside it.
      expect(importer, contains("Text('csb-yhwh', 'hcsbs'"));
      expect(importer, contains("Text('lxx', 'lxxs'"));
      final ships = RegExp(r'SHIPPED = \{([^}]*)\}').firstMatch(importer);
      expect(ships, isNotNull);
      expect(ships!.group(1), isNot(contains('csb-yhwh')));
      expect(ships.group(1), isNot(contains("'lxx'")));
      for (final code in shipped) {
        expect(ships.group(1), contains("'$code'"));
      }
    });

    test('the Septuagint is not shipped either, and for its own reason',
        () {
      expect(File('assets/lxx.json').existsSync(), isFalse);
      expect(bibleVersions.map((v) => v.value), isNot(contains('lxx')));
      // The Greek tab exists for the Westcott-Hort alone. If the LXX
      // question is ever answered, this is the assertion that has to be
      // changed on purpose.
      expect(versionsForLanguage('el').map((v) => v.value), ['wh']);
    });
  });

  group('the app can actually load them', () {
    // Everything else in this file reads the assets with `dart:io`,
    // which proves the files are on disk and proves nothing about
    // whether the app can reach them. The app reads them through
    // `rootBundle.loadString('assets/<code>.json')`, and that resolves
    // through `pubspec.yaml`'s asset list — so a file that exists but
    // was never declared passes every other test here and then throws
    // "Unable to load asset" on the reader's first tap.
    //
    // That is not hypothetical in this repo: `resolvableVersion` exists
    // because v1.4.193/194 shipped a version code whose asset the build
    // did not contain, and the app failed to paint at all on every
    // English-locale web client.
    //
    // **`rootBundle.load`, never `rootBundle.loadString` — the latter
    // hangs the entire suite.** `AssetBundle.loadString` decodes inline
    // only below 50 KB; above it (`asset_bundle.dart:95`) it hands the
    // bytes to `compute()`, which spawns an isolate. Under
    // `flutter_test` that isolate never completes, and because these
    // assets are 2-6.5 MB every one of them takes that branch. The
    // first version of this group used `loadString` and wedged the run
    // for 31 minutes with 2 seconds of CPU burnt — a hang, not a slow
    // test, and indistinguishable from one until you look at process
    // times. Decoding the bytes here costs a line and stays on this
    // thread. (The app's own `FetchVerses` calls `loadString` and is
    // right to: isolates work fine outside the test binding.)
    //
    // This is the same shape as the trap recorded in
    // `verse_card_service.dart` — an await that resolves in the app and
    // never resolves under `flutter_test`.
    setUp(TestWidgetsFlutterBinding.ensureInitialized);

    for (final code in shipped) {
      testWidgets('$code is declared in pubspec and loads from the bundle',
          (tester) async {
        final bytes = await rootBundle.load('assets/$code.json');
        final raw = utf8.decode(Uint8List.sublistView(bytes));
        expect(json.decode(raw) as List, isNotEmpty);
      });
    }

    test('every version the picker offers has an asset behind it', () {
      // The general form of the same bug, so a future edition added
      // without its file fails here rather than in the reader's hands.
      for (final v in availableVersions) {
        expect(File('assets/${v.value}.json').existsSync(), isTrue,
            reason: '${v.value} is offered in the picker but '
                'assets/${v.value}.json does not exist');
        expect(File('pubspec.yaml').readAsStringSync(),
            contains('assets/${v.value}.json'),
            reason: '${v.value} has an asset file that pubspec.yaml does '
                'not declare, so it will not be in the build');
      }
    });
  });

  group('measured against the source database itself', () {
    // Everything above reads the shipped assets and the importer's
    // declared contract. This reads the export the assets were made
    // from, which is the only check that can catch the importer and its
    // own declarations being wrong together.
    //
    // It is skipped when the export is not on this machine — it is a
    // 182 MB file in another project, not a fixture this repo owns —
    // and it is written to be a real failure rather than a silent pass
    // when it does run.
    const db = String.fromEnvironment('YDH_DB', defaultValue: '');
    final path = db.isNotEmpty
        ? db
        : '${Platform.environment['HOME']}/Documents/CodingProject/'
            'Yahwehdehua/app/build/bible.db';
    final available = File(path).existsSync() &&
        Process.runSync('which', ['sqlite3']).exitCode == 0;

    String query(String sql) {
      final r = Process.runSync('sqlite3', [path, sql]);
      expect(r.exitCode, 0, reason: r.stderr.toString());
      return (r.stdout as String).trim();
    }

    // Shipped assets only. 'bsb' -> 'bsbs' is a real mapping and
    // tools/import_ydh_texts.py still carries it, but plain BSB stopped
    // shipping on 2026-09-08 (「bsbs 不用」), so there is no asset here
    // to measure against the database.
    const sources = {
      'bsb-yhwh': 'bsbys',
      'asv-yhwh': 'asvs',
      'wh': 'whs',
    };

    test('every shipped verse exists in the export, and every non-empty '
        'export verse ships', () {
      for (final entry in sources.entries) {
        final counts = query(
          "SELECT COUNT(*), SUM(TRIM(plain) = '') FROM verses "
          "WHERE version = '${entry.value}'",
        ).split('|');
        final total = int.parse(counts[0]);
        final empty = int.parse(counts[1]);
        expect(load(entry.key), hasLength(total - empty),
            reason: '${entry.key} vs `${entry.value}` in the export');
      }
    }, skip: available ? false : 'the 雅伟的话 export is not on this machine');

    test('the canon of each shipped text is the canon of its source', () {
      for (final entry in sources.entries) {
        final books = int.parse(query(
          "SELECT COUNT(DISTINCT book) FROM verses "
          "WHERE version = '${entry.value}' AND TRIM(plain) != ''",
        ));
        expect(load(entry.key).map((v) => v['book']).toSet(),
            hasLength(books),
            reason: entry.key);
      }
    }, skip: available ? false : 'the 雅伟的话 export is not on this machine');

    test('"CSB (Yahweh)" in the export is the CSB this app already '
        'ships, which is why it is not shipped again', () {
      // The claim on the catalogue entry, checked rather than asserted
      // in prose: the two texts agree on the overwhelming majority of
      // verses, and where they differ it is the shipped `csb` that
      // reads the divine name MORE often — the opposite of what a row
      // labelled "(Yahweh)" would promise.
      final csb = load('csb');
      final named = csb
          .where((v) => (v['text'] as String).contains('Yahweh'))
          .length;
      final sourceNamed = int.parse(query(
        "SELECT COUNT(*) FROM verses WHERE version = 'hcsbs' "
        "AND plain LIKE '%Yahweh%'",
      ));
      expect(sourceNamed, lessThan(named),
          reason: 'the export module reads Yahweh in $sourceNamed verses '
              'and the shipped csb in $named; if that ever reverses, the '
              'reason this text is not shipped has changed');
      expect(
        query("SELECT plain FROM verses WHERE version = 'hcsbs' "
            "AND book = 'Deut' AND chapter = 6 AND verse = 4"),
        contains('The Lord our God'),
      );
      expect(
        csb.firstWhere((v) =>
            v['book'] == 'Deuteronomy' &&
            v['chapter'] == '6' &&
            v['verse'] == '4')['text'],
        contains('Yahweh our God'),
      );
    }, skip: available ? false : 'the 雅伟的话 export is not on this machine');
  });
}
