// 2026-05-19 (v1.2.54): URL-friendly slugs for every canonical
// English book name. Used by the URL sync layer to produce / parse
// hash-based deep links like:
//
//   /#/genesis/1            → Genesis 1
//   /#/john/3:16            → John 3:16
//   /#/1samuel/16:13?v=leb  → 1 Samuel 16:13 in LEB
//   /#/songofsolomon/2:4
//
// Slugs are lowercase canonical English, with all whitespace
// collapsed (so "1 Samuel" → "1samuel", "Song of Solomon" →
// "songofsolomon"). The reverse map accepts a few common aliases
// (`gen`, `ex`, `lev`, `1sam`, `revelation`/`rev`, `psalm`/`psalms`)
// so shared / typed URLs that aren't fully canonical still resolve.

/// Canonical English book name → URL slug. Lowercase, no spaces,
/// no punctuation. Generated programmatically from `standardBookOrder`
/// at static-data time so changes only need to happen in one place.
const Map<String, String> bookToSlug = {
  // Old Testament
  'Genesis': 'genesis',
  'Exodus': 'exodus',
  'Leviticus': 'leviticus',
  'Numbers': 'numbers',
  'Deuteronomy': 'deuteronomy',
  'Joshua': 'joshua',
  'Judges': 'judges',
  'Ruth': 'ruth',
  '1 Samuel': '1samuel',
  '2 Samuel': '2samuel',
  '1 Kings': '1kings',
  '2 Kings': '2kings',
  '1 Chronicles': '1chronicles',
  '2 Chronicles': '2chronicles',
  'Ezra': 'ezra',
  'Nehemiah': 'nehemiah',
  'Esther': 'esther',
  'Job': 'job',
  'Psalms': 'psalms',
  'Proverbs': 'proverbs',
  'Ecclesiastes': 'ecclesiastes',
  'Song of Solomon': 'songofsolomon',
  'Isaiah': 'isaiah',
  'Jeremiah': 'jeremiah',
  'Lamentations': 'lamentations',
  'Ezekiel': 'ezekiel',
  'Daniel': 'daniel',
  'Hosea': 'hosea',
  'Joel': 'joel',
  'Amos': 'amos',
  'Obadiah': 'obadiah',
  'Jonah': 'jonah',
  'Micah': 'micah',
  'Nahum': 'nahum',
  'Habakkuk': 'habakkuk',
  'Zephaniah': 'zephaniah',
  'Haggai': 'haggai',
  'Zechariah': 'zechariah',
  'Malachi': 'malachi',
  // New Testament
  'Matthew': 'matthew',
  'Mark': 'mark',
  'Luke': 'luke',
  'John': 'john',
  'Acts': 'acts',
  'Romans': 'romans',
  '1 Corinthians': '1corinthians',
  '2 Corinthians': '2corinthians',
  'Galatians': 'galatians',
  'Ephesians': 'ephesians',
  'Philippians': 'philippians',
  'Colossians': 'colossians',
  '1 Thessalonians': '1thessalonians',
  '2 Thessalonians': '2thessalonians',
  '1 Timothy': '1timothy',
  '2 Timothy': '2timothy',
  'Titus': 'titus',
  'Philemon': 'philemon',
  'Hebrews': 'hebrews',
  'James': 'james',
  '1 Peter': '1peter',
  '2 Peter': '2peter',
  '1 John': '1john',
  '2 John': '2john',
  '3 John': '3john',
  'Jude': 'jude',
  'Revelation': 'revelation',
};

/// Slug → canonical English book name. Reverse of [bookToSlug],
/// plus common short aliases (`gen`, `ex`, `rev`, `1sam`, etc.)
/// so users typing or sharing partial slugs still resolve cleanly.
const Map<String, String> slugToBook = {
  // Canonical full slugs (mirrors bookToSlug)
  'genesis': 'Genesis',
  'exodus': 'Exodus',
  'leviticus': 'Leviticus',
  'numbers': 'Numbers',
  'deuteronomy': 'Deuteronomy',
  'joshua': 'Joshua',
  'judges': 'Judges',
  'ruth': 'Ruth',
  '1samuel': '1 Samuel',
  '2samuel': '2 Samuel',
  '1kings': '1 Kings',
  '2kings': '2 Kings',
  '1chronicles': '1 Chronicles',
  '2chronicles': '2 Chronicles',
  'ezra': 'Ezra',
  'nehemiah': 'Nehemiah',
  'esther': 'Esther',
  'job': 'Job',
  'psalms': 'Psalms',
  'proverbs': 'Proverbs',
  'ecclesiastes': 'Ecclesiastes',
  'songofsolomon': 'Song of Solomon',
  'isaiah': 'Isaiah',
  'jeremiah': 'Jeremiah',
  'lamentations': 'Lamentations',
  'ezekiel': 'Ezekiel',
  'daniel': 'Daniel',
  'hosea': 'Hosea',
  'joel': 'Joel',
  'amos': 'Amos',
  'obadiah': 'Obadiah',
  'jonah': 'Jonah',
  'micah': 'Micah',
  'nahum': 'Nahum',
  'habakkuk': 'Habakkuk',
  'zephaniah': 'Zephaniah',
  'haggai': 'Haggai',
  'zechariah': 'Zechariah',
  'malachi': 'Malachi',
  'matthew': 'Matthew',
  'mark': 'Mark',
  'luke': 'Luke',
  'john': 'John',
  'acts': 'Acts',
  'romans': 'Romans',
  '1corinthians': '1 Corinthians',
  '2corinthians': '2 Corinthians',
  'galatians': 'Galatians',
  'ephesians': 'Ephesians',
  'philippians': 'Philippians',
  'colossians': 'Colossians',
  '1thessalonians': '1 Thessalonians',
  '2thessalonians': '2 Thessalonians',
  '1timothy': '1 Timothy',
  '2timothy': '2 Timothy',
  'titus': 'Titus',
  'philemon': 'Philemon',
  'hebrews': 'Hebrews',
  'james': 'James',
  '1peter': '1 Peter',
  '2peter': '2 Peter',
  '1john': '1 John',
  '2john': '2 John',
  '3john': '3 John',
  'jude': 'Jude',
  'revelation': 'Revelation',
  // Short / common aliases (lowercased, no punctuation)
  'gen': 'Genesis',
  'ex': 'Exodus',
  'exo': 'Exodus',
  'lev': 'Leviticus',
  'num': 'Numbers',
  'deut': 'Deuteronomy',
  'josh': 'Joshua',
  'judg': 'Judges',
  '1sam': '1 Samuel',
  '2sam': '2 Samuel',
  '1ki': '1 Kings',
  '2ki': '2 Kings',
  '1ch': '1 Chronicles',
  '2ch': '2 Chronicles',
  'neh': 'Nehemiah',
  'est': 'Esther',
  'ps': 'Psalms',
  'psa': 'Psalms',
  'psalm': 'Psalms',
  'prov': 'Proverbs',
  'eccl': 'Ecclesiastes',
  'song': 'Song of Solomon',
  'sos': 'Song of Solomon',
  'isa': 'Isaiah',
  'jer': 'Jeremiah',
  'lam': 'Lamentations',
  'eze': 'Ezekiel',
  'ezek': 'Ezekiel',
  'dan': 'Daniel',
  'hos': 'Hosea',
  'oba': 'Obadiah',
  'obad': 'Obadiah',
  'mic': 'Micah',
  'nah': 'Nahum',
  'hab': 'Habakkuk',
  'zeph': 'Zephaniah',
  'hag': 'Haggai',
  'zech': 'Zechariah',
  'zec': 'Zechariah',
  'mal': 'Malachi',
  'matt': 'Matthew',
  'mt': 'Matthew',
  'mk': 'Mark',
  'lk': 'Luke',
  'jn': 'John',
  'rom': 'Romans',
  '1cor': '1 Corinthians',
  '2cor': '2 Corinthians',
  'gal': 'Galatians',
  'eph': 'Ephesians',
  'phil': 'Philippians',
  'col': 'Colossians',
  '1th': '1 Thessalonians',
  '1thes': '1 Thessalonians',
  '2th': '2 Thessalonians',
  '2thes': '2 Thessalonians',
  '1tim': '1 Timothy',
  '2tim': '2 Timothy',
  'phlm': 'Philemon',
  'phm': 'Philemon',
  'heb': 'Hebrews',
  'jas': 'James',
  '1pet': '1 Peter',
  '1pe': '1 Peter',
  '2pet': '2 Peter',
  '2pe': '2 Peter',
  '1jn': '1 John',
  '2jn': '2 John',
  '3jn': '3 John',
  'rev': 'Revelation',
};

/// Canonical English book → slug, with `null` for an unknown book
/// (caller should fall back to writing no URL update).
String? slugForBook(String englishBook) => bookToSlug[englishBook];

/// Slug → canonical English book, with `null` for an unknown slug.
/// Input is lowercased + whitespace-stripped before lookup, so
/// `'Gen'`, `'gen'`, `'GEN '` all match.
String? bookForSlug(String slug) {
  final normalised = slug.toLowerCase().replaceAll(RegExp(r'\s+'), '');
  return slugToBook[normalised];
}
