const englishToChinese = {
  // Old Testament (Simplified)
  "Genesis": "创世记",
  "Exodus": "出埃及记",
  "Leviticus": "利未记",
  "Numbers": "民数记",
  "Deuteronomy": "申命记",
  "Joshua": "约书亚记",
  "Judges": "士师记",
  "Ruth": "路得记",
  "1 Samuel": "撒母耳记上",
  "2 Samuel": "撒母耳记下",
  "1 Kings": "列王纪上",
  "2 Kings": "列王纪下",
  "1 Chronicles": "历代志上",
  "2 Chronicles": "历代志下",
  "Ezra": "以斯拉记",
  "Nehemiah": "尼希米记",
  "Esther": "以斯帖记",
  "Job": "约伯记",
  "Psalms": "诗篇",
  "Proverbs": "箴言",
  "Ecclesiastes": "传道书",
  "Song of Solomon": "雅歌",
  "Isaiah": "以赛亚书",
  "Jeremiah": "耶利米书",
  "Lamentations": "耶利米哀歌",
  "Ezekiel": "以西结书",
  "Daniel": "但以理书",
  "Hosea": "何西阿书",
  "Joel": "约珥书",
  "Amos": "阿摩司书",
  "Obadiah": "俄巴底亚书",
  "Jonah": "约拿书",
  "Micah": "弥迦书",
  "Nahum": "那鸿书",
  "Habakkuk": "哈巴谷书",
  "Zephaniah": "西番雅书",
  "Haggai": "哈该书",
  "Zechariah": "撒迦利亚书",
  "Malachi": "玛拉基书",

  // New Testament (Simplified)
  "Matthew": "马太福音",
  "Mark": "马可福音",
  "Luke": "路加福音",
  "John": "约翰福音",
  "Acts": "使徒行传",
  "Romans": "罗马书",
  "1 Corinthians": "哥林多前书",
  "2 Corinthians": "哥林多后书",
  "Galatians": "加拉太书",
  "Ephesians": "以弗所书",
  "Philippians": "腓立比书",
  "Colossians": "歌罗西书",
  "1 Thessalonians": "帖撒罗尼迦前书",
  "2 Thessalonians": "帖撒罗尼迦后书",
  "1 Timothy": "提摩太前书",
  "2 Timothy": "提摩太后书",
  "Titus": "提多书",
  "Philemon": "腓利门书",
  "Hebrews": "希伯来书",
  "James": "雅各书",
  "1 Peter": "彼得前书",
  "2 Peter": "彼得后书",
  "1 John": "约翰一书",
  "2 John": "约翰二书",
  "3 John": "约翰三书",
  "Jude": "犹大书",
  "Revelation": "启示录",
};

const englishToChineseTraditional = {
  // Old Testament
  "Genesis": "創世紀",
  "Exodus": "出埃及記",
  "Leviticus": "利未記",
  "Numbers": "民數記",
  "Deuteronomy": "申命記",
  "Joshua": "約書亞記",
  "Judges": "士師記",
  "Ruth": "路得記",
  "1 Samuel": "撒母耳記上",
  "2 Samuel": "撒母耳記下",
  "1 Kings": "列王紀上",
  "2 Kings": "列王紀下",
  "1 Chronicles": "歷代志上",
  "2 Chronicles": "歷代志下",
  "Ezra": "以斯拉記",
  "Nehemiah": "尼希米記",
  "Esther": "以斯帖記",
  "Job": "約伯記",
  "Psalms": "詩篇",
  "Proverbs": "箴言",
  "Ecclesiastes": "傳道書",
  "Song of Solomon": "雅歌",
  "Isaiah": "以賽亞書",
  "Jeremiah": "耶利米書",
  "Lamentations": "耶利米哀歌",
  "Ezekiel": "以西結書",
  "Daniel": "但以理書",
  "Hosea": "何西阿書",
  "Joel": "約珥書",
  "Amos": "阿摩司書",
  "Obadiah": "俄巴底亞書",
  "Jonah": "約拿書",
  "Micah": "彌迦書",
  "Nahum": "那鴻書",
  "Habakkuk": "哈巴谷書",
  "Zephaniah": "西番雅書",
  "Haggai": "哈該書",
  "Zechariah": "撒迦利亞書",
  "Malachi": "瑪拉基書",

  // New Testament
  "Matthew": "馬太福音",
  "Mark": "馬可福音",
  "Luke": "路加福音",
  "John": "約翰福音",
  "Acts": "使徒行傳",
  "Romans": "羅馬書",
  "1 Corinthians": "哥林多前書",
  "2 Corinthians": "哥林多後書",
  "Galatians": "加拉太書",
  "Ephesians": "以弗所書",
  "Philippians": "腓立比書",
  "Colossians": "歌羅西書",
  "1 Thessalonians": "帖撒羅尼迦前書",
  "2 Thessalonians": "帖撒羅尼迦後書",
  "1 Timothy": "提摩太前書",
  "2 Timothy": "提摩太後書",
  "Titus": "提多書",
  "Philemon": "腓利門書",
  "Hebrews": "希伯來書",
  "James": "雅各書",
  "1 Peter": "彼得前書",
  "2 Peter": "彼得後書",
  "1 John": "約翰一書",
  "2 John": "約翰二書",
  "3 John": "約翰三書",
  "Jude": "猶大書",
  "Revelation": "啟示錄",
};

// 常见的中文别写（简/繁 / 异体字）→ 英文键，用于容错
// 常见的中文别写（简 / 繁 / 异体字 / 旧译名）→ 英文键
const _zhAliasToEn = {
  // ===== Old Testament =====
  '创世纪': 'Genesis', '創世紀': 'Genesis', '创世记': 'Genesis', '創世記': 'Genesis',
  '出埃及记': 'Exodus', '出埃及記': 'Exodus',
  '利未记': 'Leviticus', '利未記': 'Leviticus',
  '民数记': 'Numbers', '民數記': 'Numbers',
  '申命记': 'Deuteronomy', '申命記': 'Deuteronomy',
  '约书亚记': 'Joshua', '約書亞記': 'Joshua',
  '士师记': 'Judges', '士師記': 'Judges',
  '路得记': 'Ruth', '路得記': 'Ruth',
  '撒母耳记上': '1 Samuel', '撒母耳記上': '1 Samuel',
  '撒母耳记下': '2 Samuel', '撒母耳記下': '2 Samuel',
  '列王纪上': '1 Kings', '列王紀上': '1 Kings',
  '列王纪下': '2 Kings', '列王紀下': '2 Kings',
  '历代志上': '1 Chronicles', '歷代志上': '1 Chronicles',
  '历代志下': '2 Chronicles', '歷代志下': '2 Chronicles',
  '以斯拉记': 'Ezra', '以斯拉記': 'Ezra',
  '尼希米记': 'Nehemiah', '尼希米記': 'Nehemiah',
  '以斯帖记': 'Esther', '以斯帖記': 'Esther',
  '约伯记': 'Job', '約伯記': 'Job',
  '诗篇': 'Psalms', '詩篇': 'Psalms',
  '箴言': 'Proverbs',
  '传道书': 'Ecclesiastes', '傳道書': 'Ecclesiastes',
  '雅歌': 'Song of Solomon',
  '以赛亚书': 'Isaiah', '以賽亞書': 'Isaiah',
  '耶利米书': 'Jeremiah', '耶利米書': 'Jeremiah',
  '耶利米哀歌': 'Lamentations',
  '以西结书': 'Ezekiel', '以西結書': 'Ezekiel',
  '但以理书': 'Daniel', '但以理書': 'Daniel',
  '何西阿书': 'Hosea', '何西阿書': 'Hosea',
  '约珥书': 'Joel', '約珥書': 'Joel',
  '阿摩司书': 'Amos', '阿摩司書': 'Amos',
  '俄巴底亚书': 'Obadiah', '俄巴底亞書': 'Obadiah',
  '约拿书': 'Jonah', '約拿書': 'Jonah',
  '弥迦书': 'Micah', '彌迦書': 'Micah',
  '那鸿书': 'Nahum', '那鴻書': 'Nahum',
  '哈巴谷书': 'Habakkuk', '哈巴谷書': 'Habakkuk',
  '西番雅书': 'Zephaniah', '西番雅書': 'Zephaniah',
  '哈该书': 'Haggai', '哈該書': 'Haggai',
  '撒迦利亚书': 'Zechariah', '撒迦利亞書': 'Zechariah',
  '玛拉基书': 'Malachi', '瑪拉基書': 'Malachi',

  // ===== New Testament =====
  '马太福音': 'Matthew', '馬太福音': 'Matthew',
  '马可福音': 'Mark', '馬可福音': 'Mark',
  '路加福音': 'Luke',
  '约翰福音': 'John', '約翰福音': 'John',
  '使徒行传': 'Acts', '使徒行傳': 'Acts',
  '罗马书': 'Romans', '羅馬書': 'Romans',
  '哥林多前书': '1 Corinthians', '哥林多前書': '1 Corinthians',
  '哥林多后书': '2 Corinthians', '哥林多後書': '2 Corinthians',
  '加拉太书': 'Galatians', '加拉太書': 'Galatians',
  '以弗所书': 'Ephesians', '以弗所書': 'Ephesians',
  '腓立比书': 'Philippians', '腓立比書': 'Philippians',
  '歌罗西书': 'Colossians', '歌羅西書': 'Colossians',
  '帖撒罗尼迦前书': '1 Thessalonians', '帖撒羅尼迦前書': '1 Thessalonians',
  '帖撒罗尼迦后书': '2 Thessalonians', '帖撒羅尼迦後書': '2 Thessalonians',
  '提摩太前书': '1 Timothy', '提摩太前書': '1 Timothy',
  '提摩太后书': '2 Timothy', '提摩太後書': '2 Timothy',
  '提多书': 'Titus', '提多書': 'Titus',
  '腓利门书': 'Philemon', '腓利門書': 'Philemon',
  '希伯来书': 'Hebrews', '希伯來書': 'Hebrews',
  '雅各书': 'James', '雅各書': 'James',
  '彼得前书': '1 Peter', '彼得前書': '1 Peter',
  '彼得后书': '2 Peter', '彼得後書': '2 Peter',
  '约翰一书': '1 John', '約翰一書': '1 John',
  '约翰二书': '2 John', '約翰二書': '2 John',
  '约翰三书': '3 John', '約翰三書': '3 John',
  '犹大书': 'Jude', '猶大書': 'Jude',
  '启示录': 'Revelation', '啟示錄': 'Revelation',
};

/// 把中文书名（简体或繁体）转换为英文键；若找不到则返回 null
String? zhToEn(String name) {
  final hitHans = englishToChinese.entries
      .firstWhere((e) => e.value == name, orElse: () => const MapEntry('', ''));
  if (hitHans.key.isNotEmpty) return hitHans.key;

  final hitHant = englishToChineseTraditional.entries
      .firstWhere((e) => e.value == name, orElse: () => const MapEntry('', ''));
  if (hitHant.key.isNotEmpty) return hitHant.key;

  // 别写容错
  return _zhAliasToEn[name];
}

String toLocale(String englishKey, String version) {
  if (version == 'kjv' || version == 'leb') return englishKey;
  return version.endsWith('-tr')
      ? englishToChineseTraditional[englishKey] ?? englishKey
      : englishToChinese[englishKey] ?? englishKey;
}
