// GENERATED FROM A ONE-OFF SOURCE, THEN OWNED HERE. Edit this file
// directly; there is no generator to re-run. 繁體 was produced with
// OpenCC (`opencc -c s2twp`) and then corrected where its Taiwan
// phrasing differs from what this app already says on screen:
//   插圖 → 插畫
//   重新檢視導覽 → 重新查看導覽
//   傳送測試通知 → 發送測試通知
//   彙總 → 匯總
//   字型 → 字體
//   母音 → 元音
//   映象 → 鏡像
//   重灌 → 重新安裝
//   型別 → 類型
//   位址列 → 網址列
//   新增到主螢幕 → 加入主畫面
//   畫素 → 像素
//   意見反饋 → 意見回饋
//   生成圖片 → 產生圖片
//   開啟分屏閱讀 → 打開分屏閱讀
//   靈脩 → 靈修
// Writing new 繁體 by the same route? Apply the same list.
//
// ignore_for_file: lines_longer_than_80_chars

/// Everything the Help page says about Yahweh's Words — see `help_catalog.dart`
/// for the model and the rules, and `test/help_catalog_test.dart` for
/// what keeps it honest (every path key exists, every example key
/// exists, every destination opens, the searches people actually type
/// find something).
///
/// Written against the code on 2026-09-18, not against the README,
/// which is allowed to drift; a help page must not inherit that. Where a
/// sentence names a menu, it names it with the menu's own label.
library;

import 'package:yahwehs_words/utils/help_catalog.dart';

const List<HelpTopic> kHelpTopics = [
  HelpTopic(
    id: 'overview',
    section: HelpSection.start,
    title: HelpText(
      '雅伟之言是什么',
      '雅偉之言是什麼',
      'What Yahweh\'s Words is',
    ),
    body: HelpText(
      '雅伟之言是一个中英双语的读经 app：可以读多个中英文译本、看原文、查经、做笔记，也能听讲道和诗歌。\n\n打开后先看到主页，从上到下是：\n• 读经：接着上次读到的地方\n• 继续讲道、每日金句\n• 收藏 / 笔记 / 高亮的数量和最近收藏\n• 今日证据\n• 快捷入口：搜索、我的收藏、讲道、设置，以及更多探索\n• 精选推荐：诗歌、年代对照图\n\n主页显示哪些区块，可以在「设置」›「主页布局」里选。',
      '雅偉之言是一箇中英雙語的讀經 app：可以讀多箇中英文譯本、看原文、查經、做筆記，也能聽講道和詩歌。\n\n開啟後先看到主頁，從上到下是：\n• 讀經：接著上次讀到的地方\n• 繼續講道、每日金句\n• 收藏 / 筆記 / 高亮的數量和最近收藏\n• 今日證據\n• 快捷入口：搜尋、我的收藏、講道、設定，以及更多探索\n• 精選推薦：詩歌、年代對照圖\n\n主頁顯示哪些區塊，可以在「設定」›「主頁佈局」裡選。',
      'Yahweh\'s Words is a bilingual Bible reader: several Chinese and English versions, the original languages, search, notes, and sermons and songs to listen to.\n\nIt opens on the home page, which runs top to bottom:\n• Read Bible: back to where you left off\n• Resume sermon, Verse of the Day\n• Your bookmark, note and highlight counts, and recent bookmarks\n• Today\'s Evidence\n• Quick links: Search, Library, Sermons, Settings, and Explore more\n• Featured: Songs and the chronology chart\n\nChoose which of these appear in Settings › Home layout.',
    ),
    path: ['settings', 'settingsSectionDashboard'],
    keywords: [
      '介绍',
      'introduction',
      'home',
      '主页',
      '首页',
      'dashboard',
      '仪表盘',
      'overview',
      '概览',
      'layout',
      '布局',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'help',
    section: HelpSection.start,
    title: HelpText(
      '怎么用这份说明',
      '怎麼用這份說明',
      'Using this help',
    ),
    body: HelpText(
      '打开这里的方法：主页快捷入口的「使用说明」、「设置」最上面的「使用说明与快捷键」、阅读页右上角「⋯」›「使用说明」，或者接上键盘时在经文里按 ?。\n\n• 顶上的搜索框可以用中文（简繁都行）或英文搜，例如「字体」「split」「高亮」。\n• 平台选项默认是你正在用的设备；换一个就能看到同一功能在 iPhone、Android、电脑或网页上怎么用。\n• 标着「带我去」的条目，点一下直接打开那个功能。',
      '開啟這裡的方法：主頁快捷入口的「使用說明」、「設定」最上面的「使用說明與快捷鍵」、閱讀頁右上角「⋯」›「使用說明」，或者接上鍵盤時在經文裡按 ?。\n\n• 頂上的搜尋框可以用中文（簡繁都行）或英文搜，例如「字體」「split」「高亮」。\n• 平臺選項預設是你正在用的裝置；換一個就能看到同一功能在 iPhone、Android、電腦或網頁上怎麼用。\n• 標著「帶我去」的條目，點一下直接開啟那個功能。',
      'Ways in: the Help tile in Quick links on the home page, Help & shortcuts at the top of Settings, ⋯ › Help at the top right of the reader, or ? in the text with a keyboard attached.\n\n• The search box takes Chinese (simplified or traditional) or English — "font", "分屏", "highlight".\n• The platform choice starts on the device you are using; switch it to see how the same feature works on an iPhone, Android, a computer or the web.\n• Entries marked "Take me there" open the feature directly.',
    ),
    path: ['settings', 'helpTitle'],
    keywords: [
      'help',
      '帮助',
      '说明',
      '找不到',
      'where',
      '在哪',
      'manual',
      '手册',
      'guide',
      '教程',
      'tutorial',
      '?',
    ],
  ),
  HelpTopic(
    id: 'tour',
    section: HelpSection.start,
    title: HelpText(
      '再看一遍新手导览',
      '再看一遍新手導覽',
      'Seeing the tour again',
    ),
    body: HelpText(
      '第一次打开时的几页介绍，可以在「设置」›「重新查看导览」再看一遍。',
      '第一次開啟時的幾頁介紹，可以在「設定」›「重新查看導覽」再看一遍。',
      'The pages shown the first time the app opens: Settings › Show tour again brings them back.',
    ),
    path: ['settings', 'showTourAgain'],
    keywords: [
      'tour',
      '导览',
      'onboarding',
      '新手',
      '入门',
      'introduction',
      'welcome',
      '欢迎',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'go-to',
    section: HelpSection.reading,
    title: HelpText(
      '翻到某卷、某章',
      '翻到某卷、某章',
      'Going to a book and chapter',
    ),
    body: HelpText(
      '点阅读页顶上的书卷名，打开书卷列表（可以切换网格和列表），选卷再选章。\n\n• 左右滑动经文：上一章、下一章\n• 在搜索框里打「约 3:16」「John 3:16」「罗 12:1-2」，直接跳到那一节\n• 主页的「读经」回到上次读到的地方',
      '點閱讀頁頂上的書卷名，開啟書卷列表（可以切換網格和列表），選卷再選章。\n\n• 左右滑動經文：上一章、下一章\n• 在搜尋框裡打「約 3:16」「John 3:16」「羅 12:1-2」，直接跳到那一節\n• 主頁的「讀經」回到上次讀到的地方',
      'Tap the book name at the top of the reader to open the book list (grid or list view), then pick a book and a chapter.\n\n• Swipe the text sideways: previous and next chapter\n• Type "John 3:16", "约 3:16" or "Rom 12:1-2" into Search to go straight to the verse\n• Read Bible on the home page returns to where you left off',
    ),
    keywords: [
      '跳转',
      'jump',
      'goto',
      'navigate',
      '书卷',
      'book',
      'chapter',
      'verse',
      '章',
      '节',
      '目录',
      'contents',
      '上一章',
      '下一章',
      'previous',
      'next',
      '翻页',
      'swipe',
      '滑动',
    ],
    notes: {
      HelpPlatform.macos: HelpText(
        '用键盘：[ 和 ] 上一章下一章，也可以用 ⌘[ ⌘]。',
        '用鍵盤：[ 和 ] 上一章下一章，也可以用 ⌘[ ⌘]。',
        'On the keyboard: [ and ] for previous and next chapter, or ⌘[ ⌘].',
      ),
      HelpPlatform.windows: HelpText(
        '用键盘：[ 和 ] 上一章下一章，也可以用 Ctrl+[ Ctrl+]。',
        '用鍵盤：[ 和 ] 上一章下一章，也可以用 Ctrl+[ Ctrl+]。',
        'On the keyboard: [ and ] for previous and next chapter, or Ctrl+[ Ctrl+].',
      ),
      HelpPlatform.linux: HelpText(
        '用键盘：[ 和 ] 上一章下一章，也可以用 Ctrl+[ Ctrl+]。',
        '用鍵盤：[ 和 ] 上一章下一章，也可以用 Ctrl+[ Ctrl+]。',
        'On the keyboard: [ and ] for previous and next chapter, or Ctrl+[ Ctrl+].',
      ),
      HelpPlatform.web: HelpText(
        '用键盘：[ 和 ] 上一章下一章。',
        '用鍵盤：[ 和 ] 上一章下一章。',
        'On the keyboard: [ and ] for previous and next chapter.',
      ),
    },
  ),
  HelpTopic(
    id: 'versions',
    section: HelpSection.reading,
    title: HelpText(
      '切换译本',
      '切換譯本',
      'Changing the version',
    ),
    body: HelpText(
      '点阅读页顶上书卷名旁边的版本名，从列表里选另一个译本。想同时看两个译本，用分屏阅读。',
      '點閱讀頁頂上書卷名旁邊的版本名，從列表裡選另一個譯本。想同時看兩個譯本，用分屏閱讀。',
      'Tap the version name beside the book name at the top of the reader and choose another. To read two versions at once, use Split View.',
    ),
    keywords: [
      'version',
      'translation',
      '译本',
      '版本',
      '和合本',
      'KJV',
      'NASB',
      'LEB',
      '梁家铿',
      '切换',
      'switch',
      'change',
    ],
  ),
  HelpTopic(
    id: 'split',
    section: HelpSection.reading,
    title: HelpText(
      '分屏阅读：两个译本并排',
      '分屏閱讀：兩個譯本並排',
      'Split View: two versions side by side',
    ),
    body: HelpText(
      '阅读页右上角「⋯」›「打开分屏阅读」。两个阅读栏完全独立，各自选书卷、章和译本。\n\n手机上是上下两栏，平板和电脑上是左右两栏；中间的分隔条可以拖动调大小。再点一次同一个菜单项就关闭分屏。',
      '閱讀頁右上角「⋯」›「打開分屏閱讀」。兩個閱讀欄完全獨立，各自選書卷、章和譯本。\n\n手機上是上下兩欄，平板和電腦上是左右兩欄；中間的分隔條可以拖動調大小。再點一次同一個選單項就關閉分屏。',
      'At the top right of the reader: ⋯ › Open Split View. The two panes are fully independent — each has its own book, chapter and version.\n\nOn a phone they sit one above the other, on a tablet or computer side by side; drag the divider between them to resize. The same menu item closes it.',
    ),
    path: ['more', 'openSplitView'],
    keywords: [
      'split',
      '分屏',
      '并排',
      '对照',
      'parallel',
      'compare',
      '两个译本',
      'two versions',
      'side by side',
      '双栏',
    ],
  ),
  HelpTopic(
    id: 'reading-mode',
    section: HelpSection.reading,
    title: HelpText(
      '段落排版还是逐节显示',
      '段落排版還是逐節顯示',
      'Paragraph Flow or Verse by Verse',
    ),
    body: HelpText(
      '• 段落排版（默认）：经文按段落连成一段读，像读书\n• 逐节显示：每节一行，方便对照和选取\n\n在「设置」›「阅读模式」里切换；平板和电脑上，阅读页「⋯」菜单里也能直接切换。',
      '• 段落排版（預設）：經文按段落連成一段讀，像讀書\n• 逐節顯示：每節一行，方便對照和選取\n\n在「設定」›「閱讀模式」裡切換；平板和電腦上，閱讀頁「⋯」選單裡也能直接切換。',
      '• Paragraph Flow (the default): verses run together in paragraphs, like a book\n• Verse by Verse: one verse per line, easier to compare and select\n\nSwitch in Settings › Reading Mode; on a tablet or computer the reader\'s ⋯ menu switches it too.',
    ),
    path: ['settings', 'readingMode'],
    keywords: [
      'paragraph',
      '段落',
      'verse by verse',
      '逐节',
      'layout',
      '排版',
      'mode',
      '模式',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'immersive',
    section: HelpSection.reading,
    title: HelpText(
      '全屏专心读经',
      '全屏專心讀經',
      'Reading without the toolbars',
    ),
    body: HelpText(
      '点经文旁边或段落之间的空白处，顶栏和底栏会隐藏；再点一次就回来。',
      '點經文旁邊或段落之間的空白處，頂欄和底欄會隱藏；再點一次就回來。',
      'Tap the margin or a gap between paragraphs and the top and bottom bars hide; tap again to bring them back.',
    ),
    keywords: [
      'immersive',
      '全屏',
      '沉浸',
      'fullscreen',
      'hide',
      '隐藏',
      'toolbar',
      '工具栏',
      'focus',
      '专心',
    ],
  ),
  HelpTopic(
    id: 'appearance',
    section: HelpSection.reading,
    title: HelpText(
      '字号、字体、颜色和深色模式',
      '字號、字體、顏色和深色模式',
      'Text size, font, colour and dark mode',
    ),
    body: HelpText(
      '都在「设置」里：\n\n• 显示：字号、菜单大小、行距、字体、主色调、风格预设；改动即时生效，有预览\n• 阅读：主题模式（浅色 / 深色 / 跟随系统）、护眼纸质背景、加粗经文、段落标题、书卷简介\n\n改主色调时，app 图标也会跟着变成同一个颜色。',
      '都在「設定」裡：\n\n• 顯示：字號、選單大小、行距、字體、主色調、風格預設；改動即時生效，有預覽\n• 閱讀：主題模式（淺色 / 深色 / 跟隨系統）、護眼紙質背景、加粗經文、段落標題、書卷簡介\n\n改主色調時，app 圖示也會跟著變成同一個顏色。',
      'All in Settings:\n\n• Display: text size, menu size, line spacing, font, primary colour, style preset — changes apply at once, with a preview\n• Reading: theme mode (light / dark / system), paper reading theme, bold verse text, section titles, book introductions\n\nChanging the primary colour recolours the app icon to match.',
    ),
    path: ['settings', 'settingsSectionDisplay'],
    keywords: [
      'font',
      '字体',
      'size',
      '字号',
      '字太小',
      'bigger',
      '放大',
      '缩小',
      'dark',
      '深色',
      '夜间',
      'night',
      'theme',
      '主题',
      'color',
      'colour',
      '颜色',
      '主色调',
      'icon',
      '图标',
      'line spacing',
      '行距',
      'paper',
      '护眼',
      'bold',
      '加粗',
    ],
    notes: {
      HelpPlatform.windows: HelpText(
        'Windows 和 Linux 上 app 图标不会跟着变色。',
        'Windows 和 Linux 上 app 圖示不會跟著變色。',
        'On Windows and Linux the app icon does not change colour.',
      ),
      HelpPlatform.linux: HelpText(
        'Windows 和 Linux 上 app 图标不会跟着变色。',
        'Windows 和 Linux 上 app 圖示不會跟著變色。',
        'On Windows and Linux the app icon does not change colour.',
      ),
      HelpPlatform.web: HelpText(
        '网页版改变的是浏览器标签上的小图标。',
        '網頁版改變的是瀏覽器標籤上的小圖示。',
        'On the web it is the browser tab\'s icon that changes.',
      ),
      HelpPlatform.android: HelpText(
        '换图标颜色时 app 会重新打开一次，这是 Android 的要求。',
        '換圖示顏色時 app 會重新開啟一次，這是 Android 的要求。',
        'Changing the icon colour restarts the app once — Android requires it.',
      ),
    },
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'select-verses',
    section: HelpSection.study,
    title: HelpText(
      '选中经文后能做什么',
      '選中經文後能做什麼',
      'What you can do with selected verses',
    ),
    body: HelpText(
      '点一节经文就选中它，可以接着点选多节。下面会出现一排操作（放不下的在「更多」里）：\n\n• 释经：逐字原文和词义\n• 相互参照：串珠经文\n• 注释：有注释的书卷才出现\n• 相关讲道\n• AI 解释经文\n• 笔记、书签、高亮（六种颜色）\n• 生成图片：把经文做成一张可以分享的图\n• 投影\n• 复制、分享\n\n点「清除选择」取消。',
      '點一節經文就選中它，可以接著點選多節。下面會出現一排操作（放不下的在「更多」裡）：\n\n• 釋經：逐字原文和詞義\n• 相互參照：串珠經文\n• 註釋：有註釋的書卷才出現\n• 相關講道\n• AI 解釋經文\n• 筆記、書籤、高亮（六種顏色）\n• 產生圖片：把經文做成一張可以分享的圖\n• 投影\n• 複製、分享\n\n點「清除選擇」取消。',
      'Tap a verse to select it; keep tapping to select several. A row of actions appears (what does not fit is under More):\n\n• Exegesis: word by word in the original\n• Cross-references\n• Commentary: only in books that have one\n• Related sermons\n• AI explain\n• Note, bookmark, highlight (six colours)\n• Verse image: turn the verse into a picture to share\n• Project\n• Copy, share\n\nClear selection deselects.',
    ),
    keywords: [
      'select',
      '选中',
      '选择',
      '多选',
      'multi',
      'long press',
      '操作',
      'actions',
      'copy',
      '复制',
      'share',
      '分享',
      'highlight',
      '高亮',
      'note',
      '笔记',
      'bookmark',
      '书签',
      'image',
      '图片',
      'project',
      '投影',
    ],
  ),
  HelpTopic(
    id: 'exegesis',
    section: HelpSection.study,
    title: HelpText(
      '释经：逐字看原文',
      '釋經：逐字看原文',
      'Exegesis: the original, word by word',
    ),
    body: HelpText(
      '选中经文后点「释经」：每个词列出希腊文或希伯来文原文、Strong 编号、音译和词义。\n\n点任何一个词，打开完整的词典条目：同源词、近义词、七十士译本里的对应、以及这个词在圣经里出现的所有地方。但以理书和以斯拉记里的亚兰文会单独标出。',
      '選中經文後點「釋經」：每個詞列出希臘文或希伯來文原文、Strong 編號、音譯和詞義。\n\n點任何一個詞，開啟完整的詞典條目：同源詞、近義詞、七十士譯本里的對應、以及這個詞在聖經裡出現的所有地方。但以理書和以斯拉記裡的亞蘭文會單獨標出。',
      'Select a verse and tap Exegesis: every word with its Greek or Hebrew, Strong\'s number, transliteration and meaning.\n\nTap any word for its full lexicon entry — word family, synonyms, the Septuagint\'s use of it, and everywhere it occurs. Aramaic in Daniel and Ezra is marked as such.',
    ),
    keywords: [
      'exegesis',
      '释经',
      'original',
      '原文',
      'Greek',
      'Hebrew',
      '希腊文',
      '希伯来文',
      'Strong',
      '编号',
      'interlinear',
      '逐字',
      'lexicon',
      '词典',
      'word study',
      'Aramaic',
      '亚兰文',
      'LXX',
      '七十士',
    ],
  ),
  HelpTopic(
    id: 'cross-refs',
    section: HelpSection.study,
    title: HelpText(
      '相互参照（串珠）',
      '相互參照（串珠）',
      'Cross-references',
    ),
    body: HelpText(
      '选中经文后点「相互参照」，列出相关经文，来自《圣经宝库》（TSK）和 OpenBible 的读者投票，票数高的排在前面。点一条就跳过去。',
      '選中經文後點「相互參照」，列出相關經文，來自《聖經寶庫》（TSK）和 OpenBible 的讀者投票，票數高的排在前面。點一條就跳過去。',
      'Select a verse and tap Cross-references: related passages from the Treasury of Scripture Knowledge and OpenBible\'s reader votes, the most-voted first. Tap one to go there.',
    ),
    keywords: [
      'cross references',
      '串珠',
      '参照',
      '互参',
      'related verses',
      '相关经文',
      'TSK',
      'OpenBible',
    ],
  ),
  HelpTopic(
    id: 'ai-explain',
    section: HelpSection.study,
    title: HelpText(
      'AI 解释经文',
      'AI 解釋經文',
      'AI explain',
    ),
    body: HelpText(
      '选中经文后点「AI 解释经文」。可以追问、让它说得更详细或更简短，也可以把回答存成笔记。\n\nAI 的回答只作参考，请对照经文自己核对。「设置」›「AI 释义」可以选回应深度；如果常用，也可以填入你自己的免费 Gemini 密钥，就不受共用额度限制。',
      '選中經文後點「AI 解釋經文」。可以追問、讓它說得更詳細或更簡短，也可以把回答存成筆記。\n\nAI 的回答只作參考，請對照經文自己核對。「設定」›「AI 釋義」可以選回應深度；如果常用，也可以填入你自己的免費 Gemini 金鑰，就不受共用額度限制。',
      'Select a verse and tap AI explain. Ask follow-up questions, make it longer or shorter, or save the answer as a note.\n\nAI answers are for reference — check them against the text yourself. Settings › AI sets the response depth; if you use it a lot, add your own free Gemini key so the shared quota never runs out on you.',
    ),
    path: ['settings', 'settingsSectionAi'],
    keywords: [
      'AI',
      '人工智能',
      'explain',
      '解释',
      'Gemini',
      'key',
      '密钥',
      'chat',
      '问答',
      'question',
      '提问',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'chapter-menu',
    section: HelpSection.study,
    title: HelpText(
      '这一章的相关资料',
      '這一章的相關資料',
      'Resources for this chapter',
    ),
    body: HelpText(
      '阅读页右上角「⋯」里的「本章资源」只列和当前这一章有关的内容：\n\n• 我的高亮（本章有高亮时）\n• 投影\n• 圣经实证：和本章有关的考古、历史发现\n• 福音书对观：四福音里才有\n• 插图\n• 相关讲道\n• 冷知识',
      '閱讀頁右上角「⋯」裡的「本章資源」只列和當前這一章有關的內容：\n\n• 我的高亮（本章有高亮時）\n• 投影\n• 聖經實證：和本章有關的考古、歷史發現\n• 福音書對觀：四福音裡才有\n• 插畫\n• 相關講道\n• 冷知識',
      'The reader\'s ⋯ menu has a This Chapter section listing only what bears on the chapter you are reading:\n\n• My Highlights (when the chapter has some)\n• Projection\n• Bible Evidence: archaeological and historical finds for this chapter\n• Gospel Synopsis: in the four gospels\n• Illustrations\n• Related sermons\n• Bible Trivia',
    ),
    path: ['more', 'menuSectionChapter'],
    keywords: [
      'chapter',
      '本章',
      'resources',
      '资源',
      'synopsis',
      '对观',
      '福音书',
      'gospel',
      'maps',
      '插图',
      'illustrations',
      'evidence',
      '实证',
      'trivia',
      '冷知识',
      'sermons',
      '讲道',
      'menu',
      '菜单',
      '⋯',
    ],
  ),
  HelpTopic(
    id: 'verse-image',
    section: HelpSection.study,
    title: HelpText(
      '把经文做成图片',
      '把經文做成圖片',
      'Turning a verse into a picture',
    ),
    body: HelpText(
      '选中经文后点「生成图片」：选浅色或深色，也可以放一张自己的照片做背景，做成一张清晰的图片，保存到相册或直接分享。',
      '選中經文後點「產生圖片」：選淺色或深色，也可以放一張自己的照片做背景，做成一張清晰的圖片，儲存到相簿或直接分享。',
      'Select verses and tap Verse image: light or dark, optionally one of your own photos as the background, and you get a sharp image to save to Photos or share.',
    ),
    keywords: [
      'image',
      '图片',
      'picture',
      'card',
      '经文卡',
      'share',
      '分享',
      'wallpaper',
      '壁纸',
      'photo',
      '照片',
      'save',
      '保存',
    ],
  ),
  HelpTopic(
    id: 'bible-tools',
    section: HelpSection.study,
    title: HelpText(
      '圣经工具',
      '聖經工具',
      'Bible Tools',
    ),
    body: HelpText(
      '主页「更多探索」›「圣经工具」：总览（整本圣经的统计）、查询（原文词查询）、分布（一个词在各卷出现多少次）。',
      '主頁「更多探索」›「聖經工具」：總覽（整本聖經的統計）、查詢（原文詞查詢）、分佈（一個詞在各卷出現多少次）。',
      'Home › Explore more › Bible Tools: Overview (statistics for the whole Bible), Lookup (original-language words) and Distribution (how often a word occurs, book by book).',
    ),
    path: ['quickLinksExplore', 'statistics'],
    keywords: [
      'tools',
      '工具',
      'statistics',
      '统计',
      'distribution',
      '分布',
      'lookup',
      '查询',
      'Strong',
      'word count',
      '词频',
    ],
    open: HelpDestination.statistics,
  ),
  HelpTopic(
    id: 'search',
    section: HelpSection.search,
    title: HelpText(
      '搜索经文',
      '搜尋經文',
      'Searching the Bible',
    ),
    body: HelpText(
      '主页快捷入口的「搜索」，或阅读页顶上的放大镜。边打边出结果，点一条结果就跳到那节并标出来。\n\n• 打经文位置直接跳：约 3:16、John 3:16、Rom 12:1-2\n• 可以选「搜索整本圣经」或「搜索当前书卷」\n• 最近搜过的会列在上面，点一下再搜，点 × 删掉\n• 「复制全部」一次复制所有结果\n• 搜索框旁的 ? 有更完整的写法说明\n\n搜索用的是你正在读的译本。',
      '主頁快捷入口的「搜尋」，或閱讀頁頂上的放大鏡。邊打邊出結果，點一條結果就跳到那節並標出來。\n\n• 打經文位置直接跳：約 3:16、John 3:16、Rom 12:1-2\n• 可以選「搜尋整本聖經」或「搜尋當前書卷」\n• 最近搜過的會列在上面，點一下再搜，點 × 刪掉\n• 「複製全部」一次複製所有結果\n• 搜尋框旁的 ? 有更完整的寫法說明\n\n搜尋用的是你正在讀的譯本。',
      'Search in Quick links on the home page, or the magnifier at the top of the reader. Results appear as you type; tap one to go to the verse, marked.\n\n• Type a reference to jump: John 3:16, 约 3:16, Rom 12:1-2\n• Choose Search Entire Bible or Search Current Book\n• Recent searches are listed on top — tap to repeat, × to delete\n• Copy all copies every result at once\n• The ? beside the box explains every way to search\n\nSearch uses the version you are reading.',
    ),
    path: ['quickLinksFrequent', 'search'],
    keywords: [
      'search',
      '搜索',
      '查找',
      'find',
      '查经',
      'keyword',
      '关键字',
      'reference',
      '经文位置',
      'recent',
      '最近',
      'copy all',
      '复制全部',
      '/',
    ],
    open: HelpDestination.search,
  ),
  HelpTopic(
    id: 'advanced-search',
    section: HelpSection.search,
    title: HelpText(
      '按原文、编号或主题搜索',
      '按原文、編號或主題搜尋',
      'Searching by original word, number or theme',
    ),
    body: HelpText(
      '• 打 Strong 编号（G2316、H7200）打开词典和经文索引；输入编号后会出现 AND、OR、✶ 按钮，可以组合几个编号\n• 直接打希腊文（ἀγάπη）或希伯来文（אהבה）\n• 打音译（agape、shalom、logos）：完全符合就打开词典，部分符合会问「您是否在找…」\n• 关键字找不到时，可以点「用 AI 智能搜索」，按主题或模糊的说法找（结果仅供参考）',
      '• 打 Strong 編號（G2316、H7200）開啟詞典和經文索引；輸入編號後會出現 AND、OR、✶ 按鈕，可以組合幾個編號\n• 直接打希臘文（ἀγάπη）或希伯來文（אהבה）\n• 打音譯（agape、shalom、logos）：完全符合就開啟詞典，部分符合會問「您是否在找…」\n• 關鍵字找不到時，可以點「用 AI 智慧搜尋」，按主題或模糊的說法找（結果僅供參考）',
      '• Type a Strong\'s number (G2316, H7200) for the lexicon and every occurrence; AND, OR and ✶ buttons then appear to combine numbers\n• Type the Greek (ἀγάπη) or Hebrew (אהבה) directly\n• Type a transliteration (agape, shalom, logos): an exact match opens the lexicon, a partial one asks "Did you mean…"\n• When keywords find nothing, AI search looks by theme or loose wording (for reference only)',
    ),
    path: ['quickLinksFrequent', 'search'],
    keywords: [
      'Strong',
      '编号',
      'G',
      'H',
      'Greek',
      'Hebrew',
      '希腊',
      '希伯来',
      'transliteration',
      '音译',
      'AND',
      'OR',
      'AI search',
      'AI 搜索',
      '主题',
      'theme',
      'topic',
      '模糊',
      'lemma',
      '原文',
    ],
    open: HelpDestination.search,
  ),
  HelpTopic(
    id: 'library',
    section: HelpSection.personal,
    title: HelpText(
      '笔记、书签和高亮在哪里',
      '筆記、書籤和高亮在哪裡',
      'Where your notes, bookmarks and highlights are',
    ),
    body: HelpText(
      '• 「我的收藏」（主页快捷入口，或阅读页「⋯」›「更多」）：笔记和书签两个分页，按圣经顺序排列，点一条跳回原处\n• 「我的高亮」：按颜色筛选，也可以搜索；长按一条可以复制、分享或删除\n• 主页显示它们的数量和最近收藏\n\n笔记和书签在经文旁边会显示小标记，一眼能看到。',
      '• 「我的收藏」（主頁快捷入口，或閱讀頁「⋯」›「更多」）：筆記和書籤兩個分頁，按聖經順序排列，點一條跳回原處\n• 「我的高亮」：按顏色篩選，也可以搜尋；長按一條可以複製、分享或刪除\n• 主頁顯示它們的數量和最近收藏\n\n筆記和書籤在經文旁邊會顯示小標記，一眼能看到。',
      '• Library (Quick links on the home page, or ⋯ › More in the reader): Notes and Bookmarks tabs, in scripture order — tap one to go back to it\n• My Highlights: filter by colour or search; long-press one to copy, share or remove it\n• The home page shows their counts and your recent bookmarks\n\nNotes and bookmarks are marked beside their verses so you can see them as you read.',
    ),
    path: ['quickLinksFrequent', 'library'],
    keywords: [
      'notes',
      '笔记',
      'bookmarks',
      '书签',
      '收藏',
      'highlights',
      '高亮',
      '划线',
      'library',
      'favourites',
      'saved',
      '保存',
      'annotation',
    ],
    open: HelpDestination.library,
  ),
  HelpTopic(
    id: 'sync',
    section: HelpSection.personal,
    title: HelpText(
      '登录后在多台设备间同步',
      '登入後在多臺裝置間同步',
      'Syncing across devices',
    ),
    body: HelpText(
      '不登录也完全可以用，所有内容都存在这台设备上。\n\n想在手机、平板、电脑之间同步高亮、笔记和书签：「设置」›「账号」，用邮箱登录（或用 Google 登录）。登录后自动同步；在主页往下拉一下，会立刻同步一次。',
      '不登入也完全可以用，所有內容都存在這臺裝置上。\n\n想在手機、平板、電腦之間同步高亮、筆記和書籤：「設定」›「賬號」，用郵箱登入（或用 Google 登入）。登入後自動同步；在主頁往下拉一下，會立刻同步一次。',
      'Everything works without signing in; your data stays on this device.\n\nTo sync highlights, notes and bookmarks between phone, tablet and computer: Settings › Account, sign in with email (or Google). It syncs automatically; pull down on the home page to sync right away.',
    ),
    path: ['settings', 'settingsSectionAccount'],
    keywords: [
      'sync',
      '同步',
      'sign in',
      'login',
      '登录',
      '账号',
      'account',
      'email',
      '邮箱',
      'Google',
      'cloud',
      '云',
      'backup',
      '备份',
      'devices',
      '多台设备',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'profiles',
    section: HelpSection.personal,
    title: HelpText(
      '一台设备几个人用',
      '一臺裝置幾個人用',
      'Several people on one device',
    ),
    body: HelpText(
      '「设置」›「账号」可以管理本机账号：新增、切换、改名、删除。每个人的高亮、笔记和书签分开保存；主页上的头像也能切换。',
      '「設定」›「賬號」可以管理本機賬號：新增、切換、改名、刪除。每個人的高亮、筆記和書籤分開儲存；主頁上的頭像也能切換。',
      'Settings › Account manages the profiles on this device: add, switch, rename, delete. Each person\'s highlights, notes and bookmarks are kept apart; the avatar on the home page switches too.',
    ),
    path: ['settings', 'settingsSectionAccount'],
    keywords: [
      'profile',
      '账号',
      '用户',
      'user',
      'family',
      '家人',
      'switch',
      '切换',
      'avatar',
      '头像',
      'multiple',
      '多人',
    ],
    open: HelpDestination.profiles,
  ),
  HelpTopic(
    id: 'export',
    section: HelpSection.personal,
    title: HelpText(
      '导出和导入你的数据',
      '匯出和匯入你的資料',
      'Exporting and importing your data',
    ),
    body: HelpText(
      '「设置」最下面的「导出我的数据」：Markdown 可以直接贴进备忘录、Notion、Obsidian；JSON 是完整备份。到新设备上用「导入」读回来。',
      '「設定」最下面的「匯出我的資料」：Markdown 可以直接貼進備忘錄、Notion、Obsidian；JSON 是完整備份。到新裝置上用「匯入」讀回來。',
      'Export my data at the bottom of Settings: Markdown pastes into Notes, Notion or Obsidian; JSON is a complete backup. Import reads it back on a new device.',
    ),
    path: ['settings', 'settingsSectionAbout'],
    keywords: [
      'export',
      '导出',
      'import',
      '导入',
      'backup',
      '备份',
      'markdown',
      'json',
      'transfer',
      '迁移',
      '换手机',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'copy-format',
    section: HelpSection.personal,
    title: HelpText(
      '复制出来是什么格式',
      '複製出來是什麼格式',
      'What copying produces',
    ),
    body: HelpText(
      '「设置」›「复制格式」三选一：\n\n• 灵修格式（默认）：几节连成一段，出处放在最后的括号里，适合灵修和抄经\n• 包含经文参考：每节带出处\n• 纯文字\n\n「复制时去掉括号里的译注」打开后，复制出来的经文不含译者的括号注释。',
      '「設定」›「複製格式」三選一：\n\n• 靈修格式（預設）：幾節連成一段，出處放在最後的括號裡，適合靈修和抄經\n• 包含經文參考：每節帶出處\n• 純文字\n\n「複製時去掉括號裡的譯註」開啟後，複製出來的經文不含譯者的括號註釋。',
      'Settings › Copy Format, one of three:\n\n• Devotional Format (the default): the verses run as one paragraph with the reference at the end — good for devotions and copying out\n• Include Reference: each verse with its reference\n• Plain Text\n\nTurn on Leave out translators\' notes to copy the text without the bracketed notes.',
    ),
    path: ['settings', 'copyFormat'],
    keywords: [
      'copy',
      '复制',
      'format',
      '格式',
      'devotional',
      '灵修',
      'reference',
      '出处',
      'plain',
      '纯文字',
      '抄经',
      'notes',
      '译注',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'sermons',
    section: HelpSection.media,
    title: HelpText(
      '讲道',
      '講道',
      'Sermons',
    ),
    body: HelpText(
      '张恩年牧师的讲道，按主题分类。每篇可以切换英文、简体、繁体；有录音的可以直接播放，主页的「继续讲道」从上次停下的地方接着听。\n\n想知道某节经文在哪些讲道里讲过：选中经文，点「相关讲道」。',
      '張恩年牧師的講道，按主題分類。每篇可以切換英文、簡體、繁體；有錄音的可以直接播放，主頁的「繼續講道」從上次停下的地方接著聽。\n\n想知道某節經文在哪些講道里講過：選中經文，點「相關講道」。',
      'Pastor Eric Chang\'s sermons, grouped by topic. Each one switches between English, simplified and traditional Chinese; where there is a recording it plays in the app, and Resume sermon on the home page picks up where you stopped.\n\nTo find sermons on a verse, select it and tap Related sermons.',
    ),
    path: ['quickLinksFrequent', 'sermons'],
    keywords: [
      'sermon',
      '讲道',
      '讲章',
      'preaching',
      'audio',
      '录音',
      '音频',
      'listen',
      '听',
      '张恩年',
      'Eric Chang',
      'resume',
      '继续',
    ],
    open: HelpDestination.sermons,
  ),
  HelpTopic(
    id: 'songs',
    section: HelpSection.media,
    title: HelpText(
      '诗歌',
      '詩歌',
      'Songs',
    ),
    body: HelpText(
      '教会诗歌：在线听、看乐谱、看影片，也能离线下载。\n\n• 歌单：收藏、精选歌单、存下来的筛选\n• 离线下载：看占用多少空间，不要的删掉\n• 全屏播放器字大、按钮大，开车时也好用；离开诗歌页后，底部的小播放条继续播放\n\n主页「精选推荐」里的「诗歌」直接进入。',
      '教會詩歌：線上聽、看樂譜、看影片，也能離線下載。\n\n• 歌單：收藏、精選歌單、存下來的篩選\n• 離線下載：看佔用多少空間，不要的刪掉\n• 全屏播放器字大、按鈕大，開車時也好用；離開詩歌頁後，底部的小播放條繼續播放\n\n主頁「精選推薦」裡的「詩歌」直接進入。',
      'Church songs: listen online, read the sheet music, watch the video, or download for offline.\n\n• Playlists: favourites, curated lists and saved filters\n• Downloads: see how much space they use and remove what you no longer need\n• The full-screen player has large type and large buttons, fine for the car; leave the Songs page and the mini player at the bottom keeps playing\n\nSongs under Featured on the home page goes straight there.',
    ),
    keywords: [
      'songs',
      '诗歌',
      '赞美诗',
      'hymn',
      'music',
      '音乐',
      'sheet music',
      '乐谱',
      'score',
      'PDF',
      'video',
      '影片',
      'download',
      '下载',
      'offline',
      '离线',
      'playlist',
      '歌单',
      'player',
      '播放',
    ],
    open: HelpDestination.songs,
  ),
  HelpTopic(
    id: 'videos',
    section: HelpSection.media,
    title: HelpText(
      '影片系列',
      '影片系列',
      'Featured videos',
    ),
    body: HelpText(
      '精选影片，按系列排列，在 app 里直接播放。',
      '精選影片，按系列排列，在 app 裡直接播放。',
      'Selected videos, arranged in series and played inside the app.',
    ),
    keywords: [
      'video',
      '影片',
      '视频',
      'youtube',
      'watch',
      '看',
    ],
    open: HelpDestination.videos,
  ),
  HelpTopic(
    id: 'projection',
    section: HelpSection.media,
    title: HelpText(
      '投影',
      '投影',
      'Projection',
    ),
    body: HelpText(
      '把经文投到聚会的大屏幕上。选中经文后点「投影」，或阅读页「⋯」›「本章资源」›「投影」。\n\n• 方向键、空格或翻页笔：上一节、下一节；PgUp / PgDn：上一章、下一章\n• B 黑屏，+ / − 调字号，P 加上或去掉第二个译本\n• G 换一种深色背景，V 选第二个译本，S 调出存好的设置\n• A 打开聚会流程，[ ] 走上一项、下一项；C 倒计时\n• D 在第二个屏幕上打开投影窗口\n• Esc 离开\n\n投影只用深色背景，字号和你平时读经的字号分开设定。',
      '把經文投到聚會的大螢幕上。選中經文後點「投影」，或閱讀頁「⋯」›「本章資源」›「投影」。\n\n• 方向鍵、空格或翻頁筆：上一節、下一節；PgUp / PgDn：上一章、下一章\n• B 黑屏，+ / − 調字號，P 加上或去掉第二個譯本\n• G 換一種深色背景，V 選第二個譯本，S 調出存好的設定\n• A 開啟聚會流程，[ ] 走上一項、下一項；C 倒計時\n• D 在第二個螢幕上開啟投影視窗\n• Esc 離開\n\n投影只用深色背景，字號和你平時讀經的字號分開設定。',
      'Puts scripture on the screen at the front of a meeting. Select verses and choose Project, or ⋯ › This Chapter › Projection in the reader.\n\n• Arrows, Space or a presentation clicker: previous and next verse; PgUp / PgDn: previous and next chapter\n• B blanks, + / − resize, P adds or drops a second version\n• G steps to the next dark background, V picks the second version, S recalls a saved setup\n• A opens the order of service and [ ] step through it; C is a countdown\n• D opens the projection window on a second screen\n• Esc leaves\n\nProjection always uses a dark background, and its type size is separate from your reading size.',
    ),
    keywords: [
      'projection',
      '投影',
      '投屏',
      'projector',
      '大屏幕',
      'screen',
      'church',
      '聚会',
      '教会',
      'service',
      '主日',
      'blank',
      '黑屏',
      'clicker',
      '翻页笔',
      'countdown',
      '倒计时',
      'agenda',
      '流程',
      'second screen',
      '第二屏幕',
      'presentation',
    ],
    notes: {
      HelpPlatform.web: HelpText(
        '按 D 会开一个新的浏览器窗口，把它拖到投影仪那个屏幕上并设为全屏；原来的窗口留在你面前操作。',
        '按 D 會開一個新的瀏覽器視窗，把它拖到投影儀那個螢幕上並設為全屏；原來的視窗留在你面前操作。',
        'D opens a new browser window: drag it to the projector\'s screen and make it full screen, and keep driving from the original.',
      ),
      HelpPlatform.macos: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.windows: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.linux: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.ios: HelpText(
        'iPhone 和 iPad 没有第二个投影窗口（D 不起作用）：用系统的屏幕镜像把整个画面投出去，用手指点屏幕上的按钮操作；接上键盘时上面的按键也能用。',
        'iPhone 和 iPad 沒有第二個投影視窗（D 不起作用）：用系統的螢幕鏡像把整個畫面投出去，用手指點螢幕上的按鈕操作；接上鍵盤時上面的按鍵也能用。',
        'iPhone and iPad have no second projection window (D does nothing): mirror the whole screen with the system\'s screen mirroring and use the on-screen buttons; with a keyboard attached the keys above work too.',
      ),
      HelpPlatform.android: HelpText(
        'Android 没有第二个投影窗口（D 不起作用）：用系统的投屏把整个画面投出去，用手指点屏幕上的按钮操作。',
        'Android 沒有第二個投影視窗（D 不起作用）：用系統的投屏把整個畫面投出去，用手指點螢幕上的按鈕操作。',
        'Android has no second projection window (D does nothing): cast the whole screen with the system\'s screen casting and use the on-screen buttons.',
      ),
    },
    open: HelpDestination.projection,
  ),
  HelpTopic(
    id: 'evidence',
    section: HelpSection.explore,
    title: HelpText(
      '圣经实证',
      '聖經實證',
      'Bible Evidence',
    ),
    body: HelpText(
      '考古、手抄本、历史和科学方面的发现，每条都连到相关经文。可以浏览、搜索，也可以用 AI 按问题查找。\n\n主页的「今日证据」每天换一条；读某一章时，「⋯」›「本章资源」›「圣经实证」只列和这章有关的。',
      '考古、手抄本、歷史和科學方面的發現，每條都連到相關經文。可以瀏覽、搜尋，也可以用 AI 按問題查詢。\n\n主頁的「今日證據」每天換一條；讀某一章時，「⋯」›「本章資源」›「聖經實證」只列和這章有關的。',
      'Archaeological, manuscript, historical and scientific finds, each linked to its scripture. Browse, search, or ask the AI a question.\n\nToday\'s Evidence on the home page changes daily; while reading, ⋯ › This Chapter › Bible Evidence lists only the finds for that chapter.',
    ),
    path: ['quickLinksExplore', 'bibleEvidence'],
    keywords: [
      'evidence',
      '实证',
      '证据',
      'archaeology',
      '考古',
      'manuscript',
      '手抄本',
      'history',
      '历史',
      'science',
      '科学',
    ],
    open: HelpDestination.evidence,
  ),
  HelpTopic(
    id: 'family-tree',
    section: HelpSection.explore,
    title: HelpText(
      '圣经家谱',
      '聖經家譜',
      'Family Tree',
    ),
    body: HelpText(
      '圣经人物的家谱。点一个人看他的经文和亲属。',
      '聖經人物的家譜。點一個人看他的經文和親屬。',
      'The family tree of biblical people. Tap a person for their passages and relations.',
    ),
    path: ['quickLinksExplore', 'familyTree'],
    keywords: [
      'family',
      '家谱',
      'genealogy',
      '族谱',
      'people',
      '人物',
      'person',
    ],
    open: HelpDestination.familyTree,
  ),
  HelpTopic(
    id: 'timeline',
    section: HelpSection.explore,
    title: HelpText(
      '圣经时间轴和年代对照图',
      '聖經時間軸和年代對照圖',
      'Bible Timeline and the chronology chart',
    ),
    body: HelpText(
      '• 圣经时间轴：圣经事件按年代排列\n• 年代对照图（主页「精选推荐」）：从创造到启示录画在同一条刻度上，看谁和谁同时在世，其他大事又在什么时候',
      '• 聖經時間軸：聖經事件按年代排列\n• 年代對照圖（主頁「精選推薦」）：從創造到啟示錄畫在同一條刻度上，看誰和誰同時在世，其他大事又在什麼時候',
      '• Bible Timeline: biblical events in order\n• The chronology chart (Featured on the home page): Creation to Revelation on one axis — who was alive at the same time, and when everything else happened',
    ),
    path: ['quickLinksExplore', 'bibleTimeline'],
    keywords: [
      'timeline',
      '时间轴',
      '时间线',
      'chronology',
      '年代',
      '对照图',
      'chart',
      'history',
      '历史',
      'dates',
      '年份',
    ],
    open: HelpDestination.timeline,
  ),
  HelpTopic(
    id: 'trivia',
    section: HelpSection.explore,
    title: HelpText(
      '冷知识',
      '冷知識',
      'Bible Trivia',
    ),
    body: HelpText(
      '圣经里不容易注意到的规律：离合诗、数字结构、神名的排列等等，按圣经顺序排列，有些配了示意图。',
      '聖經裡不容易注意到的規律：離合詩、數字結構、神名的排列等等，按聖經順序排列，有些配了示意圖。',
      'Patterns that are easy to miss — acrostics, numerical structures, the arrangement of divine names — in canonical order, some with diagrams.',
    ),
    path: ['quickLinksExplore', 'bibleTrivia'],
    keywords: [
      'trivia',
      '冷知识',
      '知识',
      'acrostic',
      '离合诗',
      'pattern',
      '规律',
      'numbers',
      '数字',
    ],
    open: HelpDestination.trivia,
  ),
  HelpTopic(
    id: 'misconceptions',
    section: HelpSection.explore,
    title: HelpText(
      '常见误解',
      '常見誤解',
      'Common misunderstandings',
    ),
    body: HelpText(
      '大家常说、但经文其实不是这样说的事，每条都附上经文。学者确实有分歧的地方会直接说明，不替你选边。',
      '大家常說、但經文其實不是這樣說的事，每條都附上經文。學者確實有分歧的地方會直接說明，不替你選邊。',
      'Things people often repeat that the text does not actually say, each with its passages. Where scholars genuinely disagree, the card says so rather than picking a side.',
    ),
    path: ['quickLinksExplore', 'misconceptionsTile'],
    keywords: [
      'misconception',
      '误解',
      '误区',
      'myth',
      '谣言',
      'common',
      '常见',
    ],
    open: HelpDestination.misconceptions,
  ),
  HelpTopic(
    id: 'reading-stats',
    section: HelpSection.explore,
    title: HelpText(
      '阅读统计',
      '閱讀統計',
      'Reading statistics',
    ),
    body: HelpText(
      '你读过哪些书卷和章节、读了多少，一目了然。',
      '你讀過哪些書卷和章節、讀了多少，一目瞭然。',
      'Which books and chapters you have read, and how much.',
    ),
    path: ['quickLinksExplore', 'readingStats'],
    keywords: [
      'reading',
      '阅读',
      'statistics',
      '统计',
      'progress',
      '进度',
      'history',
      '记录',
    ],
    open: HelpDestination.readingStats,
  ),
  HelpTopic(
    id: 'feedback',
    section: HelpSection.explore,
    title: HelpText(
      '意见反馈',
      '意見回饋',
      'Feedback',
    ),
    body: HelpText(
      '发现问题或有建议，在「意见反馈」里写下来直接寄给开发者，不用离开 app。会自动附上版本、设备等资料，方便查问题。',
      '發現問題或有建議，在「意見回饋」裡寫下來直接寄給開發者，不用離開 app。會自動附上版本、裝置等資料，方便查問題。',
      'Found a problem or have an idea? Write it in Feedback and it goes straight to the developer without leaving the app, with the version and device attached to help track it down.',
    ),
    path: ['quickLinksExplore', 'feedback'],
    keywords: [
      'feedback',
      '反馈',
      '意见',
      'bug',
      '问题',
      'report',
      '报告',
      'contact',
      '联系',
      'suggestion',
      '建议',
    ],
    open: HelpDestination.feedback,
  ),
  HelpTopic(
    id: 'settings',
    section: HelpSection.settings,
    title: HelpText(
      '设置里有什么',
      '設定裡有什麼',
      'What\'s in Settings',
    ),
    body: HelpText(
      '主页快捷入口的「设置」，或阅读页「⋯」›「设置」。\n\n• 账号：登录同步、管理本机账号\n• 显示：字号、菜单大小、行距、复制格式、字体、主色调、风格预设\n• 阅读：主题模式、阅读模式、护眼纸质背景、加粗经文、段落标题、书卷简介、词卡上的编号\n• 应用：界面语言、检查更新\n• 主页布局：主页显示哪些区块\n• 通知：每日提醒\n• AI 释义：回应深度、自己的 Gemini 密钥\n• 关于：版权说明、安装、导出导入、离线包、清除缓存、重新查看导览、恢复设置',
      '主頁快捷入口的「設定」，或閱讀頁「⋯」›「設定」。\n\n• 賬號：登入同步、管理本機賬號\n• 顯示：字號、選單大小、行距、複製格式、字體、主色調、風格預設\n• 閱讀：主題模式、閱讀模式、護眼紙質背景、加粗經文、段落標題、書卷簡介、詞卡上的編號\n• 應用：介面語言、檢查更新\n• 主頁佈局：主頁顯示哪些區塊\n• 通知：每日提醒\n• AI 釋義：回應深度、自己的 Gemini 金鑰\n• 關於：版權說明、安裝、匯出匯入、離線包、清除快取、重新查看導覽、恢復設定',
      'Settings in Quick links, or ⋯ › Settings in the reader.\n\n• Account: sign in to sync, manage profiles\n• Display: text size, menu size, line spacing, copy format, font, primary colour, style preset\n• Reading: theme mode, reading mode, paper theme, bold text, section titles, book introductions, numbers on word chips\n• App: interface language, update checks\n• Home layout: which sections the home page shows\n• Notifications: daily reminders\n• AI: response depth, your own Gemini key\n• About: attributions, install, export and import, offline pack, clear cache, tour, reset',
    ),
    path: ['quickLinksFrequent', 'settings'],
    keywords: [
      'settings',
      '设置',
      'preferences',
      '偏好',
      'options',
      '选项',
      'config',
      '配置',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'language',
    section: HelpSection.settings,
    title: HelpText(
      '切换界面语言',
      '切換介面語言',
      'Changing the interface language',
    ),
    body: HelpText(
      '简体中文、繁體中文、English 三种：「设置」›「界面语言」，或各页右上角的语言按钮，或阅读页「⋯」›「界面语言」。切换界面语言不会换经文译本。',
      '簡體中文、繁體中文、English 三種：「設定」›「介面語言」，或各頁右上角的語言按鈕，或閱讀頁「⋯」›「介面語言」。切換介面語言不會換經文譯本。',
      'Simplified Chinese, Traditional Chinese or English: Settings › Interface Language, the language button at the top right of each page, or ⋯ › Interface Language in the reader. It does not change the Bible version.',
    ),
    path: ['settings', 'interfaceLanguage'],
    keywords: [
      'language',
      '语言',
      '中文',
      '英文',
      'English',
      'Chinese',
      '简体',
      '繁体',
      'traditional',
      'simplified',
      'interface',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'dashboard-layout',
    section: HelpSection.settings,
    title: HelpText(
      '主页显示哪些内容',
      '主頁顯示哪些內容',
      'Choosing what the home page shows',
    ),
    body: HelpText(
      '「设置」›「主页布局」：打开或关掉每个区块（读经、继续讲道、每日金句、收藏数量、最近收藏、今日证据、快捷入口、精选推荐），也能恢复默认。',
      '「設定」›「主頁佈局」：開啟或關掉每個區塊（讀經、繼續講道、每日金句、收藏數量、最近收藏、今日證據、快捷入口、精選推薦），也能恢復預設。',
      'Settings › Home layout: switch each section on or off (Read Bible, Resume sermon, Verse of the Day, counts, recent bookmarks, Today\'s Evidence, Quick links, Featured), or reset to the default.',
    ),
    path: ['settings', 'settingsSectionDashboard'],
    keywords: [
      'home',
      '主页',
      'dashboard',
      'layout',
      '布局',
      'sections',
      '区块',
      'hide',
      '隐藏',
      'customize',
      '自定义',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'notifications',
    section: HelpSection.settings,
    title: HelpText(
      '每日提醒',
      '每日提醒',
      'Daily reminders',
    ),
    body: HelpText(
      '「设置」›「通知」开启后，每天会有一条轻量的提醒。第一次开启时系统会问你是否允许；可以先发一条测试看看能不能收到。',
      '「設定」›「通知」開啟後，每天會有一條輕量的提醒。第一次開啟時系統會問你是否允許；可以先發一條測試看看能不能收到。',
      'Turn on Settings › Notifications for a gentle daily reminder. The system asks for permission the first time; send a test one to check it arrives.',
    ),
    path: ['settings', 'settingsSectionNotifications'],
    keywords: [
      'notification',
      '通知',
      '提醒',
      'reminder',
      'daily',
      '每日',
      'push',
      '推送',
      'alert',
    ],
    notes: {
      HelpPlatform.web: HelpText(
        '在浏览器里，提醒会在你下次打开 app 时送达，而不是在设定的那一刻——网页没办法自己醒来，装到主屏幕也一样。想准时收到，请用下载安装的 app。',
        '在瀏覽器裡，提醒會在你下次開啟 app 時送達，而不是在設定的那一刻——網頁沒辦法自己醒來，裝到主螢幕也一樣。想準時收到，請用下載安裝的 app。',
        'In a browser, reminders arrive the next time you open the app rather than at the set moment — a web page cannot wake itself, even installed to a home screen. For them on time, use the downloaded app.',
      ),
    },
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'updates',
    section: HelpSection.settings,
    title: HelpText(
      '更新到新版本',
      '更新到新版本',
      'Getting the new version',
    ),
    body: HelpText(
      '有新版本时，主页最上面会出现一条提示。在主页往下拉一下，会立刻检查一次（登录了的话也顺便同步）；「设置」›「应用」里也能手动检查、调整自动检查。',
      '有新版本時，主頁最上面會出現一條提示。在主頁往下拉一下，會立刻檢查一次（登入了的話也順便同步）；「設定」›「應用」裡也能手動檢查、調整自動檢查。',
      'When a newer version exists, a banner appears at the top of the home page. Pull down on the home page to check right away (and to sync, if you are signed in); Settings › App also checks by hand and sets the automatic check.',
    ),
    path: ['settings', 'settingsSectionApp'],
    keywords: [
      'update',
      '更新',
      'upgrade',
      '升级',
      'new version',
      '新版本',
      'download',
      '下载',
      'install',
      '安装',
      'pull',
      '下拉',
      'refresh',
      '刷新',
    ],
    notes: {
      HelpPlatform.web: HelpText(
        '网页版每次打开都是最新版；往下拉会检查这个页面是不是旧的。如果看起来还是旧版，用「设置」›「清除缓存并重新加载」。',
        '網頁版每次開啟都是最新版；往下拉會檢查這個頁面是不是舊的。如果看起來還是舊版，用「設定」›「清除快取並重新載入」。',
        'The web version is the latest each time it opens; pulling down checks whether this tab is behind. If it still looks old, use Settings › Clear cache & reload.',
      ),
      HelpPlatform.android: HelpText(
        'Android 上可以在 app 里直接下载并安装新版本（第一次需要允许「安装未知应用」）。',
        'Android 上可以在 app 裡直接下載並安裝新版本（第一次需要允許「安裝未知應用」）。',
        'On Android the update downloads and installs inside the app (the first time, allow "install unknown apps").',
      ),
      HelpPlatform.macos: HelpText(
        '会打开下载页：下载新的 macOS 压缩包，解压后替换「应用程序」里原来的 Yahwehs-Words.app。你的数据不会丢失。',
        '會開啟下載頁：下載新的 macOS 壓縮包，解壓後替換「應用程式」裡原來的 Yahwehs-Words.app。你的資料不會丟失。',
        'Opens the download page: download the new macOS zip, unzip it and replace Yahwehs-Words.app in Applications. Your data is kept.',
      ),
      HelpPlatform.windows: HelpText(
        '会打开下载页：下载新的 Windows 压缩包，解压后覆盖原来的 Yahwehs-Words 文件夹。你的数据不会丢失。',
        '會開啟下載頁：下載新的 Windows 壓縮包，解壓後覆蓋原來的 Yahwehs-Words 資料夾。你的資料不會丟失。',
        'Opens the download page: download the new Windows zip and unzip it over the old Yahwehs-Words folder. Your data is kept.',
      ),
      HelpPlatform.linux: HelpText(
        '会打开下载页：下载新的 Linux 压缩包，解压后替换原来的文件夹。',
        '會開啟下載頁：下載新的 Linux 壓縮包，解壓後替換原來的資料夾。',
        'Opens the download page: download the new Linux archive and unpack it over the old folder.',
      ),
      HelpPlatform.ios: HelpText(
        'iPhone / iPad 版由开发者安装，检查更新会告诉你是否有新版本。',
        'iPhone / iPad 版由開發者安裝，檢查更新會告訴你是否有新版本。',
        'The iPhone / iPad build is installed by the developer; checking tells you whether a newer one exists.',
      ),
    },
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'offline',
    section: HelpSection.settings,
    title: HelpText(
      '离线使用',
      '離線使用',
      'Using it offline',
    ),
    body: HelpText(
      '「设置」›「离线包」：勾选要下载的类别（圣经、讲道、工具、原文、地图），下载一次之后，没有网络也能读经、查原文、看讲道。AI 和登录同步仍需要网络。',
      '「設定」›「離線包」：勾選要下載的類別（聖經、講道、工具、原文、地圖），下載一次之後，沒有網路也能讀經、查原文、看講道。AI 和登入同步仍需要網路。',
      'Settings › Offline pack: tick the categories to download (Bibles, sermons, tools, originals, maps); after one download you can read, study and read sermons with no connection. AI and sign-in sync still need one.',
    ),
    path: ['settings', 'offlinePackTitle'],
    keywords: [
      'offline',
      '离线',
      '没网',
      'no internet',
      'network',
      '网络',
      'download',
      '下载',
      'cache',
      '缓存',
      'airplane',
      '飞机',
    ],
    only: {HelpPlatform.web},
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'install',
    section: HelpSection.settings,
    title: HelpText(
      '把网页版装到手机或电脑上',
      '把網頁版裝到手機或電腦上',
      'Installing the web version',
    ),
    body: HelpText(
      '网页版可以像 app 一样装到主屏幕或桌面，打开时没有浏览器地址栏。\n\n• iPhone / iPad 的 Safari：点「分享」›「添加到主屏幕」\n• Android 的 Chrome：菜单 ›「安装应用」\n• 电脑上的 Chrome、Edge：「设置」里会出现「安装」按钮，或点地址栏右边的安装图标',
      '網頁版可以像 app 一樣裝到主螢幕或桌面，開啟時沒有瀏覽器網址列。\n\n• iPhone / iPad 的 Safari：點「分享」›「加入主畫面」\n• Android 的 Chrome：選單 ›「安裝應用」\n• 電腦上的 Chrome、Edge：「設定」裡會出現「安裝」按鈕，或點網址列右邊的安裝圖示',
      'The web version installs like an app on a home screen or desktop, with no address bar.\n\n• Safari on iPhone / iPad: Share › Add to Home Screen\n• Chrome on Android: menu › Install app\n• Chrome or Edge on a computer: an Install button appears in Settings, or use the install icon at the right of the address bar',
    ),
    path: ['settings', 'settingsSectionAbout'],
    keywords: [
      'install',
      '安装',
      'PWA',
      'home screen',
      '主屏幕',
      '桌面',
      'desktop',
      'app',
      '添加到主屏幕',
      'add to home screen',
    ],
    only: {HelpPlatform.web},
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'reset',
    section: HelpSection.settings,
    title: HelpText(
      '出问题时：重新加载、清除缓存、恢复设置',
      '出問題時：重新載入、清除快取、恢復設定',
      'When something is wrong: reload, clear cache, reset',
    ),
    body: HelpText(
      '• 经文没显示或加载失败：阅读页「⋯」›「重新加载」\n• 内容看起来不对或像是旧版：「设置」›「清除缓存并重新加载」，你的笔记和高亮不受影响\n• 外观和阅读选项改回默认：「设置」›「恢复设置」\n\n仍然不行，请用「意见反馈」告诉我们。',
      '• 經文沒顯示或載入失敗：閱讀頁「⋯」›「重新載入」\n• 內容看起來不對或像是舊版：「設定」›「清除快取並重新載入」，你的筆記和高亮不受影響\n• 外觀和閱讀選項改回預設：「設定」›「恢復設定」\n\n仍然不行，請用「意見回饋」告訴我們。',
      '• The text did not load: ⋯ › Reload in the reader\n• Something looks wrong or out of date: Settings › Clear cache & reload — your notes and highlights are untouched\n• Appearance and reading options back to their defaults: Settings › Reset settings\n\nStill stuck? Tell us through Feedback.',
    ),
    path: ['settings', 'clearCache'],
    keywords: [
      'problem',
      '问题',
      'bug',
      '错误',
      'error',
      '卡住',
      'stuck',
      'blank',
      '空白',
      '加载失败',
      'reload',
      '重新加载',
      'reset',
      '恢复',
      '重置',
      'cache',
      '缓存',
      'refresh',
      '刷新',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'about',
    section: HelpSection.settings,
    title: HelpText(
      '版权说明与联系方式',
      '版權說明與聯絡方式',
      'Attributions & licensing',
    ),
    body: HelpText(
      '每个译本、词典和资料的出处与授权、版本号和联系方式：「设置」›「关于」。',
      '每個譯本、詞典和資料的出處與授權、版本號和聯絡方式：「設定」›「關於」。',
      'Where every version, lexicon and resource comes from and under what licence, the version number and contact details: Settings › About.',
    ),
    path: ['settings', 'settingsSectionAbout'],
    keywords: [
      'about',
      '关于',
      'license',
      'licence',
      '授权',
      '版权',
      'copyright',
      'source',
      '来源',
      'version',
      '版本号',
      'contact',
      '联系',
    ],
    open: HelpDestination.about,
  ),
  HelpTopic(
    id: 'platform-web',
    section: HelpSection.platforms,
    title: HelpText(
      '在浏览器里用',
      '在瀏覽器裡用',
      'In a browser',
    ),
    body: HelpText(
      '打开 yahwehword.com 就能用，不用安装，也不用登录。\n\n• 可以装到主屏幕或桌面（见「把网页版装到手机或电脑上」）\n• 离线包下载一次后，没网也能读经\n• 提醒要等下次打开才送达；想准时收到，请用下载安装的 app\n• 在中国大陆请用中国版网站：不需要翻墙，能用邮箱登录同步（不提供 Google 登录）',
      '開啟 yahwehword.com 就能用，不用安裝，也不用登入。\n\n• 可以裝到主螢幕或桌面（見「把網頁版裝到手機或電腦上」）\n• 離線包下載一次後，沒網也能讀經\n• 提醒要等下次開啟才送達；想準時收到，請用下載安裝的 app\n• 在中國大陸請用中國版網站：不需要翻牆，能用郵箱登入同步（不提供 Google 登入）',
      'Open yahwehword.com — nothing to install, no sign-in needed.\n\n• It installs to a home screen or desktop (see "Installing the web version")\n• After one offline-pack download it reads without a connection\n• Reminders wait until you next open it; for them on time, use the downloaded app\n• In mainland China use the China build of the site: no VPN needed, and email sign-in syncs (Google sign-in is not offered)',
    ),
    keywords: [
      'web',
      '网页',
      'browser',
      '浏览器',
      'Chrome',
      'Safari',
      'Edge',
      'online',
      '在线',
      'China',
      '中国',
      '大陆',
      '翻墙',
      'VPN',
    ],
    only: {HelpPlatform.web},
  ),
  HelpTopic(
    id: 'platform-ios',
    section: HelpSection.platforms,
    title: HelpText(
      '在 iPhone 和 iPad 上',
      '在 iPhone 和 iPad 上',
      'On iPhone and iPad',
    ),
    body: HelpText(
      '• 点经文选中，左右滑动翻章，点空白处隐藏顶栏\n• iPad 上分屏是左右两栏，还有可收起的侧栏\n• 改主色调时，主屏幕上的 app 图标跟着变色\n• 接上键盘时，⌘[ ⌘] 翻章、⌘F 搜索、⌘, 打开设置、? 打开使用说明',
      '• 點經文選中，左右滑動翻章，點空白處隱藏頂欄\n• iPad 上分屏是左右兩欄，還有可收起的側欄\n• 改主色調時，主螢幕上的 app 圖示跟著變色\n• 接上鍵盤時，⌘[ ⌘] 翻章、⌘F 搜尋、⌘, 開啟設定、? 開啟使用說明',
      '• Tap to select a verse, swipe sideways to turn the chapter, tap a margin to hide the bars\n• On an iPad Split View sits side by side, and there is a collapsible sidebar\n• Changing the primary colour recolours the home-screen icon\n• With a keyboard: ⌘[ ⌘] turn the chapter, ⌘F searches, ⌘, opens Settings, ? opens Help',
    ),
    keywords: [
      'iPhone',
      'iPad',
      'iOS',
      'Apple',
      'touch',
      '触屏',
      'phone',
      '手机',
      'tablet',
      '平板',
      'keyboard',
      '键盘',
    ],
    only: {HelpPlatform.ios},
  ),
  HelpTopic(
    id: 'platform-android',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Android 上',
      '在 Android 上',
      'On Android',
    ),
    body: HelpText(
      '• 点经文选中，左右滑动翻章，点空白处隐藏顶栏\n• 更新可以在 app 里直接下载安装\n• 改主色调时 app 图标跟着变色（会重新打开一次）\n• 可以用 Google 或邮箱登录同步',
      '• 點經文選中，左右滑動翻章，點空白處隱藏頂欄\n• 更新可以在 app 裡直接下載安裝\n• 改主色調時 app 圖示跟著變色（會重新開啟一次）\n• 可以用 Google 或郵箱登入同步',
      '• Tap to select a verse, swipe sideways to turn the chapter, tap a margin to hide the bars\n• Updates download and install inside the app\n• Changing the primary colour recolours the icon (the app restarts once)\n• Sign in with Google or email to sync',
    ),
    keywords: [
      'Android',
      '安卓',
      'phone',
      '手机',
      'tablet',
      '平板',
      'Samsung',
      '三星',
      'Xiaomi',
      '小米',
      'Huawei',
      '华为',
      'APK',
      'touch',
      '触屏',
    ],
    only: {HelpPlatform.android},
  ),
  HelpTopic(
    id: 'platform-macos',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Mac 上',
      '在 Mac 上',
      'On a Mac',
    ),
    body: HelpText(
      '快捷键用 ⌘：⌘[ ⌘] 上一章下一章，⌘F 搜索，⌘, 设置，? 使用说明（先点一下经文区）。\n\n第一次打开下载的 app 时，如果 macOS 说无法验证开发者：在「应用程序」里右键点 Yahwehs-Words，选「打开」，再点一次「打开」。之后就正常了。',
      '快捷鍵用 ⌘：⌘[ ⌘] 上一章下一章，⌘F 搜尋，⌘, 設定，? 使用說明（先點一下經文區）。\n\n第一次開啟下載的 app 時，如果 macOS 說無法驗證開發者：在「應用程式」裡右鍵點 Yahwehs-Words，選「開啟」，再點一次「開啟」。之後就正常了。',
      'Shortcuts use ⌘: ⌘[ ⌘] previous and next chapter, ⌘F search, ⌘, Settings, ? Help (click in the text first).\n\nIf macOS says it cannot verify the developer the first time you open the downloaded app: in Applications, right-click Yahwehs-Words, choose Open, then Open again. It opens normally from then on.',
    ),
    keywords: [
      'Mac',
      'macOS',
      'Apple',
      'MacBook',
      '⌘',
      'Command',
      'Gatekeeper',
      '无法验证',
      'cannot be opened',
      'unidentified developer',
      '身份不明',
    ],
    only: {HelpPlatform.macos},
  ),
  HelpTopic(
    id: 'platform-windows',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Windows 上',
      '在 Windows 上',
      'On Windows',
    ),
    body: HelpText(
      '解压下载的压缩包，运行 Yahwehs-Words 文件夹里的 Yahwehs-Words.exe。快捷键：[ ] 或 Ctrl+[ Ctrl+] 翻章，/ 搜索，? 使用说明。\n\n如果 Windows 弹出「Windows 已保护你的电脑」，点「更多信息」›「仍要运行」。',
      '解壓下載的壓縮包，執行 Yahwehs-Words 資料夾裡的 Yahwehs-Words.exe。快捷鍵：[ ] 或 Ctrl+[ Ctrl+] 翻章，/ 搜尋，? 使用說明。\n\n如果 Windows 彈出「Windows 已保護你的電腦」，點「更多資訊」›「仍要執行」。',
      'Unzip the download and run Yahwehs-Words.exe in the Yahwehs-Words folder. Shortcuts: [ ] or Ctrl+[ Ctrl+] turn the chapter, / searches, ? opens Help.\n\nIf Windows shows "Windows protected your PC", choose More info › Run anyway.',
    ),
    keywords: [
      'Windows',
      'PC',
      'exe',
      'Ctrl',
      'SmartScreen',
      '保护',
      'protected',
      '运行',
      'run anyway',
    ],
    only: {HelpPlatform.windows},
  ),
  HelpTopic(
    id: 'platform-linux',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Linux 上',
      '在 Linux 上',
      'On Linux',
    ),
    body: HelpText(
      '解压下载的压缩包，在文件夹里运行 ./Yahwehs-Words。快捷键和 Windows 相同。',
      '解壓下載的壓縮包，在資料夾裡執行 ./Yahwehs-Words。快捷鍵和 Windows 相同。',
      'Unpack the download and run ./Yahwehs-Words in its folder. Shortcuts are the same as on Windows.',
    ),
    keywords: [
      'Linux',
      'Ubuntu',
      'Debian',
      'Fedora',
      'Ctrl',
      'terminal',
      '终端',
    ],
    only: {HelpPlatform.linux},
  ),
];

/// Headings for the shortcut groups the Help page prints.
const Map<String, HelpText> kHelpKeyGroupTitles = {
  'keysReader': HelpText(
    '阅读页（先点一下经文）',
    '閱讀頁（先點一下經文）',
    'In the reader (click the text first)',
  ),
  'keysProjection': HelpText(
    '投影',
    '投影',
    'Projection',
  ),
  'keysTouch': HelpText(
    '触屏手势',
    '觸屏手勢',
    'Touch gestures',
  ),
};

/// What a finger does, for the touch platforms — (gesture, effect).
const List<(HelpText, HelpText)> kHelpTouchGestures = [
  (
    HelpText(
      '点一下经节',
      '點一下經節',
      'Tap a verse',
    ),
    HelpText(
      '选中；可以连续点选多节',
      '選中；可以連續點選多節',
      'Select it; keep tapping for more',
    ),
  ),
  (
    HelpText(
      '左右滑动经文',
      '左右滑動經文',
      'Swipe the text sideways',
    ),
    HelpText(
      '上一章 / 下一章',
      '上一章 / 下一章',
      'Previous / next chapter',
    ),
  ),
  (
    HelpText(
      '点经文旁的空白处',
      '點經文旁的空白處',
      'Tap a margin',
    ),
    HelpText(
      '隐藏或显示顶栏和底栏',
      '隱藏或顯示頂欄和底欄',
      'Hide or show the bars',
    ),
  ),
  (
    HelpText(
      '在主页往下拉',
      '在主頁往下拉',
      'Pull down on the home page',
    ),
    HelpText(
      '立刻同步（已登录时）并检查新版本',
      '立刻同步（已登入時）並檢查新版本',
      'Sync now (when signed in) and check for a new version',
    ),
  ),
  (
    HelpText(
      '拖动分屏中间的分隔条',
      '拖動分屏中間的分隔條',
      'Drag the Split View divider',
    ),
    HelpText(
      '调整两栏大小',
      '調整兩欄大小',
      'Resize the two panes',
    ),
  ),
  (
    HelpText(
      '长按「我的高亮」里的一条',
      '長按「我的高亮」裡的一條',
      'Long-press an entry in My Highlights',
    ),
    HelpText(
      '复制、分享或删除',
      '複製、分享或刪除',
      'Copy, share or remove it',
    ),
  ),
];
