#!/usr/bin/env python3
"""
Author section/paragraph titles for Bible chapters and bundle them
into a single asset:  assets/section_titles.json.

Schema:
  {
    "_meta": { "version": 1, "books": ["Genesis", "Matthew", "John", "Romans"] },
    "sets": {
      "<set-id>": {
        "<EnglishBookName>": {
          "<chapter-as-string>": [
            {"verse": <int>, "title": "<heading text>"},
            ...
          ]
        }
      }
    }
  }

Three sets are emitted in this Phase-1 file:
  • cuv               — simplified-Chinese 和合本-style headings
  • cuv-tr            — traditional-Chinese mirror of cuv
  • english-classic   — neutral English Bible-society style headings

The title-set-per-version mapping lives in
`lib/constants/section_title_map.dart`. New title sets (e.g. cnv) can
be added later without code changes once authored.

Pairs are author-curated (not machine-translated) so that each
language reads naturally for its audience.
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "assets", "section_titles.json")


# Each entry is: (chapter, verse, title_simplified, title_traditional, title_english)
# Authored against well-known CUV / KJV-style section divisions.
GENESIS: list[tuple[int, int, str, str, str]] = [
    (1, 1, "起初创造天地", "起初創造天地", "The Creation"),
    (1, 14, "第四日：日月星辰", "第四日：日月星辰", "The Fourth Day: Sun, Moon, and Stars"),
    (1, 26, "创造人类", "創造人類", "The Creation of Mankind"),
    (2, 1, "第七日安息", "第七日安息", "The Seventh Day, God Rests"),
    (2, 4, "伊甸园", "伊甸園", "The Garden of Eden"),
    (2, 18, "造夏娃", "造夏娃", "The Creation of Woman"),
    (3, 1, "人类的堕落", "人類的墮落", "The Fall of Mankind"),
    (3, 14, "神的审判", "神的審判", "Judgment and Promise"),
    (3, 22, "驱逐出园", "驅逐出園", "Expulsion from Eden"),
    (4, 1, "该隐与亚伯", "該隱與亞伯", "Cain and Abel"),
    (4, 17, "该隐的后裔", "該隱的後裔", "The Descendants of Cain"),
    (4, 25, "塞特的家系", "塞特的家系", "Seth and His Descendants"),
    (5, 1, "亚当的家谱", "亞當的家譜", "The Genealogy from Adam to Noah"),
    (6, 1, "人类的败坏", "人類的敗壞", "The Wickedness of Mankind"),
    (6, 9, "挪亚造方舟", "挪亞造方舟", "Noah and the Ark"),
    (7, 1, "洪水来到", "洪水來到", "The Great Flood"),
    (8, 1, "洪水退去", "洪水退去", "The Flood Recedes"),
    (8, 20, "挪亚献祭", "挪亞獻祭", "Noah's Sacrifice"),
    (9, 1, "神与挪亚立约", "神與挪亞立約", "God's Covenant with Noah"),
    (9, 18, "挪亚的预言", "挪亞的預言", "Noah's Sons"),
    (10, 1, "列国的起源", "列國的起源", "The Table of Nations"),
    (11, 1, "巴别塔", "巴別塔", "The Tower of Babel"),
    (11, 10, "闪的家谱", "閃的家譜", "The Genealogy from Shem to Abram"),
    (11, 27, "他拉的家谱", "他拉的家譜", "The Family of Terah"),
    (12, 1, "神呼召亚伯兰", "神呼召亞伯蘭", "The Call of Abram"),
    (12, 10, "亚伯兰下埃及", "亞伯蘭下埃及", "Abram in Egypt"),
    (13, 1, "亚伯兰与罗得分地", "亞伯蘭與羅得分地", "Abram and Lot Separate"),
    (14, 1, "列王交战", "列王交戰", "Abram Rescues Lot"),
    (14, 17, "麦基洗德祝福亚伯兰", "麥基洗德祝福亞伯蘭", "Melchizedek Blesses Abram"),
    (15, 1, "神与亚伯兰立约", "神與亞伯蘭立約", "God's Covenant with Abram"),
    (16, 1, "夏甲与以实玛利", "夏甲與以實瑪利", "Hagar and Ishmael"),
    (17, 1, "立割礼之约", "立割禮之約", "The Covenant of Circumcision"),
    (18, 1, "三位访客", "三位訪客", "The Three Visitors"),
    (18, 16, "亚伯拉罕为所多玛代求", "亞伯拉罕為所多瑪代求", "Abraham Pleads for Sodom"),
    (19, 1, "所多玛与蛾摩拉的毁灭", "所多瑪與蛾摩拉的毀滅", "The Destruction of Sodom and Gomorrah"),
    (19, 30, "罗得与他的女儿们", "羅得與他的女兒們", "Lot and His Daughters"),
    (20, 1, "亚伯拉罕与亚比米勒", "亞伯拉罕與亞比米勒", "Abraham and Abimelech"),
    (21, 1, "以撒出生", "以撒出生", "The Birth of Isaac"),
    (21, 8, "夏甲与以实玛利被遣", "夏甲與以實瑪利被遣", "Hagar and Ishmael Sent Away"),
    (21, 22, "亚比米勒之约", "亞比米勒之約", "Treaty with Abimelech"),
    (22, 1, "亚伯拉罕献以撒", "亞伯拉罕獻以撒", "Abraham Offers Isaac"),
    (22, 20, "拿鹤的子孙", "拿鶴的子孫", "The Children of Nahor"),
    (23, 1, "撒拉之死与安葬", "撒拉之死與安葬", "Sarah's Death and Burial"),
    (24, 1, "以撒娶利百加", "以撒娶利百加", "Isaac Marries Rebekah"),
    (25, 1, "亚伯拉罕去世", "亞伯拉罕去世", "The Death of Abraham"),
    (25, 19, "雅各与以扫的出生", "雅各與以掃的出生", "The Birth of Jacob and Esau"),
    (25, 29, "以扫卖长子名分", "以掃賣長子名分", "Esau Sells His Birthright"),
    (26, 1, "以撒在基拉耳", "以撒在基拉耳", "Isaac and Abimelech"),
    (26, 34, "以扫娶妻", "以掃娶妻", "Esau's Wives"),
    (27, 1, "雅各骗取祝福", "雅各騙取祝福", "Jacob Receives Isaac's Blessing"),
    (27, 41, "雅各逃往哈兰", "雅各逃往哈蘭", "Jacob Flees from Esau"),
    (28, 10, "雅各在伯特利的梦", "雅各在伯特利的夢", "Jacob's Dream at Bethel"),
    (29, 1, "雅各与拉班相会", "雅各與拉班相會", "Jacob Meets Rachel"),
    (29, 31, "雅各的儿子们", "雅各的兒子們", "Jacob's Children"),
    (30, 25, "雅各的产业", "雅各的產業", "Jacob's Flocks Increase"),
    (31, 1, "雅各离开拉班", "雅各離開拉班", "Jacob Flees from Laban"),
    (32, 1, "雅各预备见以扫", "雅各預備見以掃", "Jacob Prepares to Meet Esau"),
    (32, 22, "雅各与神摔跤", "雅各與神摔跤", "Jacob Wrestles with God"),
    (33, 1, "雅各与以扫和好", "雅各與以掃和好", "Jacob Meets Esau"),
    (34, 1, "底拿被玷污", "底拿被玷污", "The Defilement of Dinah"),
    (35, 1, "雅各回到伯特利", "雅各回到伯特利", "Jacob Returns to Bethel"),
    (35, 16, "拉结之死", "拉結之死", "The Death of Rachel"),
    (36, 1, "以扫的后裔", "以掃的後裔", "The Descendants of Esau"),
    (37, 1, "约瑟的梦", "約瑟的夢", "Joseph's Dreams"),
    (37, 12, "约瑟被卖", "約瑟被賣", "Joseph Sold into Slavery"),
    (38, 1, "犹大与他玛", "猶大與他瑪", "Judah and Tamar"),
    (39, 1, "约瑟在波提乏家", "約瑟在波提乏家", "Joseph in Potiphar's House"),
    (39, 7, "约瑟受诬下监", "約瑟受誣下監", "Joseph Falsely Accused"),
    (40, 1, "约瑟解囚犯的梦", "約瑟解囚犯的夢", "The Cupbearer and the Baker"),
    (41, 1, "约瑟解法老的梦", "約瑟解法老的夢", "Joseph Interprets Pharaoh's Dreams"),
    (41, 38, "约瑟治理埃及", "約瑟治理埃及", "Joseph Made Ruler of Egypt"),
    (42, 1, "约瑟的兄弟下埃及", "約瑟的兄弟下埃及", "Joseph's Brothers Come to Egypt"),
    (43, 1, "第二次到埃及", "第二次到埃及", "The Second Journey to Egypt"),
    (44, 1, "约瑟试验兄弟", "約瑟試驗兄弟", "Joseph Tests His Brothers"),
    (45, 1, "约瑟与兄弟相认", "約瑟與兄弟相認", "Joseph Reveals Himself"),
    (46, 1, "雅各下埃及", "雅各下埃及", "Jacob Goes to Egypt"),
    (47, 13, "约瑟治理饥荒", "約瑟治理饑荒", "Joseph Manages the Famine"),
    (47, 28, "雅各祝福约瑟的儿子", "雅各祝福約瑟的兒子", "Jacob Blesses Joseph's Sons"),
    (49, 1, "雅各祝福十二支派", "雅各祝福十二支派", "Jacob Blesses His Sons"),
    (49, 29, "雅各之死", "雅各之死", "The Death of Jacob"),
    (50, 1, "约瑟葬父", "約瑟葬父", "Jacob's Burial"),
    (50, 15, "约瑟安慰兄弟", "約瑟安慰兄弟", "Joseph Reassures His Brothers"),
    (50, 22, "约瑟之死", "約瑟之死", "The Death of Joseph"),
]

MATTHEW: list[tuple[int, int, str, str, str]] = [
    (1, 1, "耶稣的家谱", "耶穌的家譜", "The Genealogy of Jesus"),
    (1, 18, "耶稣降生", "耶穌降生", "The Birth of Jesus"),
    (2, 1, "博士来朝", "博士來朝", "The Visit of the Magi"),
    (2, 13, "逃往埃及", "逃往埃及", "The Flight to Egypt"),
    (2, 19, "回拿撒勒", "回拿撒勒", "The Return to Nazareth"),
    (3, 1, "施洗约翰传道", "施洗約翰傳道", "John the Baptist Prepares the Way"),
    (3, 13, "耶稣受洗", "耶穌受洗", "The Baptism of Jesus"),
    (4, 1, "耶稣受试探", "耶穌受試探", "The Temptation of Jesus"),
    (4, 12, "在加利利开始传道", "在加利利開始傳道", "Jesus Begins His Ministry"),
    (4, 18, "呼召四个门徒", "呼召四個門徒", "Jesus Calls His First Disciples"),
    (5, 1, "登山宝训：八福", "登山寶訓：八福", "The Sermon on the Mount: The Beatitudes"),
    (5, 13, "盐与光", "鹽與光", "Salt and Light"),
    (5, 17, "耶稣与律法", "耶穌與律法", "The Fulfillment of the Law"),
    (5, 21, "论怒气", "論怒氣", "Teaching About Anger"),
    (5, 27, "论奸淫", "論姦淫", "Teaching About Lust"),
    (5, 31, "论离婚", "論離婚", "Teaching About Divorce"),
    (5, 33, "论起誓", "論起誓", "Teaching About Oaths"),
    (5, 38, "论报复", "論報復", "Teaching About Retaliation"),
    (5, 43, "爱仇敌", "愛仇敵", "Love Your Enemies"),
    (6, 1, "论施舍", "論施捨", "Teaching About Giving"),
    (6, 5, "论祷告", "論禱告", "Teaching About Prayer"),
    (6, 9, "主祷文", "主禱文", "The Lord's Prayer"),
    (6, 16, "论禁食", "論禁食", "Teaching About Fasting"),
    (6, 19, "论财宝", "論財寶", "Treasures in Heaven"),
    (6, 25, "论忧虑", "論憂慮", "Do Not Worry"),
    (7, 1, "论论断人", "論論斷人", "Do Not Judge"),
    (7, 7, "祈求与寻找", "祈求與尋找", "Ask, Seek, Knock"),
    (7, 13, "窄门与宽门", "窄門與寬門", "The Narrow and Wide Gates"),
    (7, 15, "假先知与好果子", "假先知與好果子", "True and False Prophets"),
    (7, 24, "聪明人与愚拙人", "聰明人與愚拙人", "The Wise and Foolish Builders"),
    (8, 1, "洁净长大痲疯", "潔淨長大痲瘋", "Jesus Heals a Leper"),
    (8, 5, "百夫长的信心", "百夫長的信心", "The Faith of the Centurion"),
    (8, 14, "医治许多病人", "醫治許多病人", "Jesus Heals Many"),
    (8, 23, "平静风浪", "平靜風浪", "Jesus Calms the Storm"),
    (8, 28, "赶逐群鬼", "趕逐群鬼", "The Demon-Possessed Men of Gadara"),
    (9, 1, "医治瘫子", "醫治癱子", "Jesus Heals a Paralyzed Man"),
    (9, 9, "呼召马太", "呼召馬太", "The Calling of Matthew"),
    (9, 14, "禁食的问题", "禁食的問題", "Question About Fasting"),
    (9, 18, "复活女孩与医治血漏", "復活女孩與醫治血漏", "The Dead Girl and the Sick Woman"),
    (9, 27, "医治瞎子与哑巴", "醫治瞎子與啞巴", "Jesus Heals the Blind and Mute"),
    (9, 35, "庄稼多工人少", "莊稼多工人少", "The Workers Are Few"),
    (10, 1, "差遣十二门徒", "差遣十二門徒", "Jesus Sends Out the Twelve"),
    (10, 16, "面临逼迫", "面臨逼迫", "Coming Persecutions"),
    (10, 32, "认主与作门徒的代价", "認主與作門徒的代價", "Acknowledging Christ"),
    (11, 1, "施洗约翰的疑问", "施洗約翰的疑問", "Jesus and John the Baptist"),
    (11, 20, "灾祸与安息", "災禍與安息", "Woe to Unrepentant Cities"),
    (12, 1, "安息日的主", "安息日的主", "The Lord of the Sabbath"),
    (12, 22, "耶稣与别西卜", "耶穌與別西卜", "Jesus and Beelzebul"),
    (12, 38, "约拿的兆头", "約拿的兆頭", "The Sign of Jonah"),
    (12, 46, "耶稣的真亲属", "耶穌的真親屬", "The True Family of Jesus"),
    (13, 1, "撒种的比喻", "撒種的比喻", "The Parable of the Sower"),
    (13, 24, "稗子的比喻", "稗子的比喻", "The Parable of the Weeds"),
    (13, 31, "芥菜种与酵的比喻", "芥菜種與酵的比喻", "The Mustard Seed and Yeast"),
    (13, 44, "藏宝与珍珠的比喻", "藏寶與珍珠的比喻", "Hidden Treasure and Pearl"),
    (13, 53, "在拿撒勒被弃", "在拿撒勒被棄", "Rejected at Nazareth"),
    (14, 1, "施洗约翰被斩", "施洗約翰被斬", "John the Baptist Beheaded"),
    (14, 13, "喂饱五千人", "餵飽五千人", "Jesus Feeds the Five Thousand"),
    (14, 22, "耶稣行走海面", "耶穌行走海面", "Jesus Walks on Water"),
    (15, 1, "古人的遗传", "古人的遺傳", "Clean and Unclean"),
    (15, 21, "迦南妇人的信心", "迦南婦人的信心", "The Faith of the Canaanite Woman"),
    (15, 32, "喂饱四千人", "餵飽四千人", "Jesus Feeds the Four Thousand"),
    (16, 1, "求兆头", "求兆頭", "The Demand for a Sign"),
    (16, 13, "彼得的认信", "彼得的認信", "Peter's Confession of Christ"),
    (16, 21, "首次预言受难", "首次預言受難", "Jesus Predicts His Death"),
    (17, 1, "耶稣登山变像", "耶穌登山變像", "The Transfiguration"),
    (17, 14, "医治被鬼附的孩子", "醫治被鬼附的孩子", "Jesus Heals a Demon-Possessed Boy"),
    (17, 24, "纳殿税", "納殿稅", "The Temple Tax"),
    (18, 1, "天国里最大的", "天國裡最大的", "The Greatest in the Kingdom"),
    (18, 10, "迷失羊的比喻", "迷失羊的比喻", "The Parable of the Lost Sheep"),
    (18, 15, "弟兄犯罪当如何对待", "弟兄犯罪當如何對待", "Dealing with Sin in the Church"),
    (18, 21, "无怜悯仆人的比喻", "無憐憫僕人的比喻", "The Parable of the Unforgiving Servant"),
    (19, 1, "论离婚", "論離婚", "Jesus Teaches About Divorce"),
    (19, 13, "耶稣祝福小孩", "耶穌祝福小孩", "Jesus Blesses the Children"),
    (19, 16, "财主的难处", "財主的難處", "The Rich Young Ruler"),
    (20, 1, "葡萄园工人的比喻", "葡萄園工人的比喻", "The Workers in the Vineyard"),
    (20, 17, "再次预言受难", "再次預言受難", "Jesus Foretells His Death Again"),
    (20, 20, "西庇太儿子的请求", "西庇太兒子的請求", "A Mother's Request"),
    (20, 29, "医治瞎眼的人", "醫治瞎眼的人", "Two Blind Men Receive Sight"),
    (21, 1, "光荣进入耶路撒冷", "光榮進入耶路撒冷", "The Triumphal Entry"),
    (21, 12, "洁净圣殿", "潔淨聖殿", "Jesus Cleanses the Temple"),
    (21, 18, "咒诅无花果树", "咒詛無花果樹", "Jesus Curses the Fig Tree"),
    (21, 23, "盘问耶稣的权柄", "盤問耶穌的權柄", "The Authority of Jesus Questioned"),
    (21, 33, "凶恶园户的比喻", "兇惡園戶的比喻", "The Parable of the Wicked Tenants"),
    (22, 1, "婚筵的比喻", "婚筵的比喻", "The Parable of the Wedding Banquet"),
    (22, 15, "纳税给凯撒", "納稅給凱撒", "Paying Taxes to Caesar"),
    (22, 23, "复活的问题", "復活的問題", "Marriage at the Resurrection"),
    (22, 34, "最大的诫命", "最大的誡命", "The Greatest Commandment"),
    (23, 1, "斥责文士与法利赛人", "斥責文士與法利賽人", "Seven Woes to Religious Leaders"),
    (24, 1, "末世的预兆", "末世的預兆", "Signs of the End of the Age"),
    (24, 36, "无人知道那日子", "無人知道那日子", "No One Knows the Day or Hour"),
    (25, 1, "十童女的比喻", "十童女的比喻", "The Parable of the Ten Virgins"),
    (25, 14, "按才受托的比喻", "按才受托的比喻", "The Parable of the Talents"),
    (25, 31, "羊与山羊", "羊與山羊", "The Final Judgment"),
    (26, 1, "杀害耶稣的阴谋", "殺害耶穌的陰謀", "The Plot Against Jesus"),
    (26, 6, "在伯大尼受膏", "在伯大尼受膏", "Jesus Anointed at Bethany"),
    (26, 14, "犹大要卖耶稣", "猶大要賣耶穌", "Judas Agrees to Betray Jesus"),
    (26, 17, "最后的晚餐", "最後的晚餐", "The Last Supper"),
    (26, 36, "客西马尼园祷告", "客西馬尼園禱告", "Gethsemane"),
    (26, 47, "耶稣被捕", "耶穌被捕", "Jesus Arrested"),
    (26, 57, "公会受审", "公會受審", "Jesus Before the Sanhedrin"),
    (26, 69, "彼得三次否认", "彼得三次否認", "Peter Disowns Jesus"),
    (27, 1, "犹大自杀", "猶大自殺", "Judas Hangs Himself"),
    (27, 11, "彼拉多前受审", "彼拉多前受審", "Jesus Before Pilate"),
    (27, 27, "戏弄与定罪", "戲弄與定罪", "The Soldiers Mock Jesus"),
    (27, 32, "钉十字架", "釘十字架", "The Crucifixion"),
    (27, 45, "耶稣之死", "耶穌之死", "The Death of Jesus"),
    (27, 57, "耶稣被埋葬", "耶穌被埋葬", "The Burial of Jesus"),
    (28, 1, "耶稣复活", "耶穌復活", "The Resurrection"),
    (28, 11, "兵丁的报告", "兵丁的報告", "The Report of the Guards"),
    (28, 16, "大使命", "大使命", "The Great Commission"),
]

JOHN: list[tuple[int, int, str, str, str]] = [
    (1, 1, "道成肉身", "道成肉身", "The Word Became Flesh"),
    (1, 19, "施洗约翰的见证", "施洗約翰的見證", "John the Baptist's Testimony"),
    (1, 35, "首批门徒", "首批門徒", "The First Disciples Follow Jesus"),
    (1, 43, "呼召腓力与拿但业", "呼召腓力與拿但業", "Jesus Calls Philip and Nathanael"),
    (2, 1, "迦拿婚宴", "迦拿婚宴", "The Wedding at Cana"),
    (2, 13, "洁净圣殿", "潔淨聖殿", "Jesus Clears the Temple"),
    (3, 1, "尼哥底母访耶稣", "尼哥底母訪耶穌", "Jesus Teaches Nicodemus"),
    (3, 22, "施洗约翰为耶稣作证", "施洗約翰為耶穌作證", "John Testifies Again About Jesus"),
    (4, 1, "撒玛利亚妇人", "撒瑪利亞婦人", "The Samaritan Woman at the Well"),
    (4, 27, "庄稼已熟", "莊稼已熟", "The Disciples Rejoin Jesus"),
    (4, 43, "医治大臣的儿子", "醫治大臣的兒子", "Jesus Heals an Official's Son"),
    (5, 1, "毕士大池的医治", "畢士大池的醫治", "Healing at the Pool"),
    (5, 16, "子与父", "子與父", "Life Through the Son"),
    (6, 1, "喂饱五千人", "餵飽五千人", "Jesus Feeds the Five Thousand"),
    (6, 16, "耶稣行走海面", "耶穌行走海面", "Jesus Walks on Water"),
    (6, 25, "生命的粮", "生命的糧", "Jesus the Bread of Life"),
    (6, 60, "许多门徒退去", "許多門徒退去", "Many Disciples Desert Jesus"),
    (7, 1, "上耶路撒冷过节", "上耶路撒冷過節", "Jesus Goes to the Festival"),
    (7, 25, "群众的争论", "群眾的爭論", "Is Jesus the Messiah?"),
    (7, 37, "活水的应许", "活水的應許", "Streams of Living Water"),
    (8, 1, "行淫的妇人", "行淫的婦人", "The Woman Caught in Adultery"),
    (8, 12, "世界的光", "世界的光", "Jesus the Light of the World"),
    (8, 31, "真理使你们自由", "真理使你們自由", "The Truth Will Set You Free"),
    (9, 1, "医治生来瞎眼的人", "醫治生來瞎眼的人", "Jesus Heals a Man Born Blind"),
    (10, 1, "好牧人", "好牧人", "The Good Shepherd"),
    (10, 22, "犹太人不信", "猶太人不信", "Further Conflict"),
    (11, 1, "拉撒路复活", "拉撒路復活", "The Death and Raising of Lazarus"),
    (11, 45, "杀害耶稣的阴谋", "殺害耶穌的陰謀", "The Plot to Kill Jesus"),
    (12, 1, "在伯大尼受膏", "在伯大尼受膏", "Jesus Anointed at Bethany"),
    (12, 12, "光荣进入耶路撒冷", "光榮進入耶路撒冷", "The Triumphal Entry"),
    (12, 20, "希利尼人求见耶稣", "希利尼人求見耶穌", "Jesus Predicts His Death"),
    (13, 1, "为门徒洗脚", "為門徒洗腳", "Jesus Washes the Disciples' Feet"),
    (13, 21, "预告卖主与不认主", "預告賣主與不認主", "Jesus Predicts His Betrayal"),
    (13, 31, "新命令", "新命令", "Jesus Predicts Peter's Denial"),
    (14, 1, "我是道路、真理、生命", "我是道路、真理、生命", "I Am the Way, Truth, and Life"),
    (14, 15, "应许圣灵", "應許聖靈", "The Promise of the Holy Spirit"),
    (15, 1, "真葡萄树", "真葡萄樹", "The True Vine"),
    (15, 18, "世人的恨", "世人的恨", "The World Hates the Disciples"),
    (16, 1, "圣灵的工作", "聖靈的工作", "The Work of the Holy Spirit"),
    (16, 16, "忧愁变为喜乐", "憂愁變為喜樂", "The Disciples' Grief Will Turn to Joy"),
    (17, 1, "耶稣大祭司的祷告", "耶穌大祭司的禱告", "Jesus Prays for Himself and His Disciples"),
    (18, 1, "耶稣被捕", "耶穌被捕", "Jesus Arrested"),
    (18, 15, "彼得的否认", "彼得的否認", "Peter Denies Jesus"),
    (18, 28, "彼拉多前受审", "彼拉多前受審", "Jesus Before Pilate"),
    (19, 1, "戏弄与判刑", "戲弄與判刑", "Jesus Sentenced to Be Crucified"),
    (19, 17, "钉十字架", "釘十字架", "The Crucifixion"),
    (19, 38, "耶稣被埋葬", "耶穌被埋葬", "The Burial of Jesus"),
    (20, 1, "空坟墓", "空墳墓", "The Empty Tomb"),
    (20, 11, "向抹大拉的马利亚显现", "向抹大拉的馬利亞顯現", "Jesus Appears to Mary Magdalene"),
    (20, 19, "向门徒显现", "向門徒顯現", "Jesus Appears to His Disciples"),
    (20, 24, "多马的疑惑", "多馬的疑惑", "Jesus Appears to Thomas"),
    (21, 1, "提比哩亚海边显现", "提比哩亞海邊顯現", "Jesus and the Miraculous Catch of Fish"),
    (21, 15, "三次问爱与托付", "三次問愛與託付", "Jesus Reinstates Peter"),
]

ROMANS: list[tuple[int, int, str, str, str]] = [
    (1, 1, "问安", "問安", "Greeting"),
    (1, 8, "渴望访问罗马", "渴望訪問羅馬", "Paul's Longing to Visit Rome"),
    (1, 16, "福音的大能", "福音的大能", "The Power of the Gospel"),
    (1, 18, "神的忿怒", "神的忿怒", "God's Wrath Against Mankind"),
    (2, 1, "神公义的审判", "神公義的審判", "God's Righteous Judgment"),
    (2, 17, "犹太人与律法", "猶太人與律法", "The Jews and the Law"),
    (3, 1, "犹太人的优势", "猶太人的優勢", "The Faithfulness of God"),
    (3, 9, "都在罪恶之下", "都在罪惡之下", "No One Is Righteous"),
    (3, 21, "因信称义", "因信稱義", "Righteousness Through Faith"),
    (4, 1, "亚伯拉罕因信称义", "亞伯拉罕因信稱義", "Abraham Justified by Faith"),
    (4, 13, "应许借着信", "應許藉著信", "The Promise Through Faith"),
    (5, 1, "因信得平安", "因信得平安", "Peace and Hope"),
    (5, 12, "亚当与基督", "亞當與基督", "Adam and Christ"),
    (6, 1, "向罪死，向神活", "向罪死，向神活", "Dead to Sin, Alive in Christ"),
    (6, 15, "义的奴仆", "義的奴僕", "Slaves to Righteousness"),
    (7, 1, "脱离律法", "脫離律法", "Released from the Law"),
    (7, 7, "律法与罪", "律法與罪", "The Law and Sin"),
    (7, 14, "心中的争战", "心中的爭戰", "The Inner Conflict"),
    (8, 1, "圣灵的生命", "聖靈的生命", "Life Through the Spirit"),
    (8, 18, "将来的荣耀", "將來的榮耀", "Future Glory"),
    (8, 28, "万事互相效力", "萬事互相效力", "More Than Conquerors"),
    (9, 1, "保罗为同胞忧伤", "保羅為同胞憂傷", "Paul's Sorrow for Israel"),
    (9, 14, "神的拣选", "神的揀選", "God's Sovereign Choice"),
    (9, 30, "以色列的不信", "以色列的不信", "Israel's Unbelief"),
    (10, 1, "因信得救", "因信得救", "Salvation by Faith for All"),
    (10, 14, "信道是从听道来", "信道是從聽道來", "Faith Comes from Hearing"),
    (11, 1, "以色列的余民", "以色列的餘民", "The Remnant of Israel"),
    (11, 11, "外邦人得救", "外邦人得救", "Ingrafted Branches"),
    (11, 25, "以色列必得救", "以色列必得救", "All Israel Will Be Saved"),
    (11, 33, "颂赞神的智慧", "頌讚神的智慧", "Doxology"),
    (12, 1, "活祭与新生", "活祭與新生", "A Living Sacrifice"),
    (12, 9, "爱与服事", "愛與服事", "Love in Action"),
    (13, 1, "顺服掌权者", "順服掌權者", "Submission to Authorities"),
    (13, 8, "彼此相爱", "彼此相愛", "Love Fulfills the Law"),
    (13, 11, "披戴主基督", "披戴主基督", "The Day Is Near"),
    (14, 1, "信心软弱者", "信心軟弱者", "The Weak and the Strong"),
    (14, 13, "不要绊倒弟兄", "不要絆倒弟兄", "Do Not Cause to Stumble"),
    (15, 1, "讨邻舍喜悦", "討鄰舍喜悅", "Pleasing Others, Not Ourselves"),
    (15, 14, "保罗事奉的呼召", "保羅事奉的呼召", "Paul's Apostolic Ministry"),
    (15, 23, "保罗访问罗马的计划", "保羅訪問羅馬的計劃", "Paul's Plan to Visit Rome"),
    (16, 1, "问候众圣徒", "問候眾聖徒", "Personal Greetings"),
    (16, 17, "防备假师傅", "防備假師傅", "Final Warning"),
    (16, 25, "颂赞", "頌讚", "Doxology"),
]

# Psalms is uniquely structured: each chapter IS a self-contained
# psalm with its own theme, so we author exactly one heading per
# psalm at verse 1. Many psalms have ascriptions ("A Psalm of David")
# inside the text; section titles describe the theme instead.
PSALMS: list[tuple[int, int, str, str, str]] = [
    (1, 1, "义人与恶人之路", "義人與惡人之路", "The Way of the Righteous"),
    (2, 1, "弥赛亚君王", "彌賽亞君王", "The Reign of the Lord's Anointed"),
    (3, 1, "晨祷：神是盾牌", "晨禱：神是盾牌", "Morning Prayer of Trust"),
    (4, 1, "晚祷：信靠中安睡", "晚禱：信靠中安睡", "Evening Prayer of Trust"),
    (5, 1, "晨求公义", "晨求公義", "Morning Prayer for Guidance"),
    (6, 1, "求医治与怜悯", "求醫治與憐憫", "Prayer in Time of Distress"),
    (7, 1, "求神为义伸冤", "求神為義伸冤", "A Plea for Justice"),
    (8, 1, "神荣耀与人尊贵", "神榮耀與人尊貴", "God's Glory and Human Dignity"),
    (9, 1, "因神公义而欢呼", "因神公義而歡呼", "Praise for God's Righteous Judgments"),
    (10, 1, "为受压制者求告", "為受壓制者求告", "A Cry Against Wickedness"),
    (11, 1, "信靠耶和华", "信靠耶和華", "Refuge in the LORD"),
    (12, 1, "求神保守纯净的话", "求神保守純淨的話", "A Plea Against Liars"),
    (13, 1, "信徒的呼求", "信徒的呼求", "How Long, O LORD?"),
    (14, 1, "愚顽人说没有神", "愚頑人說沒有神", "The Folly of Atheism"),
    (15, 1, "义人的标志", "義人的標誌", "Who Shall Dwell on Your Holy Hill?"),
    (16, 1, "我所选的产业", "我所選的產業", "My Chosen Portion"),
    (17, 1, "求神鉴察", "求神鑒察", "A Prayer of David"),
    (18, 1, "凯旋之歌", "凱旋之歌", "David's Song of Deliverance"),
    (19, 1, "诸天述说神荣耀", "諸天述說神榮耀", "The Heavens Declare God's Glory"),
    (20, 1, "为君王得胜祈祷", "為君王得勝祈禱", "Trust in the Name of the LORD"),
    (21, 1, "君王凯旋之歌", "君王凱旋之歌", "Praise for Victory"),
    (22, 1, "受苦者的呼求", "受苦者的呼求", "From Suffering to Praise"),
    (23, 1, "耶和华是我的牧者", "耶和華是我的牧者", "The LORD Is My Shepherd"),
    (24, 1, "荣耀的王进入圣殿", "榮耀的王進入聖殿", "The King of Glory"),
    (25, 1, "求引导与饶恕", "求引導與饒恕", "Teach Me Your Paths"),
    (26, 1, "求神鉴察我心", "求神鑒察我心", "Plea of an Innocent Man"),
    (27, 1, "耶和华是我的亮光", "耶和華是我的亮光", "The LORD My Light"),
    (28, 1, "求耶和华回应", "求耶和華回應", "A Cry for Help"),
    (29, 1, "耶和华的声音", "耶和華的聲音", "The Voice of the LORD"),
    (30, 1, "感恩诗", "感恩詩", "Thanksgiving for Deliverance"),
    (31, 1, "投靠耶和华", "投靠耶和華", "Into Your Hand I Commit My Spirit"),
    (32, 1, "认罪得蒙赦免之福", "認罪得蒙赦免之福", "The Joy of Forgiveness"),
    (33, 1, "颂赞创造与守护的神", "頌讚創造與守護的神", "Praise to the Creator"),
    (34, 1, "尝主恩的滋味", "嘗主恩的滋味", "Taste and See the LORD Is Good"),
    (35, 1, "求神为我争战", "求神為我爭戰", "Prayer for Rescue"),
    (36, 1, "神的慈爱", "神的慈愛", "God's Steadfast Love"),
    (37, 1, "不要为作恶者心怀不平", "不要為作惡者心懷不平", "Do Not Fret Because of Evildoers"),
    (38, 1, "认罪与求医治", "認罪與求醫治", "Prayer of a Suffering Penitent"),
    (39, 1, "认识生命的短暂", "認識生命的短暫", "Life Is Fleeting"),
    (40, 1, "新歌颂赞", "新歌頌讚", "A Song of Deliverance"),
    (41, 1, "顾念贫穷人之福", "顧念貧窮人之福", "Blessed Is He Who Considers the Poor"),
    (42, 1, "如鹿渴慕溪水", "如鹿渴慕溪水", "As the Deer Pants for Water"),
    (43, 1, "求神光照我", "求神光照我", "Send Out Your Light"),
    (44, 1, "为国家求恢复", "為國家求恢復", "A Plea for National Restoration"),
    (45, 1, "婚礼之歌", "婚禮之歌", "The Royal Wedding Song"),
    (46, 1, "神是我们的避难所", "神是我們的避難所", "God Is Our Refuge"),
    (47, 1, "万王之王", "萬王之王", "God the King of All Earth"),
    (48, 1, "锡安城的赞美", "錫安城的讚美", "The Glory of Zion"),
    (49, 1, "财富的虚空", "財富的虛空", "The Folly of Trusting in Riches"),
    (50, 1, "真敬拜与心灵之祭", "真敬拜與心靈之祭", "True Worship"),
    (51, 1, "悔罪诗", "悔罪詩", "Create in Me a Clean Heart"),
    (52, 1, "对说谎者的审判", "對說謊者的審判", "Judgment on the Deceitful"),
    (53, 1, "愚顽人说没有神", "愚頑人說沒有神", "The Folly of Atheism"),
    (54, 1, "求神拯救", "求神拯救", "Prayer for Vindication"),
    (55, 1, "被朋友出卖", "被朋友出賣", "Betrayed by a Friend"),
    (56, 1, "在恐惧中信靠神", "在恐懼中信靠神", "In God I Trust"),
    (57, 1, "在患难中坚信", "在患難中堅信", "Steadfast Heart in Trouble"),
    (58, 1, "为不公义祈求", "為不公義祈求", "A Plea Against Injustice"),
    (59, 1, "求神拯救脱离仇敌", "求神拯救脫離仇敵", "Deliverance from Enemies"),
    (60, 1, "国难中的祈求", "國難中的祈求", "Restore Us, O God"),
    (61, 1, "在地极的呼求", "在地極的呼求", "Lead Me to the Rock"),
    (62, 1, "我的心默默无声", "我的心默默無聲", "My Soul Waits in Silence"),
    (63, 1, "切慕神的爱", "切慕神的愛", "My Soul Thirsts for You"),
    (64, 1, "求神保守不被害", "求神保守不被害", "Protection from Hidden Plots"),
    (65, 1, "感恩的颂赞", "感恩的頌讚", "Thanksgiving for Earth's Bounty"),
    (66, 1, "全地颂赞神", "全地頌讚神", "All the Earth Worships God"),
    (67, 1, "万民颂赞神", "萬民頌讚神", "May All Peoples Praise God"),
    (68, 1, "神大胜之歌", "神大勝之歌", "Sing to God, You Kingdoms"),
    (69, 1, "受苦者哀歌", "受苦者哀歌", "Save Me, O God"),
    (70, 1, "急切的求救", "急切的求救", "Urgent Prayer for Help"),
    (71, 1, "老年人的祷告", "老年人的禱告", "Prayer in Old Age"),
    (72, 1, "为君王祈祷", "為君王祈禱", "Prayer for the King"),
    (73, 1, "义人为何受苦", "義人為何受苦", "The Tempting Prosperity of the Wicked"),
    (74, 1, "为圣殿被毁哀求", "為聖殿被毀哀求", "Lament for the Sanctuary"),
    (75, 1, "神是审判者", "神是審判者", "God Is the Judge"),
    (76, 1, "胜利的神", "勝利的神", "God Is Victorious"),
    (77, 1, "黑夜中的安慰", "黑夜中的安慰", "Comfort in Dark Night"),
    (78, 1, "以色列历史的教训", "以色列歷史的教訓", "Tell the Coming Generation"),
    (79, 1, "为耶路撒冷被毁哀痛", "為耶路撒冷被毀哀痛", "Lament Over Jerusalem"),
    (80, 1, "求神再次拯救", "求神再次拯救", "Restore Us, O God"),
    (81, 1, "节期之歌", "節期之歌", "Song for Festival"),
    (82, 1, "审判众神", "審判眾神", "God Stands in Judgment"),
    (83, 1, "求神击败仇敌", "求神擊敗仇敵", "Plea Against Israel's Enemies"),
    (84, 1, "渴慕神的居所", "渴慕神的居所", "How Lovely Is Your Dwelling Place"),
    (85, 1, "求神再施恩典", "求神再施恩典", "Revive Us Again"),
    (86, 1, "求神听祷告", "求神聽禱告", "Hear Me, O LORD"),
    (87, 1, "锡安城的荣耀", "錫安城的榮耀", "The Glory of Zion"),
    (88, 1, "黑夜中的哀歌", "黑夜中的哀歌", "Cry from the Depths"),
    (89, 1, "大卫之约的歌", "大衛之約的歌", "God's Covenant with David"),
    (90, 1, "神是永远的居所", "神是永遠的居所", "God Is Eternal"),
    (91, 1, "至高者的隐密处", "至高者的隱密處", "The Shelter of the Most High"),
    (92, 1, "安息日的颂歌", "安息日的頌歌", "Song for the Sabbath"),
    (93, 1, "耶和华作王", "耶和華作王", "The LORD Reigns"),
    (94, 1, "神为公义伸冤", "神為公義伸冤", "Vengeance Belongs to God"),
    (95, 1, "来敬拜耶和华", "來敬拜耶和華", "Come, Let Us Worship"),
    (96, 1, "向耶和华歌唱", "向耶和華歌唱", "Sing a New Song"),
    (97, 1, "耶和华作王全地欢喜", "耶和華作王全地歡喜", "The LORD Reigns, Let the Earth Rejoice"),
    (98, 1, "新歌颂赞救主", "新歌頌讚救主", "Sing a New Song to the LORD"),
    (99, 1, "圣洁的耶和华", "聖潔的耶和華", "The LORD Our God Is Holy"),
    (100, 1, "感恩之歌", "感恩之歌", "A Psalm of Thanksgiving"),
    (101, 1, "君王立志", "君王立志", "A King's Resolve"),
    (102, 1, "受苦者的祷告", "受苦者的禱告", "Prayer of an Afflicted Man"),
    (103, 1, "颂赞耶和华的恩慈", "頌讚耶和華的恩慈", "Bless the LORD, O My Soul"),
    (104, 1, "颂赞创造主", "頌讚創造主", "Praise to the Creator"),
    (105, 1, "回顾神的大作为", "回顧神的大作為", "Remember His Wondrous Works"),
    (106, 1, "神的恩慈与百姓的悖逆", "神的恩慈與百姓的悖逆", "The LORD's Steadfast Love and Israel's Rebellion"),
    (107, 1, "向耶和华感谢", "向耶和華感謝", "Give Thanks to the LORD"),
    (108, 1, "因神得胜", "因神得勝", "Through God We Shall Do Valiantly"),
    (109, 1, "求神为我伸冤", "求神為我伸冤", "Help Me, O LORD My God"),
    (110, 1, "弥赛亚君王与祭司", "彌賽亞君王與祭司", "The Lord Says to My Lord"),
    (111, 1, "颂赞神的作为", "頌讚神的作為", "Great Are the LORD's Works"),
    (112, 1, "义人之福", "義人之福", "The Blessings of the Righteous"),
    (113, 1, "颂赞至高神", "頌讚至高神", "Praise the Name of the LORD"),
    (114, 1, "出埃及之歌", "出埃及之歌", "When Israel Came Out of Egypt"),
    (115, 1, "唯独神当得颂赞", "唯獨神當得頌讚", "Glory to God Alone"),
    (116, 1, "感谢神的拯救", "感謝神的拯救", "Thanksgiving for Deliverance"),
    (117, 1, "万邦颂赞神", "萬邦頌讚神", "Praise the LORD, All Nations"),
    (118, 1, "感恩诗：耶和华的恩慈永远长存", "感恩詩：耶和華的恩慈永遠長存", "His Steadfast Love Endures Forever"),
    (119, 1, "神话语的诗篇", "神話語的詩篇", "The Word of God: A Meditation"),
    (120, 1, "上行之诗：求神搭救", "上行之詩：求神搭救", "Song of Ascents: Deliver Me"),
    (121, 1, "我的帮助从何而来", "我的幫助從何而來", "My Help Comes from the LORD"),
    (122, 1, "为耶路撒冷祈祷", "為耶路撒冷祈禱", "Pray for the Peace of Jerusalem"),
    (123, 1, "举目望向神", "舉目望向神", "Our Eyes Look to the LORD"),
    (124, 1, "若不是耶和华", "若不是耶和華", "If the LORD Had Not Been on Our Side"),
    (125, 1, "信靠耶和华者", "信靠耶和華者", "Those Who Trust in the LORD"),
    (126, 1, "归回锡安的喜乐", "歸回錫安的喜樂", "Restoration of Zion"),
    (127, 1, "若非耶和华建造", "若非耶和華建造", "Unless the LORD Builds"),
    (128, 1, "敬畏神者之福", "敬畏神者之福", "Blessed Is Everyone Who Fears the LORD"),
    (129, 1, "压迫中蒙保守", "壓迫中蒙保守", "Affliction Cannot Destroy Israel"),
    (130, 1, "深渊中呼求", "深淵中呼求", "Out of the Depths"),
    (131, 1, "心里平静安稳", "心裡平靜安穩", "A Calm and Quiet Soul"),
    (132, 1, "记念大卫之约", "記念大衛之約", "Remember David and His Vow"),
    (133, 1, "弟兄和睦同居", "弟兄和睦同居", "When Brothers Dwell in Unity"),
    (134, 1, "夜间颂赞神", "夜間頌讚神", "Bless the LORD by Night"),
    (135, 1, "颂赞神的奇妙作为", "頌讚神的奇妙作為", "Praise the LORD"),
    (136, 1, "他的慈爱永远长存", "他的慈愛永遠長存", "His Steadfast Love Endures Forever"),
    (137, 1, "在巴比伦哭泣", "在巴比倫哭泣", "By the Waters of Babylon"),
    (138, 1, "感谢神的应允", "感謝神的應允", "Thanksgiving for Answered Prayer"),
    (139, 1, "神无所不知无所不在", "神無所不知無所不在", "God Knows Me Completely"),
    (140, 1, "求脱离恶人", "求脫離惡人", "Deliver Me from Evil Men"),
    (141, 1, "晚祷", "晚禱", "Evening Prayer for Protection"),
    (142, 1, "在洞穴中呼求", "在洞穴中呼求", "Cry from the Cave"),
    (143, 1, "求神教导", "求神教導", "Lead Me in the Way I Should Go"),
    (144, 1, "为得胜祈求", "為得勝祈求", "My Rock and My Fortress"),
    (145, 1, "颂赞君王神", "頌讚君王神", "Great Is the LORD"),
    (146, 1, "颂赞救助者", "頌讚救助者", "Praise the LORD, O My Soul"),
    (147, 1, "颂赞医治者", "頌讚醫治者", "Praise the LORD Who Heals"),
    (148, 1, "万有颂赞神", "萬有頌讚神", "Let All Creation Praise"),
    (149, 1, "向耶和华唱新歌", "向耶和華唱新歌", "Sing a New Song"),
    (150, 1, "用各样乐器赞美神", "用各樣樂器讚美神", "Praise the LORD with All Instruments"),
]

MARK: list[tuple[int, int, str, str, str]] = [
    (1, 1, "施洗约翰预备主道", "施洗約翰預備主道", "John the Baptist Prepares the Way"),
    (1, 9, "耶稣受洗", "耶穌受洗", "The Baptism of Jesus"),
    (1, 12, "耶稣受试探", "耶穌受試探", "The Temptation of Jesus"),
    (1, 14, "耶稣开始传道", "耶穌開始傳道", "Jesus Begins His Ministry"),
    (1, 16, "呼召四个门徒", "呼召四個門徒", "Jesus Calls His First Disciples"),
    (1, 21, "在迦百农会堂赶鬼", "在迦百農會堂趕鬼", "Jesus Casts Out an Evil Spirit"),
    (1, 29, "医治彼得的岳母与众人", "醫治彼得的岳母與眾人", "Jesus Heals Many"),
    (1, 35, "在僻静处祷告", "在僻靜處禱告", "Jesus Prays in a Solitary Place"),
    (1, 40, "洁净长大痲疯", "潔淨長大痲瘋", "Jesus Heals a Man with Leprosy"),
    (2, 1, "医治瘫子", "醫治癱子", "Jesus Heals a Paralyzed Man"),
    (2, 13, "呼召利未", "呼召利未", "The Calling of Levi"),
    (2, 18, "禁食的问题", "禁食的問題", "Question About Fasting"),
    (2, 23, "安息日的主", "安息日的主", "Lord of the Sabbath"),
    (3, 1, "安息日医治枯手者", "安息日醫治枯手者", "Healing on the Sabbath"),
    (3, 7, "海边的群众", "海邊的群眾", "Crowds Follow Jesus"),
    (3, 13, "选立十二使徒", "選立十二使徒", "The Calling of the Twelve"),
    (3, 20, "耶稣与别西卜", "耶穌與別西卜", "Jesus and Beelzebul"),
    (3, 31, "耶稣的真亲属", "耶穌的真親屬", "Jesus' True Family"),
    (4, 1, "撒种的比喻", "撒種的比喻", "The Parable of the Sower"),
    (4, 21, "灯与量度", "燈與量度", "Lamp on a Stand"),
    (4, 26, "种子生长的比喻", "種子生長的比喻", "The Growing Seed"),
    (4, 30, "芥菜种的比喻", "芥菜種的比喻", "The Mustard Seed"),
    (4, 35, "平静风浪", "平靜風浪", "Jesus Calms the Storm"),
    (5, 1, "赶逐群鬼入猪群", "趕逐群鬼入豬群", "Jesus Restores the Demon-Possessed Man"),
    (5, 21, "睚鲁的女儿与血漏妇人", "睚魯的女兒與血漏婦人", "A Dead Girl and a Sick Woman"),
    (6, 1, "在拿撒勒被弃", "在拿撒勒被棄", "A Prophet Without Honor"),
    (6, 7, "差遣十二门徒", "差遣十二門徒", "Jesus Sends Out the Twelve"),
    (6, 14, "施洗约翰被斩", "施洗約翰被斬", "John the Baptist Beheaded"),
    (6, 30, "喂饱五千人", "餵飽五千人", "Jesus Feeds the Five Thousand"),
    (6, 45, "耶稣行走海面", "耶穌行走海面", "Jesus Walks on Water"),
    (6, 53, "在革尼撒勒治病", "在革尼撒勒治病", "Healing the Sick in Gennesaret"),
    (7, 1, "古人的遗传", "古人的遺傳", "Clean and Unclean"),
    (7, 24, "迦南妇人的信心", "迦南婦人的信心", "The Faith of a Syrophoenician Woman"),
    (7, 31, "医治耳聋舌结的人", "醫治耳聾舌結的人", "Jesus Heals a Deaf and Mute Man"),
    (8, 1, "喂饱四千人", "餵飽四千人", "Jesus Feeds the Four Thousand"),
    (8, 11, "求兆头与法利赛人的酵", "求兆頭與法利賽人的酵", "The Yeast of the Pharisees"),
    (8, 22, "医治伯赛大瞎子", "醫治伯賽大瞎子", "Healing the Blind Man at Bethsaida"),
    (8, 27, "彼得的认信", "彼得的認信", "Peter's Confession of Christ"),
    (8, 31, "首次预言受难", "首次預言受難", "Jesus Predicts His Death"),
    (9, 1, "耶稣登山变像", "耶穌登山變像", "The Transfiguration"),
    (9, 14, "医治被鬼附的孩子", "醫治被鬼附的孩子", "Jesus Heals a Boy with an Evil Spirit"),
    (9, 30, "再次预言受难", "再次預言受難", "Jesus Predicts His Death Again"),
    (9, 33, "天国里最大的", "天國裡最大的", "The Greatest in the Kingdom"),
    (9, 38, "不绊倒小子", "不絆倒小子", "Whoever Is Not Against Us"),
    (10, 1, "论离婚", "論離婚", "Jesus Teaches About Divorce"),
    (10, 13, "耶稣祝福小孩", "耶穌祝福小孩", "Jesus Blesses Little Children"),
    (10, 17, "财主的难处", "財主的難處", "The Rich Young Man"),
    (10, 32, "第三次预言受难", "第三次預言受難", "Jesus Predicts His Death a Third Time"),
    (10, 35, "雅各与约翰的请求", "雅各與約翰的請求", "The Request of James and John"),
    (10, 46, "医治瞎子巴底买", "醫治瞎子巴底買", "Blind Bartimaeus Receives Sight"),
    (11, 1, "光荣进入耶路撒冷", "光榮進入耶路撒冷", "The Triumphal Entry"),
    (11, 12, "咒诅无花果树与洁净圣殿", "咒詛無花果樹與潔淨聖殿", "Cursing the Fig Tree and Clearing the Temple"),
    (11, 27, "盘问耶稣的权柄", "盤問耶穌的權柄", "The Authority of Jesus Questioned"),
    (12, 1, "凶恶园户的比喻", "兇惡園戶的比喻", "The Parable of the Tenants"),
    (12, 13, "纳税给凯撒", "納稅給凱撒", "Paying Taxes to Caesar"),
    (12, 18, "复活的问题", "復活的問題", "Marriage at the Resurrection"),
    (12, 28, "最大的诫命", "最大的誡命", "The Greatest Commandment"),
    (12, 41, "穷寡妇的奉献", "窮寡婦的奉獻", "The Widow's Offering"),
    (13, 1, "末世的预兆", "末世的預兆", "Signs of the End of the Age"),
    (13, 32, "无人知道那日子", "無人知道那日子", "The Day and Hour Unknown"),
    (14, 1, "杀害耶稣的阴谋", "殺害耶穌的陰謀", "The Plot Against Jesus"),
    (14, 3, "在伯大尼受膏", "在伯大尼受膏", "Anointed at Bethany"),
    (14, 12, "最后的晚餐", "最後的晚餐", "The Last Supper"),
    (14, 32, "客西马尼园祷告", "客西馬尼園禱告", "Gethsemane"),
    (14, 43, "耶稣被捕", "耶穌被捕", "Jesus Arrested"),
    (14, 53, "公会受审", "公會受審", "Before the Sanhedrin"),
    (14, 66, "彼得三次否认", "彼得三次否認", "Peter Disowns Jesus"),
    (15, 1, "彼拉多前受审", "彼拉多前受審", "Jesus Before Pilate"),
    (15, 16, "戏弄与定罪", "戲弄與定罪", "The Soldiers Mock Jesus"),
    (15, 21, "钉十字架", "釘十字架", "The Crucifixion"),
    (15, 33, "耶稣之死", "耶穌之死", "The Death of Jesus"),
    (15, 42, "耶稣被埋葬", "耶穌被埋葬", "The Burial of Jesus"),
    (16, 1, "耶稣复活", "耶穌復活", "Jesus Has Risen"),
    (16, 9, "向门徒显现", "向門徒顯現", "Jesus Appears to His Disciples"),
    (16, 14, "大使命", "大使命", "The Great Commission"),
]

ACTS: list[tuple[int, int, str, str, str]] = [
    (1, 1, "耶稣升天前的应许", "耶穌升天前的應許", "Jesus Taken Up Into Heaven"),
    (1, 12, "选立马提亚", "選立馬提亞", "Matthias Chosen to Replace Judas"),
    (2, 1, "圣灵降临", "聖靈降臨", "The Holy Spirit Comes at Pentecost"),
    (2, 14, "彼得的讲道", "彼得的講道", "Peter Addresses the Crowd"),
    (2, 42, "教会团契生活", "教會團契生活", "The Fellowship of the Believers"),
    (3, 1, "美门外医治瘸子", "美門外醫治瘸子", "Peter Heals the Lame Beggar"),
    (3, 11, "彼得在所罗门廊讲道", "彼得在所羅門廊講道", "Peter Speaks at Solomon's Colonnade"),
    (4, 1, "彼得与约翰被审", "彼得與約翰被審", "Peter and John Before the Sanhedrin"),
    (4, 23, "信徒祷告求胆量", "信徒禱告求膽量", "The Believers' Prayer"),
    (4, 32, "信徒凡物公用", "信徒凡物公用", "The Believers Share Their Possessions"),
    (5, 1, "亚拿尼亚与撒非喇", "亞拿尼亞與撒非喇", "Ananias and Sapphira"),
    (5, 12, "使徒行神迹", "使徒行神蹟", "The Apostles Heal Many"),
    (5, 17, "使徒被囚与被释", "使徒被囚與被釋", "The Apostles Persecuted"),
    (6, 1, "选立七位执事", "選立七位執事", "The Choosing of the Seven"),
    (6, 8, "司提反被捉拿", "司提反被捉拿", "Stephen Seized"),
    (7, 1, "司提反的讲道", "司提反的講道", "Stephen's Speech"),
    (7, 54, "司提反殉道", "司提反殉道", "The Stoning of Stephen"),
    (8, 1, "耶路撒冷教会受逼迫", "耶路撒冷教會受逼迫", "The Church Persecuted and Scattered"),
    (8, 4, "腓利在撒玛利亚传道", "腓利在撒瑪利亞傳道", "Philip in Samaria"),
    (8, 9, "行邪术的西门", "行邪術的西門", "Simon the Sorcerer"),
    (8, 26, "腓利与埃塞俄比亚太监", "腓利與埃塞俄比亞太監", "Philip and the Ethiopian"),
    (9, 1, "扫罗大马士革路上的归正", "掃羅大馬士革路上的歸正", "Saul's Conversion"),
    (9, 19, "扫罗在大马士革与耶路撒冷传道", "掃羅在大馬士革與耶路撒冷傳道", "Saul Begins Preaching"),
    (9, 32, "彼得医治以尼雅与多加复活", "彼得醫治以尼雅與多加復活", "Aeneas and Dorcas"),
    (10, 1, "哥尼流的异象", "哥尼流的異象", "Cornelius Calls for Peter"),
    (10, 9, "彼得的异象", "彼得的異象", "Peter's Vision"),
    (10, 23, "彼得到哥尼流家", "彼得到哥尼流家", "Peter at Cornelius's House"),
    (10, 44, "外邦人受圣灵", "外邦人受聖靈", "The Holy Spirit Comes Upon the Gentiles"),
    (11, 1, "彼得在耶路撒冷的报告", "彼得在耶路撒冷的報告", "Peter Explains His Actions"),
    (11, 19, "安提阿教会兴起", "安提阿教會興起", "The Church in Antioch"),
    (12, 1, "希律杀害雅各囚禁彼得", "希律殺害雅各囚禁彼得", "Peter's Miraculous Escape"),
    (12, 19, "希律的死亡", "希律的死亡", "Herod's Death"),
    (13, 1, "保罗与巴拿巴受差遣", "保羅與巴拿巴受差遣", "Barnabas and Saul Sent Off"),
    (13, 4, "在居比路传道", "在居比路傳道", "On Cyprus"),
    (13, 13, "在彼西底安提阿讲道", "在彼西底安提阿講道", "In Pisidian Antioch"),
    (14, 1, "在以哥念", "在以哥念", "In Iconium"),
    (14, 8, "在路司得医治瘸子", "在路司得醫治瘸子", "In Lystra and Derbe"),
    (14, 21, "返回安提阿", "返回安提阿", "The Return to Antioch"),
    (15, 1, "耶路撒冷会议", "耶路撒冷會議", "The Council at Jerusalem"),
    (15, 22, "致外邦信徒的信", "致外邦信徒的信", "The Council's Letter"),
    (15, 36, "保罗与巴拿巴分道", "保羅與巴拿巴分道", "Disagreement Between Paul and Barnabas"),
    (16, 1, "提摩太加入", "提摩太加入", "Timothy Joins Paul and Silas"),
    (16, 6, "马其顿的异象", "馬其頓的異象", "Paul's Vision of the Man of Macedonia"),
    (16, 11, "吕底亚信主", "呂底亞信主", "Lydia's Conversion in Philippi"),
    (16, 16, "在腓立比下监", "在腓立比下監", "Paul and Silas in Prison"),
    (17, 1, "在帖撒罗尼迦", "在帖撒羅尼迦", "In Thessalonica"),
    (17, 10, "在庇哩亚", "在庇哩亞", "In Berea"),
    (17, 16, "保罗在雅典", "保羅在雅典", "In Athens"),
    (17, 22, "亚略巴古的讲道", "亞略巴古的講道", "Paul's Speech at the Areopagus"),
    (18, 1, "在哥林多", "在哥林多", "In Corinth"),
    (18, 18, "回安提阿与第三次旅程", "回安提阿與第三次旅程", "Priscilla, Aquila, and Apollos"),
    (19, 1, "在以弗所", "在以弗所", "Paul in Ephesus"),
    (19, 11, "保罗的非常神迹", "保羅的非常神蹟", "Extraordinary Miracles"),
    (19, 23, "以弗所的暴动", "以弗所的暴動", "The Riot in Ephesus"),
    (20, 1, "经过马其顿与希腊", "經過馬其頓與希臘", "Through Macedonia and Greece"),
    (20, 7, "在特罗亚使犹推古复活", "在特羅亞使猶推古復活", "Eutychus Raised in Troas"),
    (20, 17, "保罗在米利都的告别", "保羅在米利都的告別", "Paul's Farewell to the Ephesian Elders"),
    (21, 1, "前往耶路撒冷", "前往耶路撒冷", "On to Jerusalem"),
    (21, 17, "保罗到耶路撒冷", "保羅到耶路撒冷", "Paul's Arrival at Jerusalem"),
    (21, 27, "保罗被捕", "保羅被捕", "Paul Arrested"),
    (22, 1, "保罗在群众前的辩论", "保羅在群眾前的辯論", "Paul Speaks to the Crowd"),
    (22, 22, "保罗与罗马公民身份", "保羅與羅馬公民身份", "Paul the Roman Citizen"),
    (23, 1, "保罗在公会前受审", "保羅在公會前受審", "Before the Sanhedrin"),
    (23, 12, "杀害保罗的阴谋", "殺害保羅的陰謀", "The Plot to Kill Paul"),
    (23, 23, "保罗被解送至该撒利亚", "保羅被解送至該撒利亞", "Paul Transferred to Caesarea"),
    (24, 1, "在腓力斯前受审", "在腓力斯前受審", "The Trial Before Felix"),
    (25, 1, "在非斯都前受审", "在非斯都前受審", "Paul's Trial Before Festus"),
    (25, 13, "亚基帕王听保罗的案", "亞基帕王聽保羅的案", "Festus Consults King Agrippa"),
    (26, 1, "保罗在亚基帕前的辩论", "保羅在亞基帕前的辯論", "Paul Before Agrippa"),
    (27, 1, "前往罗马的航程", "前往羅馬的航程", "Paul Sails for Rome"),
    (27, 13, "海上的风暴", "海上的風暴", "The Storm"),
    (27, 27, "船毁与平安上岸", "船毀與平安上岸", "The Shipwreck"),
    (28, 1, "在马耳他岛", "在馬耳他島", "Ashore on Malta"),
    (28, 11, "保罗到罗马", "保羅到羅馬", "Paul's Arrival at Rome"),
    (28, 17, "保罗在罗马传道", "保羅在羅馬傳道", "Paul Preaches at Rome Under Guard"),
]


# --------------------------------------------------------------------
# Section-level CONTEXT (optional 1-2 sentences of background).
#
# Keyed by (book, chapter, verse) → (simplified, traditional, english).
# Authored only for high-impact / commonly-misunderstood sections —
# the goal is to give a reader who lands here cold enough setting
# to make sense of what they're about to read.
#
# Entries that don't appear here render with a title alone.
# --------------------------------------------------------------------
SECTION_CONTEXTS: dict[tuple[str, int, int], tuple[str, str, str]] = {
    # ── Genesis ──
    ("Genesis", 1, 1): (
        "圣经的开篇，回应人类最古老的问题：宇宙、生命、人类从何而来？",
        "聖經的開篇，回應人類最古老的問題：宇宙、生命、人類從何而來？",
        "The Bible opens with the most fundamental question: where did everything come from? The answer — God spoke it into being.",
    ),
    ("Genesis", 2, 4): (
        "镜头从宇宙拉近到伊甸园：人是按神的形象造的，被安置在乐园中、与神同在。",
        "鏡頭從宇宙拉近到伊甸園：人是按神的形象造的，被安置在樂園中、與神同在。",
        "The camera zooms from cosmos to garden. The first humans are made in God's image and placed in fellowship with him.",
    ),
    ("Genesis", 3, 1): (
        "人类故事的转折：受造物的悖逆，破坏了与神、与人、与受造界的关系。",
        "人類故事的轉折：受造物的悖逆，破壞了與神、與人、與受造界的關係。",
        "The pivot of human history: a single act of distrust fractures every relationship — with God, with each other, with creation itself.",
    ),
    ("Genesis", 6, 9): (
        "人类败坏到极点，神选择以洪水洗净大地，但通过挪亚保留人类的指望。",
        "人類敗壞到極點，神選擇以洪水洗淨大地，但通過挪亞保留人類的指望。",
        "Mankind's wickedness has filled the earth. God will reset creation through a flood — but preserve a remnant through one righteous family.",
    ),
    ("Genesis", 11, 1): (
        "人类企图自筑通天高塔，宣告自主与团结，却招致语言的混乱与分散。",
        "人類企圖自築通天高塔，宣告自主與團結，卻招致語言的混亂與分散。",
        "Humanity attempts to ascend to heaven by their own strength, defying God's command to fill the earth. The scattering of languages still shapes our world.",
    ),
    ("Genesis", 12, 1): (
        "圣经核心的转折：神呼召一个人——亚伯兰，借他祝福万族。这是救赎史的开端。",
        "聖經核心的轉折：神呼召一個人——亞伯蘭，藉他祝福萬族。這是救贖史的開端。",
        "The hinge of redemption history. God calls one man, Abram, promising to bless every nation through his line — a promise the rest of Scripture traces.",
    ),
    ("Genesis", 22, 1): (
        "亚伯拉罕信心的最终试炼，预表父神献子救赎人类的伟大爱。",
        "亞伯拉罕信心的最終試煉，預表父神獻子救贖人類的偉大愛。",
        "Abraham's ultimate test of faith. The scene of a father offering his only son on Mount Moriah foreshadows what God himself will one day do.",
    ),
    ("Genesis", 37, 12): (
        "约瑟被亲兄弟出卖到埃及，神却用人的恶意成就拯救——日后保全了雅各家族。",
        "約瑟被親兄弟出賣到埃及，神卻用人的惡意成就拯救——日後保全了雅各家族。",
        "Sold by his own brothers into slavery, Joseph's story shows God working through human evil to preserve the covenant family.",
    ),
    ("Genesis", 50, 15): (
        "约瑟说：「你们的意思是要害我，但神的意思原是好的。」饶恕的最高典范。",
        "約瑟說：「你們的意思是要害我，但神的意思原是好的。」饒恕的最高典範。",
        "Joseph's famous declaration — 'You meant evil against me, but God meant it for good' — reframes decades of suffering as part of a redemptive plan.",
    ),
    # ── Psalms (selected key psalms) ──
    ("Psalms", 1, 1): (
        "诗篇的开篇，定下整卷书的基调：默想神律法的人有福，恶人必如糠秕被风吹散。",
        "詩篇的開篇，定下整卷書的基調：默想神律法的人有福，惡人必如糠秕被風吹散。",
        "The doorway to the Psalms. Two paths, two destinies — and the wise are those who delight in God's instruction day and night.",
    ),
    ("Psalms", 2, 1): (
        "弥赛亚君王诗篇，被新约多次引用，描绘列国敌挡神受膏者的徒然。",
        "彌賽亞君王詩篇，被新約多次引用，描繪列國敵擋神受膏者的徒然。",
        "A messianic coronation psalm quoted repeatedly in the New Testament. The kings of earth rage in vain against the Anointed One God himself has installed.",
    ),
    ("Psalms", 22, 1): (
        "「我的神！我的神！为什么离弃我？」——耶稣在十字架上引用的诗篇，预表受苦的弥赛亚。",
        "「我的神！我的神！為什麼離棄我？」——耶穌在十字架上引用的詩篇，預表受苦的彌賽亞。",
        "The cry Jesus echoed from the cross. Centuries before Calvary, David describes pierced hands and feet, mocking onlookers, and gambling for clothing.",
    ),
    ("Psalms", 23, 1): (
        "全圣经最为人熟知的诗篇之一。在死荫幽谷与生命平安之间，宣告耶和华是牧者。",
        "全聖經最為人熟知的詩篇之一。在死蔭幽谷與生命平安之間，宣告耶和華是牧者。",
        "Perhaps the most beloved chapter in all Scripture. Through danger, fear, and even the valley of death's shadow, the believer is shepherded — not abandoned.",
    ),
    ("Psalms", 51, 1): (
        "大卫与拔示巴犯罪后的悔罪诗。每个跌倒、却仍盼望神饶恕者都能在此找到自己。",
        "大衛與拔示巴犯罪後的悔罪詩。每個跌倒、卻仍盼望神饒恕者都能在此找到自己。",
        "David's cry of repentance after his sin with Bathsheba. Every fallen believer who has dared to hope in God's mercy finds words here.",
    ),
    ("Psalms", 119, 1): (
        "圣经中最长的一章。22 个段落，按希伯来字母为顺序，全篇默想神的话语。",
        "聖經中最長的一章。22 個段落，按希伯來字母為順序，全篇默想神的話語。",
        "The longest chapter in the Bible — 176 verses in 22 alphabetic sections — a sustained meditation on the beauty and life-giving power of God's word.",
    ),
    ("Psalms", 139, 1): (
        "对神无所不知、无所不在最深刻的反思。即使到地极、到阴间，神仍紧紧握住我们。",
        "對神無所不知、無所不在最深刻的反思。即使到地極、到陰間，神仍緊緊握住我們。",
        "The Bible's deepest meditation on divine omniscience. There is no height, depth, or darkness where God's hand cannot reach the believer.",
    ),
    # ── Matthew ──
    ("Matthew", 1, 1): (
        "马太福音以耶稣的家谱开篇，证明祂是亚伯拉罕之子（应许）与大卫之子（君王）。",
        "馬太福音以耶穌的家譜開篇，證明祂是亞伯拉罕之子（應許）與大衛之子（君王）。",
        "Matthew opens with a genealogy because identity matters. Jesus is shown to fulfill both the Abrahamic promise of blessing and the Davidic promise of an eternal King.",
    ),
    ("Matthew", 5, 1): (
        "耶稣事工初期最重要的讲论，颠覆人对「有福」的理解：贫穷、哀恸、饥渴慕义之人——这些人有福了。",
        "耶穌事工初期最重要的講論，顛覆人對「有福」的理解：貧窮、哀慟、飢渴慕義之人——這些人有福了。",
        "Jesus' foundational sermon, delivered early in his Galilean ministry. The Beatitudes invert worldly values — calling the poor in spirit, the mourners, and the persecuted 'blessed'.",
    ),
    ("Matthew", 6, 9): (
        "耶稣亲自教导门徒祷告。每一句都是天国子民与天父关系的核心。",
        "耶穌親自教導門徒禱告。每一句都是天國子民與天父關係的核心。",
        "The pattern Jesus gave his disciples for prayer. Every line is a window into the heart of how citizens of the kingdom relate to their Father.",
    ),
    ("Matthew", 16, 13): (
        "彼得在该撒利亚腓立比认信耶稣是基督，是神的儿子——四福音事工的转折点。",
        "彼得在該撒利亞腓立比認信耶穌是基督，是神的兒子——四福音事工的轉折點。",
        "Peter's confession at Caesarea Philippi is the hinge of all four Gospels. After this moment, Jesus begins openly teaching that he must die and rise again.",
    ),
    ("Matthew", 17, 1): (
        "耶稣在山上变像，向三位门徒短暂显出神性的荣光，证实祂超越摩西与以利亚的权柄。",
        "耶穌在山上變像，向三位門徒短暫顯出神性的榮光，證實祂超越摩西與以利亞的權柄。",
        "On a mountain, Jesus' divine glory briefly breaks through his humanity. Moses (Law) and Elijah (Prophets) appear with him — both pointing to the One greater than themselves.",
    ),
    ("Matthew", 26, 17): (
        "耶稣最后的逾越节晚餐，设立圣餐礼。祂的身体与血即将作为新约的祭。",
        "耶穌最後的逾越節晚餐，設立聖餐禮。祂的身體與血即將作為新約的祭。",
        "Jesus' final Passover. By breaking bread and pouring the cup, he institutes the new covenant in his body and blood — a memorial the church keeps to this day.",
    ),
    ("Matthew", 26, 36): (
        "客西马尼园的祷告：耶稣以人性面对受难的恐惧，仍顺服天父的旨意。",
        "客西馬尼園的禱告：耶穌以人性面對受難的恐懼，仍順服天父的旨意。",
        "In Gethsemane, the fully human Jesus wrestles with the cup before him — and submits to the Father's will. The hour of redemption begins here.",
    ),
    ("Matthew", 27, 32): (
        "钉十字架——历史上最公开的处决。圣经四卷福音以此为高峰，用最少的笔墨描述最大的事件。",
        "釘十字架——歷史上最公開的處決。聖經四卷福音以此為高峰，用最少的筆墨描述最大的事件。",
        "The crucifixion — the most public execution in history. The Gospels treat it with strange restraint, letting the event speak for itself.",
    ),
    ("Matthew", 28, 1): (
        "整本新约的高潮：耶稣从死里复活，证实祂的牺牲获蒙天父悦纳，开启永恒的盼望。",
        "整本新約的高潮：耶穌從死裡復活，證實祂的犧牲獲蒙天父悅納，開啟永恆的盼望。",
        "The climax of the New Testament. The resurrection vindicates Jesus' atoning sacrifice and inaugurates the hope of eternal life for all who trust him.",
    ),
    ("Matthew", 28, 16): (
        "复活的主向门徒颁布大使命：去使万民作主门徒。这是教会两千年宣教的根基。",
        "復活的主向門徒頒布大使命：去使萬民作主門徒。這是教會兩千年宣教的根基。",
        "The Great Commission. The risen Jesus sends his disciples to all nations — the marching orders that have driven 2,000 years of Christian mission.",
    ),
    # ── Mark ──
    ("Mark", 1, 1): (
        "马可福音节奏最快、最具行动感。开篇即宣告：耶稣是神的儿子。",
        "馬可福音節奏最快、最具行動感。開篇即宣告：耶穌是神的兒子。",
        "Mark moves at breakneck speed — the shortest, most action-packed Gospel. The opening line states the thesis: Jesus is the Son of God.",
    ),
    ("Mark", 4, 35): (
        "耶稣平静狂风巨浪，门徒第一次震惊地问：「这到底是谁？连风和海也听从他。」",
        "耶穌平靜狂風巨浪，門徒第一次震驚地問：「這到底是誰？連風和海也聽從他。」",
        "Jesus stills a storm. The terrified disciples ask the question Mark wants every reader to ask: 'Who is this, that even the wind and sea obey him?'",
    ),
    ("Mark", 8, 27): (
        "彼得的认信——马可福音的中心。前八章讲祂是谁；后八章讲祂为何而来（受难）。",
        "彼得的認信——馬可福音的中心。前八章講祂是誰；後八章講祂為何而來（受難）。",
        "Mark's hinge. The first eight chapters answer 'Who is Jesus?' Peter's confession unlocks the second half: 'What did he come to do?' — to suffer and die.",
    ),
    # ── John ──
    ("John", 1, 1): (
        "约翰福音以创世记为镜像开篇——那位在起初就有的「道」，如今成了肉身。",
        "約翰福音以創世記為鏡像開篇——那位在起初就有的「道」，如今成了肉身。",
        "John mirrors Genesis with his opening: 'In the beginning was the Word.' The eternal Logos — through whom all things were made — has now become flesh.",
    ),
    ("John", 3, 1): (
        "尼哥底母夜访耶稣，听见震撼一生的话：「人若不重生，就不能见神的国。」",
        "尼哥底母夜訪耶穌，聽見震撼一生的話：「人若不重生，就不能見神的國。」",
        "A leading Pharisee comes by night for an encounter that contains the most-quoted verse in the Bible (3:16) — and a teaching that has changed millions of lives.",
    ),
    ("John", 4, 1): (
        "耶稣超越种族、性别、宗教的偏见，向一位撒玛利亚妇女启示自己是「活水」。",
        "耶穌超越種族、性別、宗教的偏見，向一位撒瑪利亞婦女啟示自己是「活水」。",
        "Jesus crosses every boundary — racial, gender, religious — to offer 'living water' to a Samaritan woman at a well. By chapter's end, her village believes.",
    ),
    ("John", 11, 1): (
        "约翰福音最戏剧性的神迹：耶稣使死了四天的拉撒路复活，预先彰显祂自己的复活权能。",
        "約翰福音最戲劇性的神蹟：耶穌使死了四天的拉撒路復活，預先彰顯祂自己的復活權能。",
        "The most dramatic miracle in John's Gospel. Raising Lazarus — dead four days — both ignites Jesus' final week and previews his own resurrection.",
    ),
    ("John", 13, 1): (
        "最后晚餐前，耶稣亲自为门徒洗脚——颠覆所有关于权力和事奉的世俗观念。",
        "最後晚餐前，耶穌親自為門徒洗腳——顛覆所有關於權力和事奉的世俗觀念。",
        "On the night of his betrayal, the King washes his disciples' feet — overturning every worldly notion of power and service in a single act.",
    ),
    ("John", 17, 1): (
        "耶稣大祭司的祷告——为门徒、为后世信徒祈求，是新约最深的祷告。",
        "耶穌大祭司的禱告——為門徒、為後世信徒祈求，是新約最深的禱告。",
        "Jesus' high priestly prayer — interceding for his disciples and for every believer who would come after them. The deepest prayer in the New Testament.",
    ),
    ("John", 20, 1): (
        "空坟墓——基督教信仰的根基。约翰冷静地记录他亲眼所见的细节。",
        "空墳墓——基督教信仰的根基。約翰冷靜地記錄他親眼所見的細節。",
        "The empty tomb — the foundation of the Christian faith. John records the details of what he himself saw with the precision of an eyewitness.",
    ),
    # ── Acts ──
    ("Acts", 1, 1): (
        "使徒行传是路加福音的续集——耶稣升天后，圣灵借门徒展开教会的扩展史。",
        "使徒行傳是路加福音的續集——耶穌升天後，聖靈藉門徒展開教會的擴展史。",
        "Acts is volume two of Luke's Gospel. After Jesus' ascension, the Spirit propels his followers from Jerusalem to Rome — and the church begins.",
    ),
    ("Acts", 2, 1): (
        "五旬节圣灵降临，应验耶稣的应许。从这一刻起，教会诞生，不分种族、地域。",
        "五旬節聖靈降臨，應驗耶穌的應許。從這一刻起，教會誕生，不分種族、地域。",
        "Pentecost fulfills Jesus' promise. The Spirit descends, the Gospel is preached in many tongues, and 3,000 are added to the church in a single day.",
    ),
    ("Acts", 9, 1): (
        "教会最大的逼迫者扫罗（保罗）在大马士革路上遇见复活的主——历史的转折点。",
        "教會最大的逼迫者掃羅（保羅）在大馬士革路上遇見復活的主——歷史的轉折點。",
        "The church's chief persecutor encounters the risen Christ on the Damascus road. Saul of Tarsus becomes Paul the apostle — a hinge moment in history.",
    ),
    ("Acts", 10, 1): (
        "彼得到外邦百夫长哥尼流家——福音正式打开外邦的门。",
        "彼得到外邦百夫長哥尼流家——福音正式打開外邦的門。",
        "Through twin visions, God orchestrates Peter's visit to the Gentile centurion Cornelius. The Gospel is officially opened to the nations.",
    ),
    ("Acts", 15, 1): (
        "耶路撒冷会议：教会决定外邦信徒不必受割礼。这定义了教会的合一与多元。",
        "耶路撒冷會議：教會決定外邦信徒不必受割禮。這定義了教會的合一與多元。",
        "The Jerusalem Council settles the church's most divisive question: Gentile believers do not have to keep the Mosaic law to be saved. The unity of the church is preserved.",
    ),
    ("Acts", 17, 22): (
        "保罗在雅典亚略巴古的讲道——向异教知识分子宣讲创造主、悔改与复活。",
        "保羅在雅典亞略巴古的講道——向異教知識分子宣講創造主、悔改與復活。",
        "Paul's masterful sermon to Greek philosophers at the Areopagus. He starts with their own poets and altars and ends with the resurrection of Christ.",
    ),
    # ── Romans ──
    ("Romans", 1, 16): (
        "保罗的论文起点：「我不以福音为耻」。整卷书是这一句的展开。",
        "保羅的論文起點：「我不以福音為恥」。整卷書是這一句的展開。",
        "Paul's thesis: 'I am not ashamed of the Gospel — it is the power of God for salvation.' Everything in Romans unpacks this single sentence.",
    ),
    ("Romans", 3, 21): (
        "罗马书的核心：因信称义。神在律法以外向世人显明祂自己的义。",
        "羅馬書的核心：因信稱義。神在律法以外向世人顯明祂自己的義。",
        "The heart of Romans — and arguably the heart of the Gospel. God's righteousness is revealed apart from the law and received through faith in Christ alone.",
    ),
    ("Romans", 5, 1): (
        "因信称义的果效：与神和好、得享平安、进入恩典、夸耀盼望——也包括苦难带来的成长。",
        "因信稱義的果效：與神和好、得享平安、進入恩典、誇耀盼望——也包括苦難帶來的成長。",
        "The fruits of justification: peace with God, access to grace, hope, and the strange gift of suffering — which produces the very character we long for.",
    ),
    ("Romans", 8, 1): (
        "罗马书的最高峰之一。「在基督耶稣里的就不定罪了」——并以「万事互相效力」收尾。",
        "羅馬書的最高峰之一。「在基督耶穌裡的就不定罪了」——並以「萬事互相效力」收尾。",
        "One of the highest peaks in Scripture. 'No condemnation' opens the chapter; 'no separation' closes it. In between: the Spirit, suffering, and unshakable hope.",
    ),
    ("Romans", 12, 1): (
        "保罗从「神为我们做了什么」转到「我们当如何回应」——将身体献作活祭，是合理的事奉。",
        "保羅從「神為我們做了什麼」轉到「我們當如何回應」——將身體獻作活祭，是合理的事奉。",
        "The pivot from doctrine to ethics. In view of God's mercy, we offer ourselves as living sacrifices — and the rest of life flows from that response.",
    ),
}


def _set_for(book_data: list[tuple[int, int, str, str, str]], lang: str, book_name: str) -> dict:
    """Group authored entries by chapter for one language. Adds an
    optional `context` field when SECTION_CONTEXTS has a matching entry."""
    out: dict[str, list[dict]] = {}
    for ch, vs, simp, trad, en in book_data:
        title = {"hans": simp, "hant": trad, "en": en}[lang]
        item: dict = {"verse": vs, "title": title}
        ctx = SECTION_CONTEXTS.get((book_name, ch, vs))
        if ctx is not None:
            ctx_text = {"hans": ctx[0], "hant": ctx[1], "en": ctx[2]}[lang]
            item["context"] = ctx_text
        out.setdefault(str(ch), []).append(item)
    # Sort each chapter's entries by verse for deterministic output.
    for ch in out:
        out[ch].sort(key=lambda e: e["verse"])
    return out


def main() -> int:
    books_data = {
        "Genesis": GENESIS,
        "Psalms": PSALMS,
        "Matthew": MATTHEW,
        "Mark": MARK,
        "John": JOHN,
        "Acts": ACTS,
        "Romans": ROMANS,
    }

    payload = {
        "_meta": {
            "version": 1,
            "books": list(books_data.keys()),
            "generatedAt": _dt.datetime.now(_dt.timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "description": (
                "Section / paragraph titles. Loaded by SectionTitleService and "
                "rendered above the matched verse in the reading pane. Three "
                "title sets in this Phase-1 file: cuv (simplified), cuv-tr "
                "(traditional), english-classic (English). The version-to-set "
                "mapping lives in lib/constants/section_title_map.dart."
            ),
        },
        "sets": {
            "cuv": {b: _set_for(d, "hans", b) for b, d in books_data.items()},
            "cuv-tr": {b: _set_for(d, "hant", b) for b, d in books_data.items()},
            "english-classic": {b: _set_for(d, "en", b) for b, d in books_data.items()},
        },
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    total = sum(len(d) for d in books_data.values())
    print(
        f"Wrote {total} titles × 3 languages → "
        f"{OUT} ({os.path.getsize(OUT)} bytes)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
