#!/usr/bin/env python3
"""Refresh `assets/songs.json` from the published yswords-data dataset.

The app bundles a snapshot of the song catalogue so the directory works
offline and on first launch. That snapshot used to be produced by
running `scripts/sync_songs.py` here — re-fetching all four church
sites a second time, independently of the run that produced the
published dataset.

Two problems with that:

  • It hammered the churches' servers twice per refresh. On
    2026-08-09 fydt.org stopped answering entirely mid-session after
    this repo and yswords-data had both been scraping it; a small
    church box does not owe us that traffic.
  • The two copies could drift. They are generated by the same script,
    but from separate runs against a live upstream, so a site being
    briefly down during one of them produced a bundled snapshot that
    disagreed with what the app fetches at runtime.

yswords-data is the source of truth (it validates against a JSON
Schema and runs its own tests before publishing), so the snapshot is
now simply a copy of it.

`scripts/sync_songs.py` stays in this repo for local experimentation
and as the reference implementation, but the bundled asset should be
refreshed with THIS script.

Usage:
    python3 scripts/pull_songs_snapshot.py
    python3 scripts/pull_songs_snapshot.py --url https://…/songs.json
"""

import argparse
import json
import os
import sys
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO_ROOT, 'assets', 'songs.json')
DEFAULT_URL = 'https://yswords-data.netlify.app/data/songs.json'

# A published catalogue that fails these is a bad publish, not new
# news — writing it into the bundle would ship a broken directory to
# every user who is offline or on first launch.
REQUIRED_SOURCES = {'fydt', 'cdc', 'cgdc', 'cahaya'}
MIN_SONGS = 400


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--url', default=DEFAULT_URL)
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    print(f'Fetching {args.url} …')
    req = urllib.request.Request(
        args.url, headers={'User-Agent': 'YsWordsSnapshotPull/1.0'})
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read()

    doc = json.loads(raw)
    songs = doc.get('songs') or []
    meta = doc.get('_meta') or {}
    by_source = meta.get('bySource') or {}

    problems = []
    if len(songs) < MIN_SONGS:
        problems.append(f'only {len(songs)} songs (expected ≥{MIN_SONGS})')
    if meta.get('count') != len(songs):
        problems.append(
            f"_meta.count {meta.get('count')} != {len(songs)} rows")
    missing = REQUIRED_SOURCES - set(by_source)
    if missing:
        problems.append(f'missing sources: {sorted(missing)}')
    for source in REQUIRED_SOURCES & set(by_source):
        if by_source[source] < 10:
            problems.append(f'{source} has only {by_source[source]} songs')

    if problems:
        print('ERROR: refusing to write a suspect snapshot:',
              file=sys.stderr)
        for p in problems:
            print(f'  • {p}', file=sys.stderr)
        return 1

    print(f'  {len(songs)} songs · {by_source}')
    print(f'  generated {meta.get("generatedAt")}')

    if args.dry_run:
        print('(dry run — nothing written)')
        return 0

    with open(TARGET, 'wb') as f:
        f.write(raw)
    print(f'✓ wrote {TARGET} ({len(raw):,} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
