#!/usr/bin/env python3
"""Refresh `assets/songs.json` from the published yswords-data dataset.

The app bundles a snapshot of the song catalogue so the directory works
offline and on first launch. That snapshot used to be produced by
running `scripts/sync_songs.py` here — re-fetching all four church
sites a second time, independently of the run that produced the
published dataset.

Two problems with that:

  • It hammered the churches' servers twice per refresh. On
    2026-08-09 fydt.org stopped answering entirely mid-session after
    this repo and yswords-data had both been scraping it; a small
    church box does not owe us that traffic.
  • The two copies could drift. They are generated by the same script,
    but from separate runs against a live upstream, so a site being
    briefly down during one of them produced a bundled snapshot that
    disagreed with what the app fetches at runtime.

yswords-data is the source of truth (it validates against a JSON
Schema and runs its own tests before publishing), so the snapshot is
now simply a copy of it.

`scripts/sync_songs.py` stays in this repo for local experimentation
and as the reference implementation, but the bundled asset should be
refreshed with THIS script.

Usage:
    python3 scripts/pull_songs_snapshot.py
    python3 scripts/pull_songs_snapshot.py --url https://…/songs.json
    python3 scripts/pull_songs_snapshot.py --url file:///tmp/live.json
    python3 scripts/pull_songs_snapshot.py --allow-regression
"""

import argparse
import json
import os
import sys
import subprocess
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO_ROOT, 'assets', 'songs.json')
DEFAULT_URL = 'https://yswords-data.netlify.app/data/songs.json'

# A published catalogue that fails these is a bad publish, not new
# news — writing it into the bundle would ship a broken directory to
# every user who is offline or on first launch.
# Source → the fewest rows a good publish can have for it. The floor
# used to be a flat `< 10` applied to a set of names; `setapak` has two
# songs and always will unless that congregation posts more, so a
# single global floor cannot express it — 2 is the healthy count there,
# not a collapsed one.
#
# 2026-09-03: `setapak` is listed here even though yswords-data does
# not publish it yet, and that is deliberate. Until the fetcher is
# added there (see the note in the queue), this script will REFUSE to
# overwrite the bundle — which is the point. A pull from a dataset that
# has never heard of the source would otherwise silently delete both
# rows, and two rows out of 623 is exactly the size of loss nobody
# notices. `check_regression` catches the same thing, but that can be
# waived with --allow-regression; this cannot.
#
# 2026-09-03, same day, same reason: `ydh` (yahwehdehua.net) with a
# floor of 5. Five is the whole Songs tab of that ministry's Good
# Friday / Easter page, so anything less is a broken parse rather than
# a deletion — and, like setapak, this entry blocks the pull until
# yswords-data grows the fetcher.
REQUIRED_SOURCES = {
    'fydt': 10,
    'cdc': 10,
    'cgdc': 10,
    'cahaya': 10,
    'setapak': 2,
    'ydh': 5,
}
MIN_SONGS = 400

# A source's audio ratio is allowed to wobble by this many percentage
# points before it counts as a regression (churches occasionally pull
# one file down on purpose). 2026-08-29's CDC incident dropped the
# ratio by 6.36 points (286/286 -> 265/283); 3 points catches that with
# margin to spare. The margin is thinnest on the smallest source
# (`cahaya`, 47 rows): a single row's ordinary churn moves its ratio by
# ~2.1 points, still under 3 but only by ~0.9 — if `cahaya` starts
# false-positiving on routine single-row changes, widen the tolerance
# for that source specifically rather than raising it everywhere.
AUDIO_RATIO_TOLERANCE = 0.03


def nonempty(v):
    """Mirrors Song.fromJson's `str()` helper: null/blank -> falsy."""
    if v is None:
        return False
    return str(v).strip() != ''


def has_media(song):
    """True if a row offers ANY way to hear, watch, or read it.

    Mirrors lib/models/song.dart's `hasAudio` (audioUrl/audioTracks/
    soundcloudTrackId) plus `hasVideo`'s videoUrl/youtubeId, plus
    scoreUrl — the wider set `test/cahaya_songs_enabled_test.dart`
    requires at least one of. Missing videoUrl here would make a
    direct-mp4-only row (fydt publishes these) look dead-ended when
    the app can actually still play it.
    """
    has_playable_audio = nonempty(song.get('audioUrl')) or bool(
        song.get('audioTracks') or [])
    has_audio = has_playable_audio or nonempty(song.get('soundcloudTrackId'))
    has_video = nonempty(song.get('videoUrl')) or nonempty(
        song.get('youtubeId'))
    return has_audio or has_video or nonempty(song.get('scoreUrl'))


def has_audio_only(song):
    """Mirrors Song.hasAudio exactly (no youtube/score) for the
    per-source coverage ratio, which is what
    test/song_model_test.dart's `nearly every CDC song has audio`
    actually checks."""
    has_playable_audio = nonempty(song.get('audioUrl')) or bool(
        song.get('audioTracks') or [])
    return has_playable_audio or nonempty(song.get('soundcloudTrackId'))


def load_baseline():
    if not os.path.exists(TARGET):
        return None
    with open(TARGET, 'rb') as f:
        try:
            doc = json.load(f)
        except json.JSONDecodeError:
            return None
    return doc.get('songs') or []


def check_regression(baseline_songs, incoming_songs):
    """Compares incoming against the currently bundled snapshot.

    Returns a list of human-readable problem strings, each naming the
    specific ids affected rather than just a ratio.
    """
    problems = []

    baseline_by_id = {s['id']: s for s in baseline_songs if 'id' in s}
    incoming_by_id = {s['id']: s for s in incoming_songs if 'id' in s}

    # 1. Per-id: a row that used to offer some way to hear/read it and
    # now offers none, for ids present in both snapshots.
    lost_media_ids = sorted(
        sid for sid, base_song in baseline_by_id.items()
        if sid in incoming_by_id
        and has_media(base_song)
        and not has_media(incoming_by_id[sid])
    )
    if lost_media_ids:
        problems.append(
            f'{len(lost_media_ids)} row(s) lost their only audio/video/'
            f'score and gained no replacement: {", ".join(lost_media_ids)}')

    # 2. Per-source: net loss of rows (a source shedding ids, not just
    # churn — new ids appearing elsewhere doesn't offset this).
    def source_of(row):
        return row.get('source')

    baseline_ids_by_source = {}
    for sid, s in baseline_by_id.items():
        baseline_ids_by_source.setdefault(source_of(s), set()).add(sid)
    incoming_ids_by_source = {}
    for sid, s in incoming_by_id.items():
        incoming_ids_by_source.setdefault(source_of(s), set()).add(sid)

    for source, base_ids in baseline_ids_by_source.items():
        incoming_ids = incoming_ids_by_source.get(source, set())
        missing_ids = sorted(base_ids - incoming_ids)
        if missing_ids:
            problems.append(
                f'{source}: {len(missing_ids)} row(s) present in the '
                f'bundled snapshot vanished entirely: '
                f'{", ".join(missing_ids)}')

    # 3. Per-source: audio coverage ratio drop beyond tolerance.
    for source, base_ids in baseline_ids_by_source.items():
        incoming_ids = incoming_ids_by_source.get(source, set())
        if not base_ids or not incoming_ids:
            continue
        base_with_audio = sum(
            1 for sid in base_ids if has_audio_only(baseline_by_id[sid]))
        incoming_with_audio = sum(
            1 for sid in incoming_ids if has_audio_only(incoming_by_id[sid]))
        base_ratio = base_with_audio / len(base_ids)
        incoming_ratio = incoming_with_audio / len(incoming_ids)
        if incoming_ratio < base_ratio - AUDIO_RATIO_TOLERANCE:
            regressed_ids = sorted(
                sid for sid in (base_ids & incoming_ids)
                if has_audio_only(baseline_by_id[sid])
                and not has_audio_only(incoming_by_id[sid]))
            problems.append(
                f'{source}: audio coverage dropped from '
                f'{base_with_audio}/{len(base_ids)} '
                f'({base_ratio:.1%}) to {incoming_with_audio}/'
                f'{len(incoming_ids)} ({incoming_ratio:.1%}), beyond the '
                f'{AUDIO_RATIO_TOLERANCE:.0%} tolerance: '
                f'{", ".join(regressed_ids)}')

    return problems


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--url', default=DEFAULT_URL)
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument(
        '--allow-regression', action='store_true',
        help='Write even if the incoming snapshot regresses versus the '
             'currently bundled one. For a human who has confirmed the '
             'drop is real (a church took a file down on purpose), not '
             'for routine use.')
    args = ap.parse_args()

    print(f'Fetching {args.url} …')
    req = urllib.request.Request(
        args.url, headers={'User-Agent': 'YsWordsSnapshotPull/1.0'})
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read()

    doc = json.loads(raw)
    songs = doc.get('songs') or []
    meta = doc.get('_meta') or {}
    by_source = meta.get('bySource') or {}

    problems = []
    if len(songs) < MIN_SONGS:
        problems.append(f'only {len(songs)} songs (expected ≥{MIN_SONGS})')
    if meta.get('count') != len(songs):
        problems.append(
            f"_meta.count {meta.get('count')} != {len(songs)} rows")
    missing = set(REQUIRED_SOURCES) - set(by_source)
    if missing:
        problems.append(f'missing sources: {sorted(missing)}')
    for source, floor in REQUIRED_SOURCES.items():
        if source in by_source and by_source[source] < floor:
            problems.append(
                f'{source} has only {by_source[source]} songs '
                f'(expected ≥{floor})')

    baseline_songs = load_baseline()
    if baseline_songs is None:
        print('  (no bundled assets/songs.json to compare against — '
              'skipping regression checks)')
    elif args.allow_regression:
        regressions = check_regression(baseline_songs, songs)
        if regressions:
            print('  --allow-regression set; overriding these findings:')
            for p in regressions:
                print(f'  • {p}')
    else:
        problems.extend(check_regression(baseline_songs, songs))

    if problems:
        print('ERROR: refusing to write a suspect snapshot:',
              file=sys.stderr)
        for p in problems:
            print(f'  • {p}', file=sys.stderr)
        return 1

    print(f'  {len(songs)} songs · {by_source}')
    print(f'  generated {meta.get("generatedAt")}')

    if args.dry_run:
        print('(dry run — nothing written)')
        return 0

    with open(TARGET, 'wb') as f:
        f.write(raw)
    print(f'✓ wrote {TARGET} ({len(raw):,} bytes)')

    # Re-apply local enrichment the upstream snapshot does not carry.
    #
    # This writes the upstream bytes VERBATIM, so anything added here is
    # lost on every pull. That is not hypothetical: the 15 CDC hymn
    # `scoreUrl`s set on 2026-09-02 were wiped by the very next nightly
    # sync, and `check_regression` did not notice because the hymns still
    # have audio — `has_media` is satisfied by audio OR video OR score,
    # so losing only the score looks like no media loss at all.
    #
    # The scores are local because upstream scrapes the church's
    # `music/` directory, where songs are code-named, while the hymn PDFs
    # live in `hymns/`, named by title, which the scraper has never read.
    # Until that is fixed upstream, re-derive them here. The tool is
    # idempotent and refuses rather than guesses if a title stops
    # matching exactly one song.
    enrich = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'tools', 'add_cdc_hymn_scores.py')
    if os.path.exists(enrich):
        print('Re-applying local enrichment (CDC hymn sheet music) …')
        rc = subprocess.call([sys.executable, enrich])
        if rc != 0:
            print('ERROR: enrichment failed; assets/songs.json is now the '
                  'bare upstream snapshot and the hymns have lost their '
                  'sheet music. Fix before committing.', file=sys.stderr)
            return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
